Public Class ExitValidateProcess
    Private _qid As String
    Private _pbpPath As String
    Private _pbpPlansPath As String
    Private _pbpVBIDPath As String

    Public Sub New(ByVal qid As String, ByVal pbpPath As String, ByVal pbpPlansPath As String, ByVal pbpVBIDPath As String)
        _qid = qid
        _pbpPath = pbpPath
        _pbpPlansPath = pbpPlansPath
        _pbpVBIDPath = pbpVBIDPath
    End Sub
    Public Function GetSectionsToValidate() As List(Of String)
        Dim sections As List(Of String) = New List(Of String)
        sections.Add("WKSHTA")
        sections.Add("WKSHTB1")
        sections.Add("WKSHTB2")
        sections.Add("WKSHTB3")
        sections.Add("WKSHTB4")
        sections.Add("WKSHTB5")
        sections.Add("WKSHTB6")
        sections.Add("WKSHTB7")
        sections.Add("WKSHTB8")
        sections.Add("WKSHTB9")
        sections.Add("WKSHTB10")
        sections.Add("WKSHTB11")
        sections.Add("WKSHTB12")
        sections.Add("WKSHTB13")
        sections.Add("WKSHTB14")
        sections.Add("WKSHTB15")
        sections.Add("WKSHTB16")
        sections.Add("WKSHTB17")
        sections.Add("WKSHTB18")
        'sections.Add("WKSHTB19")
        'sections.Add("WKSHTB20")
        sections.Add("WKSHTC")
        sections.Add("SCNSETD")
        sections.Add("MRXSS000")
        Return sections
    End Function

    Public Function GetQIDSToValidate() As List(Of String)
        Dim qids As List(Of String) = New List(Of String)
        qids.Add(_qid)
        Return qids
    End Function
    Public Function Process()
        Dim resultStr As String
        resultStr = ""
        Dim wrap As PBP2019.PBPWrapper = New PBP2019.PBPWrapper()
        Dim cl As List(Of PBP2019.clsScreen) = GetScreens()
        Dim groups = From scr In cl Where scr.ScreenLevel > 0 Group By scr.Screensetname Into screens = Group
        Dim qids As List(Of String) = GetQIDSToValidate()
        Dim sections As List(Of String) = GetSectionsToValidate()
        Try
            For Each qid In qids
                wrap.Initialize(_qid, _pbpPath, _pbpPlansPath, _pbpVBIDPath)
                Dim planType As String = wrap.GetPlanType(_qid)
                Dim sectionStatusArr As String() = wrap.GetSectionStatusList(_qid)
                Dim coll As Collection = New Collection()
                For Each section In sections
                    Try
                        If GetSectionStatus(section, sectionStatusArr) <> "N/A" Then
                            'coll = wrap.ValidateSection(section)
                            'wrap.ProcA()
                            Dim sectionGrp = (From grp In groups Where grp.Screensetname = section Select grp).First()
                            Dim maxLevel = (From sc In sectionGrp.screens Select sc.ScreenLevel).Max()

                            Dim leafScreens = (From scr In sectionGrp.screens Where scr.ScreenLevel = maxLevel Select scr).ToList()
                            coll = wrap.ValidateScrnSet(section, leafScreens, planType)
                        End If
                    Catch ex1 As Exception
                        ex1 = ex1
                    End Try
                    Dim idx As Integer = 0
                    If coll.Count > 1 Then
                        For Each col In coll
                            If idx = 0 Then
                                resultStr = resultStr + col.errorstring.Split(",")(0).Trim()
                                resultStr = resultStr + Environment.NewLine
                                idx = idx + 1
                            Else
                                resultStr = resultStr + col.errorstring
                                resultStr = resultStr + Environment.NewLine
                                resultStr = resultStr + col.description
                                resultStr = resultStr + Environment.NewLine
                                resultStr = resultStr + col.screentitle
                                resultStr = resultStr + Environment.NewLine
                                resultStr = resultStr + "FIELD: " + col.fieldname
                                resultStr = resultStr + Environment.NewLine
                                resultStr = resultStr + "COLUMN: " + col.id
                                resultStr = resultStr + Environment.NewLine
                            End If
                        Next
                    End If
                Next
                resultStr = resultStr + Environment.NewLine
            Next
        Catch ex As Exception
            ex = ex
        End Try
        Return resultStr
    End Function

    Public Function GetSectionStatus(ByRef section As String, ByRef sectionStatusArray As String()) As String
        Dim retval As String = "N/A"
        Select Case section
            Case "WKSHTA"
                retval = "Incomplete"
            Case "WKSHTC"
                retval = Get_Status_BCD(sectionStatusArray(1))
            Case "SCNSETD"
                retval = Get_Status_BCD(sectionStatusArray(2))
            Case "MRXSS000"
                retval = Get_Status_BCD(sectionStatusArray(3))
            Case "WKSHTB1"
                retval = Get_Status_BCD(sectionStatusArray(4))
            Case "WKSHTB2"
                retval = Get_Status_BCD(sectionStatusArray(5))
            Case "WKSHTB3"
                retval = Get_Status_BCD(sectionStatusArray(6))
            Case "WKSHTB4"
                retval = Get_Status_BCD(sectionStatusArray(7))
            Case "WKSHTB5"
                retval = Get_Status_BCD(sectionStatusArray(8))
            Case "WKSHTB6"
                retval = Get_Status_BCD(sectionStatusArray(9))
            Case "WKSHTB7"
                retval = Get_Status_BCD(sectionStatusArray(10))
            Case "WKSHTB8"
                retval = Get_Status_BCD(sectionStatusArray(11))
            Case "WKSHTB9"
                retval = Get_Status_BCD(sectionStatusArray(12))
            Case "WKSHTB10"
                retval = Get_Status_BCD(sectionStatusArray(13))
            Case "WKSHTB11"
                retval = Get_Status_BCD(sectionStatusArray(14))
            Case "WKSHTB12"
                retval = Get_Status_BCD(sectionStatusArray(15))
            Case "WKSHTB13"
                retval = Get_Status_BCD(sectionStatusArray(16))
            Case "WKSHTB14"
                retval = Get_Status_BCD(sectionStatusArray(17))
            Case "WKSHTB15"
                retval = Get_Status_BCD(sectionStatusArray(18))
            Case "WKSHTB16"
                retval = Get_Status_BCD(sectionStatusArray(19))
            Case "WKSHTB17"
                retval = Get_Status_BCD(sectionStatusArray(20))
            Case "WKSHTB18"
                retval = Get_Status_BCD(sectionStatusArray(21))
            Case "WKSHTB19"
                retval = Get_Status_BCD(sectionStatusArray(22))
            Case "WKSHTB20"
                retval = Get_Status_BCD(sectionStatusArray(23))
        End Select
        Return retval
    End Function

    Private Function Get_Status_BCD(statusCode As String) As String
        Dim result As String = "N/A"
        If statusCode Is Nothing Then
            result = "N/A"
        Else
            If statusCode = "1" Then
                result = "New"
            ElseIf statusCode = "2" Then
                result = "Incomplete"
            ElseIf statusCode = "3" Then
                result = "Completed"
            Else
                result = "N/A"
            End If
        End If
        Return result
    End Function

    Private Function GetScreens() As List(Of PBP2019.clsScreen)
        Dim coll As New List(Of PBP2019.clsScreen)
        coll.Add(New PBP2019.clsScreen("MRXSS000", 0, "sheete", "Medicare Prescription Drug Section", "Medicare Prescription Drug Section"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd", "Medicare Rx General 1", "Medicare Rx General 1"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd0", "Defined Standard - Locations and Location Supply", "Defined Standard - Locations and Location Supply"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd1", "Medicare Rx - Notes", "Medicare Rx - Notes"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd2", "Medicare Rx General 2", "Medicare Rx General 2"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd3", "Medicare Rx General 3", "Medicare Rx General 3"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd4", "Medicare Rx - Tier Model", "Medicare Rx - Tier Model"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "ptd9", "Medicare Rx - Attestations", "Medicare Rx - Attestations"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 1, "rxvbid", "VBID - General", "VBID - General"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 2, "acteq1", "Actuarially Equivalent", "Actuarially Equivalent"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 2, "bscalt1", "Basic/Enhanced Alternative", "Basic/Enhanced Alternative"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 2, "defstnd", "Defined Standard", "Defined Standard"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 2, "vbidrx", "VBID - Package", "VBID - Package"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "actbase1", "Actuarially Equivalent Characteristics", "Actuarially Equivalent - Actuarially Equivalent Characteristics"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "actbase2", "Actuarially Equivalent - Pre-ICL", "Actuarially Equivalent - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "actbase5", "Actuarially Equivalent - OOP Threshold", "Actuarially Equivalent - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "acteq2", "Actuarially Equivalent - Pre-ICL", "Actuarially Equivalent - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "acteq3", "Actuarially Equivalent - Post-OOP", "Actuarially Equivalent - Post-OOP"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "altpoop", "Alternative - Post-OOP", "Alternative - Post-OOP"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "altpoopm", "Alternative - Medicare-Medicaid Post-OOP", "Alternative - Medicare-Medicaid Post-OOP"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscalt2", "Alternative - Pre-ICL", "Alternative - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscalt2m", "Alternative - Pre-ICL Medicare-Medicaid", "Alternative - Pre-ICL Medicare-Medicaid"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscalt3", "Alternative - ICL", "Alternative - ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscbase0", "Alternative - Deductible ", "Alternative - Deductible "))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscbase2", "Alternative - Enhanced Alternative Characteristics", "Alternative - Enhanced Alternative Characteristics"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscbase3", "Alternative - Pre-ICL", "Alternative - Pre-ICL Coverage"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscbase3m", "Alternative - Pre-ICL Medicare-Medicaid", "Alternative - Pre-ICL Medicare-Medicaid"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscbase6", "Alternative - OOP Threshold", "Alternative - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscbase7", "Alternative - Medicare-Medicaid Post-OOP Threshold", "Alternative - Medicare-Medicaid Post-OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "bscgapc", "Alternative - Gap Coverage", "Alternative - Gap Coverage"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "defbase1", "Defined Standard - ICL and OOP Threshold", "Defined Standard - ICL and OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 3, "vbidrxpak", "VBID - Package Setup", "VBID - Package Setup"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "bscgap2", "Alternative - Tier Coverage - Gap", "Alternative - Tier Coverage - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbas9a", "Actuarially Equivalent - Daily Copayment Amount Cost Sharing - Pre-ICL", "Actuarially Equivalent - Daily Copayment Amount Cost Sharing - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbas9a", "Alternative - Daily Copayment Amount Cost Sharing - Pre-ICL", "Alternative - Daily Copayment Amount Cost Sharing - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbas9a", "Alternative - Daily Copayment Amount Cost Sharing - Gap", "Alternative - Daily Copayment Amount Cost Sharing - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbas9a2", "Alternative - Medicare-Medicaid Daily Copayment Amount Cost Sharing", "Alternative - Medicare-Medicaid Daily Copayment Amount Cost Sharing"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb1", "Actuarially Equivalent - Tier Type and Cost Share Structure - Pre-ICL", "Actuarially Equivalent - Tier Type and Cost Share Structure - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb1", "Alternative - Tier Type and Cost Share Structure - Pre-ICL", "Alternative - Tier Type and Cost Share Structure - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb1", "Alternative - Tier Type and Cost Share Structure - Gap", "Alternative - Tier Type and Cost Share Structure - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb1m", "Alternative - Medicare-Medicaid Tier Type - Pre-ICL", "Alternative - Medicare-Medicaid Tier Type - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb2", "Actuarially Equivalent - Tier Locations - Pre-ICL", "Actuarially Equivalent - Tier Locations - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb2", "Alternative - Tier Locations - Pre-ICL", "Alternative - Tier Locations - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb2", "Alternative - Medicare-Medicaid Tier Locations - Pre-ICL", "Alternative - Medicare-Medicaid Tier Locations - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb2", "Alternative - Tier Locations - Gap", "Alternative - Tier Locations - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb3", "Actuarially Equivalent - Retail Pharmacy Location Supply - Pre-ICL", "Actuarially Equivalent - Retail Pharmacy Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb3", "Alternative - Retail Pharmacy Location Supply - Pre-ICL", "Alternative -  Retail Pharmacy Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb3", "Alternative - Medicare-Medicaid Retail Pharmacy Location Supply - Pre-ICL", "Alternative - Medicare-Medicaid Retail Pharmacy Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb3", "Alternative - Retail Pharmacy Location Supply - Gap", "Alternative - Retail Pharmacy Location Supply - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb4", "Actuarially Equivalent - Mail Order Location Supply - Pre-ICL", "Actuarially Equivalent - Mail Order Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb4", "Alternative - Mail Order Location Supply - Pre-ICL", "Alternative - Mail Order Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb4", "Alternative - Medicare-Medicaid Mail Order Location Supply - Pre-ICL", "Alternative - Medicare-Medicaid Mail Order Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb4", "Alternative - Mail Order Location Supply - Gap", "Alternative - Mail Order Location Supply - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb5", "Actuarially Equivalent - OON and LTC Location Supply - Pre-ICL", "Actuarially Equivalent - OON and LTC Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb5", "Alternative - OON and LTC Location Supply - Pre-ICL", "Alternative - OON and LTC Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb5", "Alternative - Medicare-Medicaid OON and LTC Location Supply - Pre-ICL", "Alternative - Medicare-Medicaid OON and LTC Location Supply - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb5", "Alternative - OON  and LTC  Location Supply - Gap", "Alternative - OON  and LTC  Location Supply - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb7", "Actuarially Equivalent - Retail Pharmacy Copayment and Coinsurance - Pre-ICL", "Actuarially Equivalent - Retail Pharmacy Copayment and Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb7", "Alternative - Retail Pharmacy Copayment and Coinsurance - Pre-ICL", "Alternative - Retail Pharmacy Copayment and Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb7", "Alternative - Retail Pharmacy Copayment and Coinsurance - Gap", "Alternative - Retail Pharmacy Copayment and Coinsurance - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb7m", "Alternative - Medicare-Medicaid Copayment - Pre-ICL", "Alternative - Medicare-Medicaid Copayment - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb8", "Actuarially Equivalent - Mail Order Copayment and Coinsurance - Pre-ICL", "Actuarially Equivalent - Mail Order Copayment and Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb8", "Alternative - Mail Order Copayment and Coinsurance - Pre-ICL", "Alternative - Mail Order Copayment and Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb8", "Alternative - Mail Order Copayment and Coinsurance - Gap", "Alternative - Mail Order Copayment and Coinsurance - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb9", "Actuarially Equivalent - OON and LTC Copayment and Coinsurance - Pre-ICL", "Actuarially Equivalent - OON and LTC Copayment and Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb9", "Alternative - OON and LTC Copayment and Coinsurance - Pre-ICL", "Alternative - OON and LTC Copayment and Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseb9", "Alternative - OON and LTC Copayment and Coinsurance - Gap", "Alternative - OON and LTC Copayment and Coinsurance - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseo1", "Actuarially Equivalent - Tier Type - Post-OOP Threshold", "Actuarially Equivalent - Tier Type - Post-OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseo1", "Alternative - Tier Type - Post-OOP Threshold", "Alternative - Tier Type - Post-OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseo2", "Actuarially Equivalent - Tier Cost Sharing - Post-OOP Threshold", "Actuarially Equivalent - Tier Cost Sharing Post - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseo2", "Alternative - Tier Cost Sharing Post-OOP Threshold", "Alternative - Tier Cost Sharing Post - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "rxbaseo3", "Alternative - Tier Type and Tier Cost Sharing Post-OOP Medicare-Medicaid", "Alternative -  Tier Type and Tier Cost Sharing Post-OOP Medicare-Medicaid"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "vbid_gap", "VBID - Gap", "VBID - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "vbid_icl", "VBID - Pre-ICL", "VBID - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "vbid_note", "VBID - Package notes", "VBID - Package notes"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 4, "vbid_oop", "VBID - OOP Threshold", "VBID - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 5, "vbid_gap2", "VBID - Package Tiers - Gap", "VBID - Package Tiers - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 5, "vbid_icl2", "VBID - Package Tiers - Pre-ICL", "VBID - Package Tiers - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 5, "vbid_oop2", "VBID - Package Tiers - OOP Threshold", "VBID - Package Tiers - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 5, "vbidnote", "VBID - Package notes", "VBID - Package notes"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbid_oop3", "VBID - Tier Coverage - OOP Threshold", "VBID - Tier Coverage - OOP Threshold"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbid_oop4", "VBID - Post OOP Threshold Cost Sharing", "VBID - Post OOP Threshold Cost Sharing"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidcovg", "VBID - Tier Coverage - Pre-ICL", "VBID - Tier Coverage - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidcovg", "VBID - Tier Coverage - Gap", "VBID - Tier Coverage - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidloc", "VBID - Tier Locations - Pre-ICL", "VBID - Tier Locations - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidloc", "VBID - Tier Locations - Gap", "VBID - Tier Locations - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb1", "VBID - Retail Copayment - Pre-ICL", "VBID - Retail Copayment - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb1", "VBID - Retail Copayment - Gap", "VBID - Retail Copayment - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb2", "VBID - Retail Coinsurance - Pre-ICL", "VBID - Retail Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb2", "VBID - Retail Coinsurance - Gap", "VBID - Retail Coinsurance - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb3", "VBID - Mail Order Copayment - Pre-ICL", "VBID - Mail Order Copayment - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb3", "VBID - Mail Order Copayment - Gap", "VBID - Mail Order Copayment - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb4", "VBID - Mail Order Coinsurance - Pre-ICL", "VBID - Mail Order Coinsurance - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb4", "VBID - Mail Order Coinsurance - Gap", "VBID - Mail Order Coinsurance - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb5", "VBID - Out-of-Network and LTC Cost Sharing - Pre-ICL", "VBID - Out-of-Network and LTC Cost Sharing - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb5", "VBID - Out-of-Network and LTC Cost Sharing - Gap", "VBID - Out-of-Network and LTC Cost Sharing - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb6", "VBID - Daily Retail and Mail Order Copay - Pre-ICL", "VBID - Daily Retail and Mail Order Copay - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb6", "VBID - Daily Retail and Mail Order Copay - Gap", "VBID - Daily Retail and Mail Order Copay - Gap"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb7", "VBID - Daily LTC Copay - Pre-ICL", "VBID - Daily LTC Copay - Pre-ICL"))
        coll.Add(New PBP2019.clsScreen("MRXSS000", 6, "vbidrxb7", "VBID - Daily LTC Copay - Gap", "VBID - Daily LTC Copay - Gap"))
        coll.Add(New PBP2019.clsScreen("OPTOON1", 3, "setd5b", "Optional Supplemental - OON Optional", "Optional Supplemental - OON Optional"))
        coll.Add(New PBP2019.clsScreen("OPTOON2", 4, "setd5b", "Optional Supplemental - OON Step-up", "Optional Supplemental - OON Step-up"))
        coll.Add(New PBP2019.clsScreen("PBPHEAD", 0, "pbphead", "Plan Status", "Plan Status"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 0, "sheetd", "Section D", "Section D"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 1, "setd0", "Section D - Plan Level", "Section D - Plan Level"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 1, "setd5.0a", "Optional Supplemental - Management Screen", "Optional Supplemental - Management Screen"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 1, "setd6", "MMP - Medicaid/plan covered cost sharing", "MMP - Medicaid/plan covered cost sharing"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd1", "Plan Deductible (Combined) - Base 1", "Plan Deductible (Combined) - Base 1"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd1a", "Plan Deductible (Combined) - Base 2", "Plan Deductible (Combined) - Base 2"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd2", "Plan Deductible (In-Network)", "Plan Deductible (In-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd3", "Plan Deductible (Out-of-Network)", "Plan Deductible (Out-of-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd4", "Plan Deductible (Non-Network)", "Plan Deductible (Non-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd5b1", "Plan Deductible LPPO/RPPO Base 3", "Plan Deductible LPPO/RPPO Base 3"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd5b2", "Plan Deductible LPPO/RPPO Base 4", "Plan Deductible LPPO/RPPO Base 4"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd5b3", "Plan Deductible LPPO/RPPO Base 5", "Plan Deductible LPPO/RPPO Base 5"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd5b4", "Plan Deductible LPPO/RPPO Base 6", "Plan Deductible LPPO/RPPO Base 6"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd8", "Plan Premium/Rebate Reduction", "Plan Premium/Rebate Reduction"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectd9", "PFFS Balance Billing", "PFFS Balance Billing"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectdppo1", "Plan Deductible LPPO/RPPO Base 1", "Plan Deductible LPPO/RPPO Base 1"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectdppo2", "Plan Deductible LPPO/RPPO Base 2", "Plan Deductible LPPO/RPPO Base 2"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectdppo3", "Deductible for LPPO/RPPO Mandatory Supplemental Benefits – Base 1", "Deductible for LPPO/RPPO Mandatory Supplemental Benefits Base 1"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "sectdppo4", "Deductible for LPPO/RPPO Mandatory Supplemental Benefits – Base 2", "Deductible for LPPO/RPPO Mandatory Supplemental Benefits Base 2"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd1a", "MSA Annual Deductible/Deposit", "MSA Annual Deductible/Deposit"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd2", "Max Enrollee Cost Limit (In-Network)", "Max Enrollee Cost Limit (In-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd2a", "Max Enrollee Cost Limit (Combined) - Base 1", "Max Enrollee Cost Limit (Combined) - Base 1"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd2a2", "Max Enrollee Cost Limit (Combined) - Base 2", "Max Enrollee Cost Limit (Combined) - Base 2"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd2b", "Max Enrollee Cost Limit (Out-of-Network)", "Max Enrollee Cost Limit (Out-of-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd2c", "Max Enrollee Cost Limit (Non-Network)", "Max Enrollee Cost Limit (Non-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd3", "Max Plan Benefit Coverage", "Max Plan Benefit Coverage"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd3a", "Max Plan Benefit Coverage (Non-Network)", "Max Plan Benefit Coverage (Non-Network)"))
        coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd4", "Notes", "Notes"))
        'coll.Add(New PBP2019.clsScreen("SCNSETD", 2, "setd5.0", "Optional Supplemental Benefit Packages", "Optional Supplemental Benefit Packages"))
        'coll.Add(New PBP2019.clsScreen("SCNSETD", 3, "setd5", "Optional Supplemental - Label and Premium", "Optional Supplemental - Label and Premium"))
        'coll.Add(New PBP2019.clsScreen("SCNSETD", 3, "setd5a", "Optional Supplemental - Service Categories", "Optional Supplemental - Service Categories"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 0, "sheeta", "Section A", "Section A"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta1", "Section A-1", "Section A-1"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta2", "Section A-3", "Section A-3"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta4", "Section A-2", "Section A-2"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta5", "Section A-4", "Section A-4"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta6", "Section A-5", "Section A-5"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta7", "Section A-6", "Section A-6"))
        coll.Add(New PBP2019.clsScreen("WKSHTA", 1, "sheeta8", "Section A-7", "Section A-7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB", 0, "sheetb", "Section B", "Section B"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 1, "s_b1_1a", "#1a Inpatient Hospital-Acute", "#1a Inpatient Hospital-Acute"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 1, "s_b1_1a2", "#1a Inpatient Hospital-Acute (B Only)", "#1a Inpatient Hospital-Acute (B Only)"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 1, "s_b1_1b", "#1b Inpatient Hospital Psychiatric", "#1b Inpatient Hospital Psychiatric"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 1, "s_b1_1b3", "#1b Inpatient Hospital Psychiatric (B Only)", "#1b Inpatient Hospital Psychiatric (B Only)"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_1ab1", "#1a Inpatient Hospital-Acute (B Only) - Base 1", "#1a Inpatient Hospital-Acute (B Only) - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_1ab2", "#1a Inpatient Hospital-Acute (B Only) - Base 2", "#1a Inpatient Hospital-Acute (B Only) - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_1ab3", "#1a Inpatient Hospital-Acute (B Only) - Base 3", "#1a Inpatient Hospital-Acute (B Only) - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_1ab4", "#1a Inpatient Hospital-Acute (B Only) - Base 4", "#1a Inpatient Hospital-Acute (B Only) - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b", "#1b Inpatient Hospital Psychiatric - Base 1", "#1b Inpatient Hospital Psychiatric - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b1", "#1b Inpatient Hospital Psychiatric (B Only) - Base 1", "#1b Inpatient Hospital Psychiatric (B Only) - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b2", "#1b Inpatient Hospital Psychiatric - Base 2", "#1b Inpatient Hospital Psychiatric - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b3", "#1b Inpatient Hospital Psychiatric - Base 5", "#1b Inpatient Hospital Psychiatric - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b4", "#1b Inpatient Hospital Psychiatric - Base 6", "#1b Inpatient Hospital Psychiatric - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b5", "#1b Inpatient Hospital Psychiatric - Base 7", "#1b Inpatient Hospital Psychiatric - Base 7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b6", "#1b Inpatient Hospital Psychiatric - Base 11", "#1b Inpatient Hospital Psychiatric - Base 11"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1_b_b7", "#1b Inpatient Hospital Psychiatric - Base 12", "#1b Inpatient Hospital Psychiatric - Base 12"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1a_b2a", "#1a Inpatient Hospital-Acute - Base 3", "#1a Inpatient Hospital-Acute - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1a_b2b", "#1a Inpatient Hospital-Acute - Base 4", "#1a Inpatient Hospital-Acute - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1a_b5a", "#1a Inpatient Hospital-Acute - Base 8", "#1a Inpatient Hospital-Acute - Base 8"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1a_b5b", "#1a Inpatient Hospital-Acute - Base 9", "#1a Inpatient Hospital-Acute - Base 9"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1a_b5c", "#1a Inpatient Hospital-Acute - Base 10", "#1a Inpatient Hospital-Acute - Base 10"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b2", "#1b Inpatient Hospital Psychiatric (B Only) - Base 2", "#1b Inpatient Hospital Psychiatric (B Only) - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b2a", "#1b Inpatient Hospital Psychiatric - Base 3", "#1b Inpatient Hospital Psychiatric - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b2b", "#1b Inpatient Hospital Psychiatric - Base 4", "#1b Inpatient Hospital Psychiatric - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b3", "#1b Inpatient Hospital Psychiatric (B Only) - Base 3", "#1b Inpatient Hospital Psychiatric (B Only) - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b4", "#1b Inpatient Hospital Psychiatric (B Only) - Base 4", "#1b Inpatient Hospital Psychiatric (B Only) - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b5", "#1b Inpatient Hospital Psychiatric (B Only) - Base 5", "#1b Inpatient Hospital Psychiatric (B Only) - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b5a", "#1b Inpatient Hospital Psychiatric - Base 8", "#1b Inpatient Hospital Psychiatric - Base 8"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b5b", "#1b Inpatient Hospital Psychiatric - Base 9", "#1b Inpatient Hospital Psychiatric - Base 9"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "b1b_b5c", "#1b Inpatient Hospital Psychiatric - Base 10", "#1b Inpatient Hospital Psychiatric - Base 10"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "s_b1_1ab", "#1a Inpatient Hospital-Acute - Base 1", "#1a Inpatient Hospital-Acute - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "s_b1_ab4", "#1a Inpatient Hospital-Acute - Base 6", "#1a Inpatient Hospital-Acute - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "s_b1_ab5", "#1a Inpatient Hospital-Acute - Base 7", "#1a Inpatient Hospital-Acute - Base 7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "s_b1_ab6", "#1a Inpatient Hospital-Acute - Base 11", "#1a Inpatient Hospital-Acute - Base 11"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "s_b1_ab7", "#1a Inpatient Hospital-Acute - Base 12", "#1a Inpatient Hospital-Acute - Base 12"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "sb1_1ab2", "#1a Inpatient Hospital-Acute - Base 2", "#1a Inpatient Hospital-Acute - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB1", 2, "sb1_1ab3", "#1a Inpatient Hospital-Acute - Base 5", "#1a Inpatient Hospital-Acute - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 1, "sb10_10a", "#10a Ambulance Services", "#10a Ambulance Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 1, "sb10_10b", "#10b Transportation Services", "#10b Transportation Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 2, "b10_a_b", "#10a Ambulance Services - Base 1", "#10a Ambulance Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 2, "b10_a_b2", "#10a Ambulance Services - Base 2", "#10a Ambulance Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 2, "b10_a_b3", "#10a Ambulance Services - Base 3", "#10a Ambulance Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 2, "b10_b_b", "#10b Transportation Services - Base 1", "#10b Transportation Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 2, "b10_b_b2", "#10b Transportation Services - Base 2", "#10b Transportation Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB10", 2, "b10_b_b3", "#10b Transportation Services - Base 3", "#10b Transportation Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 1, "sb11", "#11a DME", "#11a DME"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 1, "sb11b", "#11b Prosthetics/Medical Supplies", "#11b Prosthetics/Medical Supplies"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 1, "sb11c", "#11c Diabetic Supplies and Services", "#11c Diabetic Supplies and Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11_b", "#11a DME - Base 1", "#11a DME - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11_b2", "#11a DME - Base 2", "#11a DME - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11_b3", "#11a DME - MMP - Base 1", "#11a DME - MMP - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11_b4", "#11a DME - MMP - Base 2", "#11a DME - MMP - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11b_b", "#11b Prosthetics/Medical Supplies - Base 1", "#11b Prosthetics/Medical Supplies - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11b_b2", "#11b Prosthetics/Medical Supplies - Base 2", "#11b Prosthetics/Medical Supplies - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11b_b3", "#11b Prosthetics/Medical Supplies - Base 3", "#11b Prosthetics/Medical Supplies - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11b_b4", "#11b Prosthetics/Medical Supplies - MMP - Base 1", "#11b Prosthetics/Medical Supplies - MMP - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11c_b", "#11c Diabetic Supplies and Services - Base 1", "#11c Diabetic Supplies and Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB11", 2, "b11c_b2", "#11c Diabetic Supplies and Services - Base 2", "#11c Diabetic Supplies and Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB12", 1, "sb12", "#12 Dialysis Services", "#12 Dialysis Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB12", 2, "b12_b", "#12 Dialysis Services - Base 1", "#12 Dialysis Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB12", 2, "b12_b2", "#12 Dialysis Services - Base 2", "#12 Dialysis Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13a", "#13a Acupuncture", "#13a Acupuncture"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13b", "#13b OTC Items", "#13b OTC Items"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13c", "#13c Meal Benefit", "#13c Meal Benefit"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13d", "#13d Other 1", "#13d Other 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13e", "#13e Other 2", "#13e Other 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13f", "#13f Other 3", "#13f Other 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13g", "#13g Dual Eligible SNPs with Highly Integrated Services", "#13g Dual Eligible SNPs with Highly Integrated Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 1, "sb13_13h", "#13h Additional Services", "#13h Additional Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_a_b", "#13a Acupuncture - Base 1", "#13a Acupuncture - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_a_b2", "#13a Acupuncture - Base 2", "#13a Acupuncture - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_a_b3", "#13a Acupuncture - Base 3", "#13a Acupuncture - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_b_b1", "#13b OTC Items - Base 1", "#13b OTC Items - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_b_b2", "#13b OTC Items - Base 2", "#13b OTC Items - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_b_b3", "#13b OTC Items - Base 3", "#13b OTC Items - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_c_b1", "#13c Meal Benefit - Base 1", "#13c Meal Benefit - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_c_b2", "#13c Meal Benefit - Base 2", "#13c Meal Benefit - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_c_b3", "#13c Meal Benefit - Base 3", "#13c Meal Benefit - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_d_b1", "#13d Other 1 - Base 1", "#13d Other 1 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_d_b2", "#13d Other 1 - Base 2", "#13d Other 1 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_d_b3", "#13d Other 1 - Base 3", "#13d Other 1 - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_e_b1", "#13e Other 2 - Base 1", "#13e Other 2 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_e_b2", "#13e Other 2 - Base 2", "#13e Other 2 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_e_b3", "#13e Other 2 - Base 3", "#13e Other 2 - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_f_b1", "#13f Other 3 - Base 1", "#13f Other 3 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_f_b2", "#13f Other 3 - Base 2", "#13f Other 3 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_f_b3", "#13f Other 3 - Base 3", "#13f Other 3 - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_g_b1", "#13g Dual Eligible SNPs with Highly Integrated Services - Base 1", "#13g Dual Eligible SNPs with Highly Integrated Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_g_b2", "#13g Dual Eligible SNPs with Highly Integrated Services - Base 2", "#13g Dual Eligible SNPs with Highly Integrated Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "b13_g_b3", "#13g Dual Eligible SNPs with Highly Integrated Services - Base 3", "#13g Dual Eligible SNPs with Highly Integrated Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_10", "#13h Additional Services - Base 10", "#13h Additional Services - Base 10"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_11", "#13h Additional Services - Base 11", "#13h Additional Services - Base 11"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_12", "#13h Additional Services - Base 12", "#13h Additional Services - Base 12"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_13", "#13h Additional Services - Base 13", "#13h Additional Services - Base 13"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_14", "#13h Additional Services - Base 14", "#13h Additional Services - Base 14"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_15", "#13h Additional Services - Base 15", "#13h Additional Services - Base 15"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_16", "#13h Additional Services - Base 16", "#13h Additional Services - Base 16"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_17", "#13h Additional Services - Base 17", "#13h Additional Services - Base 17"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_18", "#13h Additional Services - Base 18", "#13h Additional Services - Base 18"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_19", "#13h Additional Services - Base 19", "#13h Additional Services - Base 19"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_20", "#13h Additional Services - Base 20", "#13h Additional Services - Base 20"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_21", "#13h Additional Services - Base 21", "#13h Additional Services - Base 21"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_22", "#13h Additional Services - Base 22", "#13h Additional Services - Base 22"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_23", "#13h Additional Services - Base 23", "#13h Additional Services - Base 23"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_24", "#13h Additional Services - Base 24", "#13h Additional Services - Base 24"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_25", "#13h Additional Services - Base 25", "#13h Additional Services - Base 25"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_26", "#13h Additional Services - Base 26", "#13h Additional Services - Base 26"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_27", "#13h Additional Services - Base 27", "#13h Additional Services - Base 27"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_28", "#13h Additional Services - Base 28", "#13h Additional Services - Base 28"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_29", "#13h Additional Services - Base 29", "#13h Additional Services - Base 29"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_30", "#13h Additional Services - Base 30", "#13h Additional Services - Base 30"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b1", "#13h Additional Services - Base 1", "#13h Additional Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b2", "#13h Additional Services - Base 2", "#13h Additional Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b3", "#13h Additional Services - Base 3", "#13h Additional Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b4", "#13h Additional Services - Base 4", "#13h Additional Services - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b5", "#13h Additional Services - Base 5", "#13h Additional Services - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b6", "#13h Additional Services - Base 6", "#13h Additional Services - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b7", "#13h Additional Services - Base 7", "#13h Additional Services - Base 7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b8", "#13h Additional Services - Base 8", "#13h Additional Services - Base 8"))
        coll.Add(New PBP2019.clsScreen("WKSHTB13", 2, "sb13_h_b9", "#13h Additional Services - Base 9", "#13h Additional Services - Base 9"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 1, "sb14_14a", "#14a Medicare-covered Zero Dollar Preventive Services", "#14a Medicare-covered Zero Dollar Preventive Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 1, "sb14_14c", "#14c Eligible Supplemental Benefits as Defined in Chapter 4", "#14c Eligible Supplemental Benefits as Defined in Chapter 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 1, "sb14_14d", "#14d Kidney Disease Education Services", "#14d Kidney Disease Education Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 1, "sb14_14e", "#14e Other Medicare-covered Preventive Services", "#14e Other Medicare-covered Preventive Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 1, "sb1414_b", "#14b Annual Physical Exam", "#14b Annual Physical Exam"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_a_b", "#14a Medicare-covered Zero Dollar Preventive Services", "#14a Medicare-covered Zero Dollar Preventive Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_b_b1", "#14b Annual Physical Exam - Base 1", "#14b Annual Physical Exam - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_b_b2", "#14b Annual Physical Exam - Base 2", "#14b Annual Physical Exam - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_b_b3", "#14b Annual Physical Exam - Base 3", "#14b Annual Physical Exam - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b1", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 1", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b10", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 10", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 10"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b11", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 11", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 11"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b2", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 2", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b3", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 3", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b4", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 4", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b5", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 5", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b6", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 6", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b7", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 7", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b8", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 8", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 8"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_c_b9", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 9", "#14c Eligible Supplemental Benefits as Defined in Chapter 4 - Base 9"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_d_b1", "#14d - Kidney Disease Education Services Base 1", "#14d - Kidney Disease Education Services Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_d_b2", "#14d - Kidney Disease Education Services Base 2", "#14d - Kidney Disease Education Services Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_d_b3", "#14d - Kidney Disease Education Services Base 3", "#14d - Kidney Disease Education Services Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_e_b1", "#14e Other Medicare-covered Preventive Services - Base 1", "#14e Other Medicare-covered Preventive Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_e_b2", "#14e Other Medicare-covered Preventive Services - Base 2", "#14e Other Medicare-covered Preventive Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_e_b3", "#14e Other Medicare-covered Preventive Services - Base 3", "#14e Other Medicare-covered Preventive Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB14", 2, "b14_e_b4", "#14e Other Medicare-covered Preventive Services - Base 4", "#14e Other Medicare-covered Preventive Services - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB15", 1, "partab", "#15 Medicare Part B Rx Drugs General", "#15 Medicare Part B Rx Drugs General"))
        coll.Add(New PBP2019.clsScreen("WKSHTB15", 2, "abgen1", "#15 Medicare Part B Rx Drugs - Base 1", "#15 Medicare Part B Rx Drugs - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB15", 2, "abgen3", "#15 Medicare Part B Rx Drugs - Base 2", "#15 Medicare Part B Rx Drugs - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB15", 2, "b15hi", "#15 Home Infusion Bundled Services", "#15 Home Infusion Bundled Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB15", 2, "drgnote3", "#15 Medicare Part B Rx Drugs - Notes", "#15 Medicare Part B Rx Drugs - Notes"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 1, "sb16a", "#16b Comprehensive Dental", "#16b Comprehensive Dental"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 1, "sb16b", "#16a Preventive Dental", "#16a Preventive Dental"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16_b", "#16b Comprehensive Dental - Base 1", "#16b Comprehensive Dental - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16_b3", "#16b Comprehensive Dental - Base 3", "#16b Comprehensive Dental - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16_b4", "#16b Comprehensive Dental - Base 4", "#16b Comprehensive Dental - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16_b6", "#16b Comprehensive Dental - Base 5", "#16b Comprehensive Dental - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16_b7", "#16b Comprehensive Dental - Base 6", "#16b Comprehensive Dental - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16a_b2", "#16b Comprehensive Dental - Base 2", "#16b Comprehensive Dental - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16b_b", "#16a Preventive Dental - Base 1", "#16a Preventive Dental - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16b_b2", "#16a Preventive Dental - Base 2", "#16a Preventive Dental - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16b_b3", "#16a Preventive Dental - Base 3", "#16a Preventive Dental - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16b_b4", "#16a Preventive Dental - Base 4", "#16a Preventive Dental - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB16", 2, "b16b_b5", "#16a Preventive Dental - Base 5", "#16a Preventive Dental - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 1, "b17a", "#17a Eye Exams", "#17a Eye Exams"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 1, "b17b", "#17b Eyewear", "#17b Eyewear"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_a_b", "#17a Eye Exams - Base 1", "#17a Eye Exams - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_a_b2", "#17a Eye Exams - Base 2", "#17a Eye Exams - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_a_b3", "#17a Eye Exams - Base 3", "#17a Eye Exams - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_b_b", "#17b Eyewear - Base 1", "#17b Eyewear - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_b_b2", "#17b Eyewear - Base 2", "#17b Eyewear - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_b_b3", "#17b Eyewear - Base 3", "#17b Eyewear - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_b_b4", "#17b Eyewear - Base 4", "#17b Eyewear - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_b_b5", "#17b Eyewear - Base 5", "#17b Eyewear - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB17", 2, "b17_b_b6", "#17b Eyewear - Base 6", "#17b Eyewear - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 1, "b18a", "#18a Hearing Exams", "#18a Hearing Exams"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 1, "b18b", "#18b Hearing Aids", "#18b Hearing Aids"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_a_b", "#18a Hearing Exams - Base 1", "#18a Hearing Exams - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_a_b2", "#18a Hearing Exams - Base 2", "#18a Hearing Exams - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_a_b3", "#18a Hearing Exams - Base 3", "#18a Hearing Exams - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_a_b4", "#18a Hearing Exams - Base 4", "#18a Hearing Exams - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_b_b", "#18b Hearing Aids - Base 1", "#18b Hearing Aids - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_b_b2", "#18b Hearing Aids - Base 2", "#18b Hearing Aids - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_b_b3", "#18b Hearing Aids - Base 3", "#18b Hearing Aids - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_b_b4", "#18b Hearing Aids - Base 4", "#18b Hearing Aids - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB18", 2, "b18_b_b5", "#18b Hearing Aids - Base 5", "#18b Hearing Aids - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 1, "b19a", "#19 VBID/MA Uniformity Flexibility", "#19 VBID/MA Uniformity Flexibility"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 1, "b19b", "#19b Additional Benefits for VBID/UF", "#19b Additional Benefits for VBID/UF"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b1", "#19a Reduced Cost Sharing for VBID/UF - Package Type", "#19a Reduced Cost Sharing for VBID/UF"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b10", "#19a Reduced Cost Sharing for VBID/UF - Base 8 (Reduced Deductible)", "#19a Reduced Cost Sharing for VBIDS - Base 8"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b11", "#19a Reduced Cost Sharing for VBID/UF - Base 9 (Reduced Deductible)", "#19a Reduced Cost Sharing for VBIDS - Base 9"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b12", "#19a Reduced Cost Sharing for VBID/UF - Base 10 (Reduced Copayment)", "#19a Reduced Cost Sharing for VBIDS - Base 10"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b13", "#19a Reduced Cost Sharing for VBID/UF - Base 11 (Reduced Copayment)", "#19a Reduced Cost Sharing for VBIDS - Base 11"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b14", "#19a Reduced Cost Sharing for VBID/UF - Base 12 (Reduced Copayment)", "#19a Reduced Cost Sharing for VBIDS - Base 12"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b15", "#19a Reduced Cost Sharing for VBID/UF - Base 13 (Reduced Copayment)", "#19a Reduced Cost Sharing for VBIDS - Base 13"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b16", "#19a Reduced Cost Sharing for VBID/UF - Base 14 (Reduced Copayment)", "#19a Reduced Cost Sharing for VBIDS - Base 15"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b17", "#19a Reduced Cost Sharing for VBID/UF - Base 15 (Reduced Specialist Coinsurance)", "#19a Reduced Cost Sharing for VBIDS - Base 16"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b18", "#19a Reduced Cost Sharing for VBID/UF - Base 16 (Reduced Specialist Deductible)", "#19a Reduced Cost Sharing for VBIDS - Base 17"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b19", "#19a Reduced Cost Sharing for VBID/UF - Base 17 (Reduced Specialist Copayment)", "#19a Reduced Cost Sharing for VBIDS - Base 18"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b20", "#19a Reduced Cost Sharing for VBID/UF - Base 18 (Retroactive Reimbursement)", "#19a Reduced Cost Sharing for VBIDS - Base 19"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b21", "#19a Reduced Cost Sharing for VBID/UF - Notes", "#19a Reduced Cost Sharing for VBIDS - Notes"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b2a", "#19a Reduced Cost Sharing for VBID/UF - Disease States: VBID", "#19a Reduced Cost Sharing for VBID/UF"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b2b", "#19a Reduced Cost Sharing for VBID/UF - Disease States: UF", "#19a Reduced Cost Sharing for VBID/UF"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b3", "#19a Reduced Cost Sharing for VBID/UF - Base 1 (Package Info)", "#19a Reduced Cost Sharing for VBIDS - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b3a", "#19a Reduced Cost Sharing for VBID/UF - MMP Benefits", "#19a Reduced Cost Sharing for VBID/UF - MMP Benefits"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b4", "#19a Reduced Cost Sharing for VBID/UF - Base 2 (OON/POS/Plan-level Deductible)", "#19a Reduced Cost Sharing for VBIDS - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b5", "#19a Reduced Cost Sharing for VBID/UF - Base 3 (Reduced Coinsurance)", "#19a Reduced Cost Sharing for VBIDS - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b6", "#19a Reduced Cost Sharing for VBID/UF - Base 4 (Reduced Coinsurance)", "#19a Reduced Cost Sharing for VBIDS - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b7", "#19a Reduced Cost Sharing for VBID/UF - Base 5 (Reduced Coinsurance)", "#19a Reduced Cost Sharing for VBIDS - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b8", "#19a Reduced Cost Sharing for VBID/UF - Base 6 (Reduced Coinsurance)", "#19a Reduced Cost Sharing for VBIDS - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_a_b9", "#19a Reduced Cost Sharing for VBID/UF - Base 7 (Reduced Coinsurance)", "#19a Reduced Cost Sharing for VBIDS - Base 7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b1", "#19b Additional Benefits for VBID/UF - Package Type", "#19b Additional Benefits for VBIDS - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b2a", "#19b Additional Benefits for VBID/UF - Disease States: VBID", "#19b Additional Benefits for VBIDS - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b2b", "#19b Additional Benefits for VBID/UF - Disease States: UF", "#19b Additional Benefits for VBIDS - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b3", "#19b Additional Benefits for VBID/UF - Base 1 (Package Info)", "#19b Additional Benefits for VBIDS - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b3a", "#19b Additional Benefits for VBID/UF - MMP Benefits", "#19b Additional Benefits for VBID/UF - MMP Benefits"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b4", "#19b Additional Benefits for VBID/UF - Base 2 (OON/POS/Plan-level Deductible)", "#19b Additional Benefits for VBIDS - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b5", "#19b Additional Benefits for VBID/UF - Base 3 (Retroactive Reimbursement)", "#19b Additional Benefits for VBIDS - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "b19_b_b6", "#19b Additional Benefits for VBID/UF - Notes", "#19b Additional Benefits for VBIDS - Notes"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "vbidb19a", "#19 VBID/MA Uniformity Flexibility", "#19 VBID/MA Uniformity Flexibility"))
        coll.Add(New PBP2019.clsScreen("WKSHTB19", 2, "vbidb19b", "#19b Additional Benefits for VBID/UF", "#19b Additional Benefits for VBID/UF"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 1, "s_b2_b", "#2 SNF", "#2 SNF"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 1, "s_b2b", "#2 SNF (B Only)", "#2 SNF (B Only)"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b", "#2 SNF - Base 1", "#2 SNF - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b_b1", "#2 SNF (B Only) - Base 1", "#2 SNF (B Only) - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b_b2", "#2 SNF (B Only) - Base 2", "#2 SNF (B Only) - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b_b3", "#2 SNF (B Only) - Base 3", "#2 SNF (B Only) - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b_b4", "#2 SNF (B Only) - Base 4", "#2 SNF (B Only) - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b2", "#2 SNF - Base 2", "#2 SNF - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_b2a", "#2 SNF - Base 3", "#2 SNF - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_bc", "#2 SNF - Base 4", "#2 SNF - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_bd", "#2 SNF - Base 5", "#2 SNF - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_be", "#2 SNF - Base 6", "#2 SNF - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_be2", "#2 SNF - Base 7", "#2 SNF - Base 7"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_be3", "#2 SNF - Base 8", "#2 SNF - Base 8"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_bf", "#2 SNF - Base 9", "#2 SNF - Base 9"))
        coll.Add(New PBP2019.clsScreen("WKSHTB2", 2, "b2_bg", "#2 SNF - Base 10", "#2 SNF - Base 10"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 1, "sb20", "#20 Outpatient Drugs", "#20 Outpatient Drugs"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "b20_b", "#20 Outpatient Drugs - Base 1", "#20 Outpatient Drugs - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "b20_b1", "#20 Home Infusion Bundled Services", "#20 Home Infusion Bundled Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "b20_b2", "#20 Outpatient Drugs - Base 3", "#20 Outpatient Drugs - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "b20_b4", "#20 Outpatient Drugs - Base 4", "#20 Outpatient Drugs - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "b20_b5", "#20 Outpatient Drugs - Base 2", "#20 Outpatient Drugs - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "drgnote2", "#20 Outpatient Drugs - Notes", "#20 Outpatient Drugs - Notes"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "sb202", "#20 Outpatient Drugs - Group 1", "#20 Outpatient Drugs - Group 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "sb203", "#20 Outpatient Drugs - Group 2", "#20 Outpatient Drugs - Group 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "sb204", "#20 Outpatient Drugs - Group 3", "#20 Outpatient Drugs - Group 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "sb205", "#20 Outpatient Drugs - Group 4", "#20 Outpatient Drugs - Group 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 2, "sb206", "#20 Outpatient Drugs - Group 5", "#20 Outpatient Drugs - Group 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b11", "#20 Outpatient Drugs - Group 2 - Base 2", "#20 Outpatient Drugs - Group 2 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b13", "#20 Outpatient Drugs - Group 3 - Base 1", "#20 Outpatient Drugs - Group 3 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b15", "#20 Outpatient Drugs - Group 3 - Base 2", "#20 Outpatient Drugs - Group 3 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b17", "#20 Outpatient Drugs - Group 4 - Base 1", "#20 Outpatient Drugs - Group 4 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b19", "#20 Outpatient Drugs - Group 4 - Base 2", "#20 Outpatient Drugs - Group 4 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b21", "#20 Outpatient Drugs - Group 5 - Base 1", "#20 Outpatient Drugs - Group 5 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b23", "#20 Outpatient Drugs - Group 5 - Base 2", "#20 Outpatient Drugs - Group 5 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b6", "#20 Outpatient Drugs - Group 1 - Base 1", "#20 Outpatient Drugs - Group 1 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b7", "#20 Outpatient Drugs - Group 1 - Base 2", "#20 Outpatient Drugs - Group 1 - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB20", 3, "b20_b9", "#20 Outpatient Drugs - Group 2 - Base 1", "#20 Outpatient Drugs - Group 2 - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB3", 1, "s_b3", "#3 Cardiac and Pulmonary Rehabilitation Services", "#3 Cardiac and Pulmonary Rehabilitation Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB3", 2, "b3_b1", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 1", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB3", 2, "b3_b2", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 2", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB3", 2, "b3_b3", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 3", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB3", 2, "b3_b4", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 4", "#3 Cardiac and Pulmonary Rehabilitation Services - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 1, "s_b4_4a", "#4a Emergency Care/Post-Stabilization Care", "#4a Emergency Care/Post-Stabilization Care"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 1, "s_b4_4b", "#4b Urgently Needed Services", "#4b Urgently Needed Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 1, "s_b4_4c", "#4c Worldwide Emergency/Urgent Coverage", "#4c Worldwide Emergency/Urgent Coverage"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_a_b", "#4a Emergency Care/Post-Stabilization Care - Base 1", "#4a Emergency Care/Post-Stabilization Care - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_a_b2", "#4a Emergency Care/Post-Stabilization Care - Base 2", "#4a Emergency Care/Post-Stabilization Care - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_b_b", "#4b Urgently Needed Services - Base 1", "#4b Urgently Needed Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_b_b2", "#4b Urgently Needed Services - Base 2", "#4b Urgently Needed Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_b_b3", "#4b Urgently Needed Services - Base 3", "#4b Urgently Needed Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_c_b", "#4c Worldwide Emergency/Urgent Coverage - Base 1", "#4c Worldwide Emergency/Urgent Coverage - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_c_b3", "#4c Worldwide Emergency/Urgent Coverage - Base 2", "#4c Worldwide Emergency/Urgent Coverage - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB4", 2, "b4_c_b4", "#4c Worldwide Emergency/Urgent Coverage - Base 3", "#4c Worldwide Emergency/Urgent Coverage - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB5", 1, "s_b5", "#5 Partial Hospitalization", "#5 Partial Hospitalization"))
        coll.Add(New PBP2019.clsScreen("WKSHTB5", 2, "b5_b", "#5 Partial Hospitalization - Base 1", "#5 Partial Hospitalization - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB5", 2, "b5_b2", "#5 Partial Hospitalization - Base 2", "#5 Partial Hospitalization - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 1, "s_b6", "#6 Home Health Services", "#6 Home Health Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 2, "b6_b", "#6 Home Health Services - Base 1", "#6 Home Health Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 2, "b6_b2", "#6 Home Health Services - Base 2", "#6 Home Health Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 2, "b6_b3", "#6 Home Health Services - Base 3", "#6 Home Health Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 2, "b6_b4", "#6 Home Health Services - MMP - Base 1", "#6 Home Health Services - MMP - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 2, "b6_b5", "#6 Home Health Services - MMP - Base 2", "#6 Home Health Services - MMP - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB6", 2, "b6_b6", "#6 Home Health Services - MMP - Base 3", "#6 Home Health Services - MMP - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7a", "#7a Primary Care Physician Services", "#7a Primary Care Physician Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7b", "#7b Chiropractic Services", "#7b Chiropractic Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7c", "#7c Occupational Therapy Services", "#7c Occupational Therapy Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7d", "#7d Physician Specialist Services", "#7d Physician Specialist Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7e", "#7e Mental Health Specialty Services", "#7e Mental Health Specialty Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7f", "#7f Podiatry Services", "#7f Podiatry Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7g", "#7g Other Health Care Professional", "#7g Other Health Care Professional"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7h", "#7h Psychiatric Services", "#7h Psychiatric Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 1, "s_b7_7i", "#7i PT and SP Services", "#7i PT and SP Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_a_b", "#7a Primary Care Physician Services - Base 1", "#7a Primary Care Physician Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_a_b1", "#7a Primary Care Physician Services - Base 2", "#7a Primary Care Physician Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_b_b", "#7b Chiropractic Services - Base 1", "#7b Chiropractic Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_b_b1", "#7b Chiropractic Services - Base 2", "#7b Chiropractic Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_b_b3", "#7b Chiropractic Services - Base 3", "#7b Chiropractic Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_c_b", "#7c Occupational Therapy Services - Base 1", "#7c Occupational Therapy Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_c_b2", "#7c Occupational Therapy Services - Base 2", "#7c Occupational Therapy Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_c_b3", "#7c Occupational Therapy Services - MMP - Base 1", "#7c Occupational Therapy Services - MMP - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_c_b4", "#7c Occupational Therapy Services - MMP - Base 2", "#7c Occupational Therapy Services - MMP - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_d_b", "#7d Physician Specialist Services - Base 1", "#7d Physician Specialist Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_d_b2", "#7d Physician Specialist Services - Base 2", "#7d Physician Specialist Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_e_b", "#7e Mental Health Specialty Services - Base 1", "#7e Mental Health Specialty Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_e_b2", "#7e Mental Health Specialty Services - Base 2", "#7e Mental Health Specialty Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_e_b3", "#7e Mental Health Specialty Services - Base 3", "#7e Mental Health Specialty Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_f_b", "#7f Podiatry Services - Base 1", "#7f Podiatry Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_f_b2", "#7f Podiatry Services - Base 2", "#7f Podiatry Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_g_b", "#7g Other Health Care Professional - Base 1", "#7g Other Health Care Professional - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_g_b2", "#7g Other Health Care Professional - Base 2", "#7g Other Health Care Professional - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_h_b", "#7h Psychiatric Services - Base 1", "#7h Psychiatric Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_h_b2", "#7h Psychiatric Services - Base 2", "#7h Psychiatric Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_h_b3", "#7h Psychiatric Services - Base 3", "#7h Psychiatric Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_i_b", "#7i PT and SP Services - Base 1", "#7i PT and SP Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_i_b2", "#7i PT and SP Services - Base 2", "#7i PT and SP Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_i_b3", "#7i PT and ST - MMP - Base 1", "#7i PT and ST - MMP - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7_i_b4", "#7i PT and ST - MMP - Base 2", "#7i PT and ST - MMP - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB7", 2, "b7f_b3", "#7f Podiatry Services - Base 3", "#7f Podiatry Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 1, "s_b8_8a", "#8a Outpatient Diag Procs/Tests/Lab Services", "#8a Outpatient Diag Procs/Tests/Lab Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 1, "s_b8_8b", "#8b Outpatient Diag/Therapeutic Rad Services", "#8b Outpatient Diag/Therapeutic Rad Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_a_b", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 1", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_a_b2", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 2", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_a_b3", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 3", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_a_b4", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 4", "#8a Outpatient Diag Procs/Tests/Lab Services - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_b_b", "#8b Outpatient Diag/Therapeutic Rad Services - Base 1", "#8b Outpatient Diag/Therapeutic Rad Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_b_b2", "#8b Outpatient Diag/Therapeutic Rad Services - Base 2", "#8b Outpatient Diag/Therapeutic Rad Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB8", 2, "b8_b_b3", "#8b Outpatient Diag/Therapeutic Rad Services - Base 3", "#8b Outpatient Diag/Therapeutic Rad Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 1, "s_b9", "#9a Outpatient Hospital Services", "#9a Outpatient Hospital Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 1, "s_b9b", "#9b ASC Services", "#9b ASC Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 1, "s_b9c", "#9c Outpatient Substance Abuse", "#9c Outpatient Substance Abuse"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 1, "s_b9d", "#9d Outpatient Blood Services", "#9d Outpatient Blood Services"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_b", "#9a Outpatient Hospital Services - Base 1", "#9a Outpatient Hospital Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_b2", "#9a Outpatient Hospital Services - Base 2", "#9a Outpatient Hospital Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_b3", "#9a Outpatient Hospital Services - Base 3", "#9a Outpatient Hospital Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_bb1", "#9b ASC Services - Base 1", "#9b ASC Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_bb2", "#9b ASC Services - Base 2", "#9b ASC Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_bb3", "#9b ASC Services - Base 3", "#9b ASC Services - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_cb1", "#9c Outpatient Substance Abuse - Base 1", "#9c Outpatient Substance Abuse - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_cb2", "#9c Outpatient Substance Abuse - Base 2", "#9c Outpatient Substance Abuse - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_cb3", "#9c Outpatient Substance Abuse - Base 3", "#9c Outpatient Substance Abuse - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_db1", "#9d Outpatient Blood Services - Base 1", "#9d Outpatient Blood Services - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTB9", 2, "b9_db2", "#9d Outpatient Blood Services - Base 2", "#9d Outpatient Blood Services - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 0, "sheetc", "Section C", "Section C"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 1, "oon", "OON", "OON"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 1, "pos", "POS", "POS"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 1, "vt", "V/T", "V/T"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "oon1", "OON - General", "OON - General"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "oon2", "OON - Inpatient", "OON - Inpatient"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "oon3_1a", "OON - Groups", "OON - Groups"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "oon3_1b1", "OON - Number of Groups", "OON - Number of Groups"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "oon4", "OON - SNF", "OON - SNF"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "posgen", "POS - General", "POS - General"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "posgrp", "POS - Groups", "POS - Groups"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "posgrps", "POS - Number of Groups", "POS - Number of Groups"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "posinp", "POS - Inpatient", "POS - Inpatient"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "possnf", "POS - SNF", "POS - SNF"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 2, "vtgenus1", "V/T - General - US", "V/T - General - US"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon1_b1", "OON - General - Base 2", "OON - General - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon1_b2", "OON - General - Base 1", "OON - General - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon2_b1", "OON - Inpatient - Base 1", "OON - Inpatient - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon2_b2", "OON - Inpatient - Base 2", "OON - Inpatient - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon2_b3", "OON - Inpatient - Base 3", "OON - Inpatient - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon2_b4", "OON - Inpatient - Base 4", "OON - Inpatient - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon3_1b2", "OON - Groups - Base 1", "OON - Groups - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon4_b1", "OON - SNF - Base 1", "OON - SNF - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oon4_b2", "OON - SNF - Base 2", "OON - SNF - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oongrpb2", "OON - Groups - Base 2", "OON - Groups - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "oonnotes", "OON - General - Notes", "OON - General - Notes"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgenb1", "POS - General - Base 1", "POS - General - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgenb2", "POS - General - Base 2", "POS - General - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgenb3", "POS - General - Base 3", "POS - General - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgenb4", "POS - General - Base 4", "POS - General - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgenb5", "POS - General - Base 5", "POS - General - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgenb6", "POS - General - Base 6", "POS - General - Base 6"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgrpb1", "POS - Groups - Base 1", "POS - Groups - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posgrpb2", "POS - Groups - Base 2", "POS - Groups - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posinpb1", "POS - Inpatient - Base 1", "POS - Inpatient - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posinpb2", "POS - Inpatient - Base 2", "POS - Inpatient - Base 2"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posinpb3", "POS - Inpatient - Base 3", "POS - Inpatient - Base 3"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posinpb4", "POS - Inpatient - Base 4", "POS - Inpatient - Base 4"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "posinpb5", "POS - Inpatient - Base 5", "POS - Inpatient - Base 5"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "possnfb1", "POS - SNF - Base 1", "POS - SNF - Base 1"))
        coll.Add(New PBP2019.clsScreen("WKSHTC", 3, "possnfb2", "POS - SNF - Base 2", "POS - SNF - Base 2"))
        Return coll
    End Function
End Class
