//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmg.equinox.integration.domain.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntegrationEntities : DbContext
    {
        public IntegrationEntities()
            : base("name=IntegrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Plugin> Plugins { get; set; }
        public DbSet<PluginProcessorError> PluginProcessorErrors { get; set; }
        public DbSet<PluginTransmissionProcessQueue> PluginTransmissionProcessQueues { get; set; }
        public DbSet<PluginVersion> PluginVersions { get; set; }
        public DbSet<PluginVersionProcessor> PluginVersionProcessors { get; set; }
        public DbSet<PluginVersionProcessorStatu> PluginVersionProcessorStatus { get; set; }
        public DbSet<PluginVersionProcessQueue> PluginVersionProcessQueues { get; set; }
        public DbSet<ELMAH_Error> ELMAH_Error { get; set; }
    }
}
