//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tmg.equinox.integration.domain.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PluginVersionProcessQueue
    {
        public int ProcessQueueId { get; set; }
        public Nullable<int> PluginVersionProcessorId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Status { get; set; }
        public Nullable<bool> HasError { get; set; }
        public string BatchId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
