using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace tmg.equinox.applicationservices.viewmodels.Report
{
    public class FaxBackReportData
    {
        public string FB_GroupName { get; set; }
        public string FB_PageNum { get; set; }
        public string FB_NetworkName { get; set; }
        public string FB_NetworkMailClaims { get; set; }
        public string FB_NetworkEDINum { get; set; }
        public string FB_NetworkPhNum { get; set; }
        public string FB_NetworkType { get; set; }
        public string FB_Referral { get; set; }
        public string FB_PrecertificationVen { get; set; }
        public string FB_PrecertificationPhNum { get; set; }
        public string FB_DrugVendorName { get; set; }
        public string FB_PlanName { get; set; }
        public string FB_NetworkWebsite { get; set; }
        public string FB_TypeofPlan { get; set; }
        public string FB_InpatientHospPreCert { get; set; }
        public string FB_OutpatientHospPreCert { get; set; }



        public string FB_DrugVendorPhNum { get; set; }
        public string FB_BenefitPeriod { get; set; }
        public string FB_BenefitPeriodACCDet { get; set; }
        public string FB_DED_T1_Ind { get; set; }
        public string FB_DED_T1_Fam { get; set; }
        public string FB_DED_T1_OT { get; set; }
        public string FB_DED_T2_Ind { get; set; }
        public string FB_DED_T2_Fam { get; set; }
        public string FB_DED_T2_OT { get; set; }
        public string FB_DED_T3_Ind { get; set; }
        public string FB_DED_T3_Fam { get; set; }
        public string FB_DED_T3_OT { get; set; }
        public string FB_DED_T4_Ind { get; set; }
        public string FB_DED_T4_Fam { get; set; }
        public string FB_DED_T4_OT { get; set; }
        public string FB_DED_AddInfo { get; set; }
        public string FB_Coins_T1_Plan { get; set; }
        public string FB_Coins_T1_Patient { get; set; }
        public string FB_Coins_T2_Plan { get; set; }
        public string FB_Coins_T2_Patient { get; set; }
        public string FB_Coins_T3_Plan { get; set; }
        public string FB_Coins_T3_Patient { get; set; }
        public string FB_Coins_T4_Plan { get; set; }
        public string FB_Coins_T4_Patient { get; set; }
        public string FB_OOP_T1_Ind { get; set; }
        public string FB_OOP_T1_Fam { get; set; }
        public string FB_OOP_T1_OT { get; set; }
        public string FB_OOP_T2_Ind { get; set; }
        public string FB_OOP_T2_Fam { get; set; }
        public string FB_OOP_T2_OT { get; set; }
        public string FB_OOP_T3_Ind { get; set; }
        public string FB_OOP_T3_Fam { get; set; }
        public string FB_OOP_T3_OT { get; set; }
        public string FB_OOP_T4_Ind { get; set; }
        public string FB_OOP_T4_Fam { get; set; }
        public string FB_OOP_T4_OT { get; set; }
        public string FB_OOP_AddInfo { get; set; }
        public string FB_HelpNum { get; set; }
        public string AboSer_T1_Value { get; set; }
        public string AcuOff_T1_Value { get; set; }
        public string AcuSer_T1_Value { get; set; }
        public string ADDADHD_T1_Value { get; set; }
        public string AllOff_T1_Value { get; set; }
        public string AllTes_T1_Value { get; set; }
        public string AllTreSer_T1_Value { get; set; }
        public string AmbSer_T1_Value { get; set; }
        public string AmbSurFac_T1_Value { get; set; }
        public string AneSer_T1_Value { get; set; }
        public string AutSer_T1_Value { get; set; }
        public string B12Inj_T1_Value { get; set; }
        public string BirCen_T1_Value { get; set; }
        public string BirCon_T1_Value { get; set; }
        public string BirConOff_T1_Value { get; set; }
        public string Vasec_T1_Value { get; set; }
        public string BrePum_T1_Value { get; set; }
        public string CarReh_T1_Value { get; set; }
        public string CatConGla_T1_Value { get; set; }
        public string CheFacPee_T1_Value { get; set; }
        public string CheOff_T1_Value { get; set; }
        public string Chemo_T1_Value { get; set; }
        public string ChiroSer_T1_Value { get; set; }
        public string ChriSciPra_T1_Value { get; set; }
        public string CocDev_T1_Value { get; set; }
        public string CosSur_T1_Value { get; set; }
        public string CusCarSer_T1_Value { get; set; }
        public string DenSerAccOff_T1_Value { get; set; }
        public string DenSerAcc_T1_Value { get; set; }
        public string DenSerNonAccOff_T1_Value { get; set; }
        public string DenSerNonAcc_T1_Value { get; set; }
        public string DerSer_T1_Value { get; set; }
        public string DiaInsSupSyi_T1_Value { get; set; }
        public string DiaLabRad_T1_Value { get; set; }
        public string DurMedEquOff_T1_Value { get; set; }
        public string DurMedEqu_T1_Value { get; set; }
        public string EduSerOff_T1_Value { get; set; }
        public string EduSer_T1_Value { get; set; }
        public string EleTelCal_T1_Value { get; set; }
        public string EmeRooFacFee_T1_Value { get; set; }
        public string EmeRooSerTruEme_T1_Value { get; set; }
        public string EmeRooSerNonTruEme_T1_Value { get; set; }
        public string ExeEqu_T1_Value { get; set; }
        public string ExpDru_T1_Value { get; set; }
        public string ExpPro_T1_Value { get; set; }
        public string FamMarCouSer_T1_Value { get; set; }
        public string GenTes_T1_Value { get; set; }
        public string GroTheSer_T1_Value { get; set; }
        public string NonRouHeaOff_T1_Value { get; set; }
        public string NonRouHeaExaAid_T1_Value { get; set; }
        public string HemOff_T1_Value { get; set; }
        public string Hemod_T1_Value { get; set; }
        public string HomHeaCarInf_T1_Value { get; set; }
        public string HosSer_T1_Value { get; set; }
        public string HosInp_T1_Value { get; set; }
        public string HosOutSur_T1_Value { get; set; }
        public string HosOutNonSur_T1_Value { get; set; }
        public string HypSer_T1_Value { get; set; }
        public string InfDiaOff_T1_Value { get; set; }
        public string InfTreOff_T1_Value { get; set; }
        public string InfSer_T1_Value { get; set; }
        public string InvDruPro_T1_Value { get; set; }
        public string LCMDisNegFee_T1_Value { get; set; }
        public string MatSer_T1_Value { get; set; }
        public string MasTheOff_T1_Value { get; set; }
        public string MasThe_T1_Value { get; set; }
        public string MedSurSup_T1_Value { get; set; }
        public string MemReqMedRecFee_T1_Value { get; set; }
        public string MenHeaSubAbuInp_T1_Value { get; set; }
        public string MenHeaSubAbuOut_T1_Value { get; set; }
        public string MilSitTheSer_T1_Value { get; set; }
        public string MorObeWeiConOff_T1_Value { get; set; }
        public string MorObeWeiCon_T1_Value { get; set; }
        public string MorObeSurOff_T1_Value { get; set; }
        public string MorObeSur_T1_Value { get; set; }
        public string NutSup_T1_Value { get; set; }
        public string OutOccThe_T1_Value { get; set; }
        public string OrtOff_T1_Value { get; set; }
        public string Ortho_T1_Value { get; set; }
        public string OrtPedSho_T1_Value { get; set; }
        public string OutPhyThe_T1_Value { get; set; }
        public string PerConIte_T1_Value { get; set; }
        public string PhyOffNonRou_T1_Value { get; set; }
        public string OrthoCatOH_T1_Value { get; set; }
        public string PodOff_T1_Value { get; set; }
        public string PodSer_T1_Value { get; set; }
        public string PriDutySer_T1_Value { get; set; }
        public string ProsOff_T1_Value { get; set; }
        public string ProsApp_T1_Value { get; set; }
        public string PulRehOff_T1_Value { get; set; }
        public string PulReh_T1_Value { get; set; }
        public string RadThe_T1_Value { get; set; }
        public string RobSur_T1_Value { get; set; }
        public string RouHeaMain_T1_Value { get; set; }
        public string RouNurCarNewInf_T1_Value { get; set; }
        public string SecSurOpiOff_T1_Value { get; set; }
        public string SecSurOpiSer_T1_Value { get; set; }
        public string SelfInfInj_T1_Value { get; set; }
        public string SexDysSer_T1_Value { get; set; }
        public string SexTraSer_T1_Value { get; set; }
        public string SkiNurFac_T1_Value { get; set; }
        public string SleDisOff_T1_Value { get; set; }
        public string SleDisStu_T1_Value { get; set; }
        public string SleDisSer_T1_Value { get; set; }
        public string SmoCesOff_T1_Value { get; set; }
        public string SmoCes_T1_Value { get; set; }
        public string OutSpeThe_T1_Value { get; set; }
        public string Sur_T1_Value { get; set; }
        public string SurSto_T1_Value { get; set; }
        public string TMJNonSurPedOff_T1_Value { get; set; }
        public string TMJSurPedOff_T1_Value { get; set; }
        public string TMJNonSurAduOff_T1_Value { get; set; }
        public string TMJSurAduOff_T1_Value { get; set; }
        public string TMJTre_T1_Value { get; set; }
        public string TransOff_T1_Value { get; set; }
        public string Trans_T1_Value { get; set; }
        public string UrgFac_T1_Value { get; set; }
        public string UrgSer_T1_Value { get; set; }
        public string NonRouVis_T1_Value { get; set; }
        public string WigsOff_T1_Value { get; set; }
        public string Wigs_T1_Value { get; set; }
        public string AboSer_T2_Value { get; set; }
        public string AcuOff_T2_Value { get; set; }
        public string AcuSer_T2_Value { get; set; }
        public string ADDADHD_T2_Value { get; set; }
        public string AllOff_T2_Value { get; set; }
        public string AllTes_T2_Value { get; set; }
        public string AllTreSer_T2_Value { get; set; }
        public string AmbSer_T2_Value { get; set; }
        public string AmbSurFac_T2_Value { get; set; }
        public string AneSer_T2_Value { get; set; }
        public string AutSer_T2_Value { get; set; }
        public string B12Inj_T2_Value { get; set; }
        public string BirCen_T2_Value { get; set; }
        public string BirCon_T2_Value { get; set; }
        public string BirConOff_T2_Value { get; set; }
        public string Vasec_T2_Value { get; set; }
        public string BrePum_T2_Value { get; set; }
        public string CarReh_T2_Value { get; set; }
        public string CatConGla_T2_Value { get; set; }
        public string CheFacPee_T2_Value { get; set; }
        public string CheOff_T2_Value { get; set; }
        public string Chemo_T2_Value { get; set; }
        public string ChiroSer_T2_Value { get; set; }
        public string ChriSciPra_T2_Value { get; set; }
        public string CocDev_T2_Value { get; set; }
        public string CosSur_T2_Value { get; set; }
        public string CusCarSer_T2_Value { get; set; }
        public string DenSerAccOff_T2_Value { get; set; }
        public string DenSerAcc_T2_Value { get; set; }
        public string DenSerNonAccOff_T2_Value { get; set; }
        public string DenSerNonAcc_T2_Value { get; set; }
        public string DerSer_T2_Value { get; set; }
        public string DiaInsSupSyi_T2_Value { get; set; }
        public string DiaLabRad_T2_Value { get; set; }
        public string DurMedEquOff_T2_Value { get; set; }
        public string DurMedEqu_T2_Value { get; set; }
        public string EduSerOff_T2_Value { get; set; }
        public string EduSer_T2_Value { get; set; }
        public string EleTelCal_T2_Value { get; set; }
        public string EmeRooFacFee_T2_Value { get; set; }
        public string EmeRooSerTruEme_T2_Value { get; set; }
        public string EmeRooSerNonTruEme_T2_Value { get; set; }
        public string ExeEqu_T2_Value { get; set; }
        public string ExpDru_T2_Value { get; set; }
        public string ExpPro_T2_Value { get; set; }
        public string FamMarCouSer_T2_Value { get; set; }
        public string GenTes_T2_Value { get; set; }
        public string GroTheSer_T2_Value { get; set; }
        public string NonRouHeaOff_T2_Value { get; set; }
        public string NonRouHeaExaAid_T2_Value { get; set; }
        public string HemOff_T2_Value { get; set; }
        public string Hemod_T2_Value { get; set; }
        public string HomHeaCarInf_T2_Value { get; set; }
        public string HosSer_T2_Value { get; set; }
        public string HosInp_T2_Value { get; set; }
        public string HosOutSur_T2_Value { get; set; }
        public string HosOutNonSur_T2_Value { get; set; }
        public string HypSer_T2_Value { get; set; }
        public string InfDiaOff_T2_Value { get; set; }
        public string InfTreOff_T2_Value { get; set; }
        public string InfSer_T2_Value { get; set; }
        public string InvDruPro_T2_Value { get; set; }
        public string LCMDisNegFee_T2_Value { get; set; }
        public string MatSer_T2_Value { get; set; }
        public string MasTheOff_T2_Value { get; set; }
        public string MasThe_T2_Value { get; set; }
        public string MedSurSup_T2_Value { get; set; }
        public string MemReqMedRecFee_T2_Value { get; set; }
        public string MenHeaSubAbuInp_T2_Value { get; set; }
        public string MenHeaSubAbuOut_T2_Value { get; set; }
        public string MilSitTheSer_T2_Value { get; set; }
        public string MorObeWeiConOff_T2_Value { get; set; }
        public string MorObeWeiCon_T2_Value { get; set; }
        public string MorObeSurOff_T2_Value { get; set; }
        public string MorObeSur_T2_Value { get; set; }
        public string NutSup_T2_Value { get; set; }
        public string OutOccThe_T2_Value { get; set; }
        public string OrtOff_T2_Value { get; set; }
        public string Ortho_T2_Value { get; set; }
        public string OrtPedSho_T2_Value { get; set; }
        public string OutPhyThe_T2_Value { get; set; }
        public string PerConIte_T2_Value { get; set; }
        public string PhyOffNonRou_T2_Value { get; set; }
        public string OrthoCatOH_T2_Value { get; set; }
        public string PodOff_T2_Value { get; set; }
        public string PodSer_T2_Value { get; set; }
        public string PriDutySer_T2_Value { get; set; }
        public string ProsOff_T2_Value { get; set; }
        public string ProsApp_T2_Value { get; set; }
        public string PulRehOff_T2_Value { get; set; }
        public string PulReh_T2_Value { get; set; }
        public string RadThe_T2_Value { get; set; }
        public string RobSur_T2_Value { get; set; }
        public string RouHeaMain_T2_Value { get; set; }
        public string RouNurCarNewInf_T2_Value { get; set; }
        public string SecSurOpiOff_T2_Value { get; set; }
        public string SecSurOpiSer_T2_Value { get; set; }
        public string SelfInfInj_T2_Value { get; set; }
        public string SexDysSer_T2_Value { get; set; }
        public string SexTraSer_T2_Value { get; set; }
        public string SkiNurFac_T2_Value { get; set; }
        public string SleDisOff_T2_Value { get; set; }
        public string SleDisStu_T2_Value { get; set; }
        public string SleDisSer_T2_Value { get; set; }
        public string SmoCesOff_T2_Value { get; set; }
        public string SmoCes_T2_Value { get; set; }
        public string OutSpeThe_T2_Value { get; set; }
        public string Sur_T2_Value { get; set; }
        public string SurSto_T2_Value { get; set; }
        public string TMJNonSurPedOff_T2_Value { get; set; }
        public string TMJSurPedOff_T2_Value { get; set; }
        public string TMJNonSurAduOff_T2_Value { get; set; }
        public string TMJSurAduOff_T2_Value { get; set; }
        public string TMJTre_T2_Value { get; set; }
        public string TransOff_T2_Value { get; set; }
        public string Trans_T2_Value { get; set; }
        public string UrgFac_T2_Value { get; set; }
        public string UrgSer_T2_Value { get; set; }
        public string NonRouVis_T2_Value { get; set; }
        public string WigsOff_T2_Value { get; set; }
        public string Wigs_T2_Value { get; set; }
        public string AboSer_T3_Value { get; set; }
        public string AcuOff_T3_Value { get; set; }
        public string AcuSer_T3_Value { get; set; }
        public string ADDADHD_T3_Value { get; set; }
        public string AllOff_T3_Value { get; set; }
        public string AllTes_T3_Value { get; set; }
        public string AllTreSer_T3_Value { get; set; }
        public string AmbSer_T3_Value { get; set; }
        public string AmbSurFac_T3_Value { get; set; }
        public string AneSer_T3_Value { get; set; }
        public string AutSer_T3_Value { get; set; }
        public string B12Inj_T3_Value { get; set; }
        public string BirCen_T3_Value { get; set; }
        public string BirCon_T3_Value { get; set; }
        public string BirConOff_T3_Value { get; set; }
        public string Vasec_T3_Value { get; set; }
        public string BrePum_T3_Value { get; set; }
        public string CarReh_T3_Value { get; set; }
        public string CatConGla_T3_Value { get; set; }
        public string CheFacPee_T3_Value { get; set; }
        public string CheOff_T3_Value { get; set; }
        public string Chemo_T3_Value { get; set; }
        public string ChiroSer_T3_Value { get; set; }
        public string ChriSciPra_T3_Value { get; set; }
        public string CocDev_T3_Value { get; set; }
        public string CosSur_T3_Value { get; set; }
        public string CusCarSer_T3_Value { get; set; }
        public string DenSerAccOff_T3_Value { get; set; }
        public string DenSerAcc_T3_Value { get; set; }
        public string DenSerNonAccOff_T3_Value { get; set; }
        public string DenSerNonAcc_T3_Value { get; set; }
        public string DerSer_T3_Value { get; set; }
        public string DiaInsSupSyi_T3_Value { get; set; }
        public string DiaLabRad_T3_Value { get; set; }
        public string DurMedEquOff_T3_Value { get; set; }
        public string DurMedEqu_T3_Value { get; set; }
        public string EduSerOff_T3_Value { get; set; }
        public string EduSer_T3_Value { get; set; }
        public string EleTelCal_T3_Value { get; set; }
        public string EmeRooFacFee_T3_Value { get; set; }
        public string EmeRooSerTruEme_T3_Value { get; set; }
        public string EmeRooSerNonTruEme_T3_Value { get; set; }
        public string ExeEqu_T3_Value { get; set; }
        public string ExpDru_T3_Value { get; set; }
        public string ExpPro_T3_Value { get; set; }
        public string FamMarCouSer_T3_Value { get; set; }
        public string GenTes_T3_Value { get; set; }
        public string GroTheSer_T3_Value { get; set; }
        public string NonRouHeaOff_T3_Value { get; set; }
        public string NonRouHeaExaAid_T3_Value { get; set; }
        public string HemOff_T3_Value { get; set; }
        public string Hemod_T3_Value { get; set; }
        public string HomHeaCarInf_T3_Value { get; set; }
        public string HosSer_T3_Value { get; set; }
        public string HosInp_T3_Value { get; set; }
        public string HosOutSur_T3_Value { get; set; }
        public string HosOutNonSur_T3_Value { get; set; }
        public string HypSer_T3_Value { get; set; }
        public string InfDiaOff_T3_Value { get; set; }
        public string InfTreOff_T3_Value { get; set; }
        public string InfSer_T3_Value { get; set; }
        public string InvDruPro_T3_Value { get; set; }
        public string LCMDisNegFee_T3_Value { get; set; }
        public string MatSer_T3_Value { get; set; }
        public string MasTheOff_T3_Value { get; set; }
        public string MasThe_T3_Value { get; set; }
        public string MedSurSup_T3_Value { get; set; }
        public string MemReqMedRecFee_T3_Value { get; set; }
        public string MenHeaSubAbuInp_T3_Value { get; set; }
        public string MenHeaSubAbuOut_T3_Value { get; set; }
        public string MilSitTheSer_T3_Value { get; set; }
        public string MorObeWeiConOff_T3_Value { get; set; }
        public string MorObeWeiCon_T3_Value { get; set; }
        public string MorObeSurOff_T3_Value { get; set; }
        public string MorObeSur_T3_Value { get; set; }
        public string NutSup_T3_Value { get; set; }
        public string OutOccThe_T3_Value { get; set; }
        public string OrtOff_T3_Value { get; set; }
        public string Ortho_T3_Value { get; set; }
        public string OrtPedSho_T3_Value { get; set; }
        public string OutPhyThe_T3_Value { get; set; }
        public string PerConIte_T3_Value { get; set; }
        public string PhyOffNonRou_T3_Value { get; set; }
        public string OrthoCatOH_T3_Value { get; set; }
        public string PodOff_T3_Value { get; set; }
        public string PodSer_T3_Value { get; set; }
        public string PriDutySer_T3_Value { get; set; }
        public string ProsOff_T3_Value { get; set; }
        public string ProsApp_T3_Value { get; set; }
        public string PulRehOff_T3_Value { get; set; }
        public string PulReh_T3_Value { get; set; }
        public string RadThe_T3_Value { get; set; }
        public string RobSur_T3_Value { get; set; }
        public string RouHeaMain_T3_Value { get; set; }
        public string RouNurCarNewInf_T3_Value { get; set; }
        public string SecSurOpiOff_T3_Value { get; set; }
        public string SecSurOpiSer_T3_Value { get; set; }
        public string SelfInfInj_T3_Value { get; set; }
        public string SexDysSer_T3_Value { get; set; }
        public string SexTraSer_T3_Value { get; set; }
        public string SkiNurFac_T3_Value { get; set; }
        public string SleDisOff_T3_Value { get; set; }
        public string SleDisStu_T3_Value { get; set; }
        public string SleDisSer_T3_Value { get; set; }
        public string SmoCesOff_T3_Value { get; set; }
        public string SmoCes_T3_Value { get; set; }
        public string OutSpeThe_T3_Value { get; set; }
        public string Sur_T3_Value { get; set; }
        public string SurSto_T3_Value { get; set; }
        public string TMJNonSurPedOff_T3_Value { get; set; }
        public string TMJSurPedOff_T3_Value { get; set; }
        public string TMJNonSurAduOff_T3_Value { get; set; }
        public string TMJSurAduOff_T3_Value { get; set; }
        public string TMJTre_T3_Value { get; set; }
        public string TransOff_T3_Value { get; set; }
        public string Trans_T3_Value { get; set; }
        public string UrgFac_T3_Value { get; set; }
        public string UrgSer_T3_Value { get; set; }
        public string NonRouVis_T3_Value { get; set; }
        public string WigsOff_T3_Value { get; set; }
        public string Wigs_T3_Value { get; set; }
        public string AboSer_T4_Value { get; set; }
        public string AcuOff_T4_Value { get; set; }
        public string AcuSer_T4_Value { get; set; }
        public string ADDADHD_T4_Value { get; set; }
        public string AllOff_T4_Value { get; set; }
        public string AllTes_T4_Value { get; set; }
        public string AllTreSer_T4_Value { get; set; }
        public string AmbSer_T4_Value { get; set; }
        public string AmbSurFac_T4_Value { get; set; }
        public string AneSer_T4_Value { get; set; }
        public string AutSer_T4_Value { get; set; }
        public string B12Inj_T4_Value { get; set; }
        public string BirCen_T4_Value { get; set; }
        public string BirCon_T4_Value { get; set; }
        public string BirConOff_T4_Value { get; set; }
        public string Vasec_T4_Value { get; set; }
        public string BrePum_T4_Value { get; set; }
        public string CarReh_T4_Value { get; set; }
        public string CatConGla_T4_Value { get; set; }
        public string CheFacPee_T4_Value { get; set; }
        public string CheOff_T4_Value { get; set; }
        public string Chemo_T4_Value { get; set; }
        public string ChiroSer_T4_Value { get; set; }
        public string ChriSciPra_T4_Value { get; set; }
        public string CocDev_T4_Value { get; set; }
        public string CosSur_T4_Value { get; set; }
        public string CusCarSer_T4_Value { get; set; }
        public string DenSerAccOff_T4_Value { get; set; }
        public string DenSerAcc_T4_Value { get; set; }
        public string DenSerNonAccOff_T4_Value { get; set; }
        public string DenSerNonAcc_T4_Value { get; set; }
        public string DerSer_T4_Value { get; set; }
        public string DiaInsSupSyi_T4_Value { get; set; }
        public string DiaLabRad_T4_Value { get; set; }
        public string DurMedEquOff_T4_Value { get; set; }
        public string DurMedEqu_T4_Value { get; set; }
        public string EduSerOff_T4_Value { get; set; }
        public string EduSer_T4_Value { get; set; }
        public string EleTelCal_T4_Value { get; set; }
        public string EmeRooFacFee_T4_Value { get; set; }
        public string EmeRooSerTruEme_T4_Value { get; set; }
        public string EmeRooSerNonTruEme_T4_Value { get; set; }
        public string ExeEqu_T4_Value { get; set; }
        public string ExpDru_T4_Value { get; set; }
        public string ExpPro_T4_Value { get; set; }
        public string FamMarCouSer_T4_Value { get; set; }
        public string GenTes_T4_Value { get; set; }
        public string GroTheSer_T4_Value { get; set; }
        public string NonRouHeaOff_T4_Value { get; set; }
        public string NonRouHeaExaAid_T4_Value { get; set; }
        public string HemOff_T4_Value { get; set; }
        public string Hemod_T4_Value { get; set; }
        public string HomHeaCarInf_T4_Value { get; set; }
        public string HosSer_T4_Value { get; set; }
        public string HosInp_T4_Value { get; set; }
        public string HosOutSur_T4_Value { get; set; }
        public string HosOutNonSur_T4_Value { get; set; }
        public string HypSer_T4_Value { get; set; }
        public string InfDiaOff_T4_Value { get; set; }
        public string InfTreOff_T4_Value { get; set; }
        public string InfSer_T4_Value { get; set; }
        public string InvDruPro_T4_Value { get; set; }
        public string LCMDisNegFee_T4_Value { get; set; }
        public string MatSer_T4_Value { get; set; }
        public string MasTheOff_T4_Value { get; set; }
        public string MasThe_T4_Value { get; set; }
        public string MedSurSup_T4_Value { get; set; }
        public string MemReqMedRecFee_T4_Value { get; set; }
        public string MenHeaSubAbuInp_T4_Value { get; set; }
        public string MenHeaSubAbuOut_T4_Value { get; set; }
        public string MilSitTheSer_T4_Value { get; set; }
        public string MorObeWeiConOff_T4_Value { get; set; }
        public string MorObeWeiCon_T4_Value { get; set; }
        public string MorObeSurOff_T4_Value { get; set; }
        public string MorObeSur_T4_Value { get; set; }
        public string NutSup_T4_Value { get; set; }
        public string OutOccThe_T4_Value { get; set; }
        public string OrtOff_T4_Value { get; set; }
        public string Ortho_T4_Value { get; set; }
        public string OrtPedSho_T4_Value { get; set; }
        public string OutPhyThe_T4_Value { get; set; }
        public string PerConIte_T4_Value { get; set; }
        public string PhyOffNonRou_T4_Value { get; set; }
        public string OrthoCatOH_T4_Value { get; set; }
        public string PodOff_T4_Value { get; set; }
        public string PodSer_T4_Value { get; set; }
        public string PriDutySer_T4_Value { get; set; }
        public string ProsOff_T4_Value { get; set; }
        public string ProsApp_T4_Value { get; set; }
        public string PulRehOff_T4_Value { get; set; }
        public string PulReh_T4_Value { get; set; }
        public string RadThe_T4_Value { get; set; }
        public string RobSur_T4_Value { get; set; }
        public string RouHeaMain_T4_Value { get; set; }
        public string RouNurCarNewInf_T4_Value { get; set; }
        public string SecSurOpiOff_T4_Value { get; set; }
        public string SecSurOpiSer_T4_Value { get; set; }
        public string SelfInfInj_T4_Value { get; set; }
        public string SexDysSer_T4_Value { get; set; }
        public string SexTraSer_T4_Value { get; set; }
        public string SkiNurFac_T4_Value { get; set; }
        public string SleDisOff_T4_Value { get; set; }
        public string SleDisStu_T4_Value { get; set; }
        public string SleDisSer_T4_Value { get; set; }
        public string SmoCesOff_T4_Value { get; set; }
        public string SmoCes_T4_Value { get; set; }
        public string OutSpeThe_T4_Value { get; set; }
        public string Sur_T4_Value { get; set; }
        public string SurSto_T4_Value { get; set; }
        public string TMJNonSurPedOff_T4_Value { get; set; }
        public string TMJSurPedOff_T4_Value { get; set; }
        public string TMJNonSurAduOff_T4_Value { get; set; }
        public string TMJSurAduOff_T4_Value { get; set; }
        public string TMJTre_T4_Value { get; set; }
        public string TransOff_T4_Value { get; set; }
        public string Trans_T4_Value { get; set; }
        public string UrgFac_T4_Value { get; set; }
        public string UrgSer_T4_Value { get; set; }
        public string NonRouVis_T4_Value { get; set; }
        public string WigsOff_T4_Value { get; set; }
        public string Wigs_T4_Value { get; set; }

        public string FB_T1_EmrgRm_Value1 { get; set; }
        public string FB_T2_EmrgRm_Value1 { get; set; }
        public string FB_T3_EmrgRm_Value1 { get; set; }
        public string FB_T4_EmrgRm_Value1 { get; set; }

        public string FB_SplPhyoNRtn_T1_Value { get; set; }
        public string FB_SplPhyoNRtn_T2_Value { get; set; }
        public string FB_SplPhyoNRtn_T3_Value { get; set; }
        public string FB_SplPhyoNRtn_T4_Value { get; set; }

        public string FB_T1_SubAb_Value { get; set; }
        public string FB_T2_SubAb_Value { get; set; }
        public string FB_T3_SubAb_Value { get; set; }
        public string FB_T4_SubAb_Value { get; set; }

        public string FB_T1_SubAbOut_Value { get; set; }
        public string FB_T2_SubAbOut_Value { get; set; }
        public string FB_T3_SubAbOut_Value { get; set; }
        public string FB_T4_SubAbOut_Value { get; set; }


        public string FB_T1_RtnVsn_Value { get; set; }
        public string FB_T2_RtnVsn_Value { get; set; }
        public string FB_T3_RtnVsn_Value { get; set; }
        public string FB_T4_RtnVsn_Value { get; set; }


        public string FB_CS_VALS_T1 { get; set; }
        public string FB_CS_VALS_T2 { get; set; }
        public string FB_CS_VALS_T3 { get; set; }
        public string FB_CS_VALS_T4 { get; set; }

        public string PCPOffVisit_T1_Value { get; set; }
        public string PCPOffVisit_T2_Value { get; set; }
        public string PCPOffVisit_T3_Value { get; set; }
        public string PCPOffVisit_T4_Value { get; set; }
        public string PCPSerWithOffVisit_T1_Value { get; set; }
        public string PCPSerWithOffVisit_T2_Value { get; set; }
        public string PCPSerWithOffVisit_T3_Value { get; set; }
        public string PCPSerWithOffVisit_T4_Value { get; set; }
        public string PCPSerNoOffVisit_T1_Value { get; set; }
        public string PCPSerNoOffVisit_T2_Value { get; set; }
        public string PCPSerNoOffVisit_T3_Value { get; set; }
        public string PCPSerNoOffVisit_T4_Value { get; set; }
        public string SpecOffVisit_T1_Value { get; set; }
        public string SpecOffVisit_T2_Value { get; set; }
        public string SpecOffVisit_T3_Value { get; set; }
        public string SpecOffVisit_T4_Value { get; set; }
        public string SpecWithOffVisit_T1_Value { get; set; }
        public string SpecWithOffVisit_T2_Value { get; set; }
        public string SpecWithOffVisit_T3_Value { get; set; }
        public string SpecWithOffVisit_T4_Value { get; set; }
        public string SpecNoOffVisit_T1_Value { get; set; }
        public string SpecNoOffVisit_T2_Value { get; set; }
        public string SpecNoOffVisit_T3_Value { get; set; }
        public string SpecNoOffVisit_T4_Value { get; set; }

        // EQN - 1147
        public string EmeRooFacFeeTrue_T1_Value { get; set; }
        public string EmeRooFacFeeTrue_T2_Value { get; set; }
        public string EmeRooFacFeeTrue_T3_Value { get; set; }
        public string EmeRooFacFeeTrue_T4_Value { get; set; }

        public string EmeRooFacFeeNonTrue_T1_Value { get; set; }
        public string EmeRooFacFeeNonTrue_T2_Value { get; set; }
        public string EmeRooFacFeeNonTrue_T3_Value { get; set; }
        public string EmeRooFacFeeNonTrue_T4_Value { get; set; }


        public string MatSerPre_T1_Value { get; set; }
        public string MatSerPre_T2_Value { get; set; }
        public string MatSerPre_T3_Value { get; set; }
        public string MatSerPre_T4_Value { get; set; }

        public string FB_BrePum_T1_Value { get; set; }
        public string FB_BrePum_T2_Value { get; set; }
        public string FB_BrePum_T3_Value { get; set; }
        public string FB_BrePum_T4_Value { get; set; }

        public string OrthoFoot_T1_Value { get; set; }
        public string OrthoFoot_T2_Value { get; set; }
        public string OrthoFoot_T3_Value { get; set; }
        public string OrthoFoot_T4_Value { get; set; }

        public string FB_T1_PhySNFCon_Value { get; set; }
        public string FB_T2_PhySNFCon_Value { get; set; }
        public string FB_T3_PhySNFCon_Value { get; set; }
        public string FB_T4_PhySNFCon_Value { get; set; }

        public string TMJTrePedi_T1_Value { get; set; }
        public string TMJTrePedi_T2_Value { get; set; }
        public string TMJTrePedi_T3_Value { get; set; }
        public string TMJTrePedi_T4_Value { get; set; }

        public string MenHeaOut_T1_Value { get; set; }
        public string MenHeaOut_T2_Value { get; set; }
        public string MenHeaOut_T3_Value { get; set; }
        public string MenHeaOut_T4_Value { get; set; }

        public string SubAbuOut_T1_Value { get; set; }
        public string SubAbuOut_T2_Value { get; set; }
        public string SubAbuOut_T3_Value { get; set; }
        public string SubAbuOut_T4_Value { get; set; }

        public string MenHeaInp_T1_Value { get; set; }
        public string MenHeaInp_T2_Value { get; set; }
        public string MenHeaInp_T3_Value { get; set; }
        public string MenHeaInp_T4_Value { get; set; }

        public string SubAbuInp_T1_Value { get; set; }
        public string SubAbuInp_T2_Value { get; set; }
        public string SubAbuInp_T3_Value { get; set; }
        public string SubAbuInp_T4_Value { get; set; }

        public string BM_Aborsrv_Limit { get; set; }
        public string BM_AcuSerO_Limit { get; set; }
        public string BM_AcuSer_Limit { get; set; }
        public string BM_AlrgOfcVist_Limit { get; set; }
        public string BM_AlrgSerm_Limit { get; set; }
        public string BM_AlrgTest_Limit { get; set; }
        public string BM_AmbSrv_Limit { get; set; }
        public string BM_AmbSrv_AirAmbulancePrecertForFToFTrans { get; set; }
        public string BM_AmbSrv_AirAmbulanceWhnAvaiActionalNWForFToFTrans { get; set; }
        public string BM_AmbSrv_ReviewComplByDentinel { get; set; }
        public string BM_AmbSrv_DoesClintElectWhnPossiForSentNegoWithProvideBehalfPlan { get; set; }
        public string BM_AmbSurFac_Limit { get; set; }
        public string BM_AnesthSrv_Limit { get; set; }
        public string BM_Autsm_Limit { get; set; }
        public string BM_B12_Limit { get; set; }
        public string BM_BrstPump_Limit { get; set; }
        public string BM_BrthCent_Limit { get; set; }
        public string BM_BrthCntrlOffVst_Limit { get; set; }
        public string BM_BrthCntrl_Limit { get; set; }
        public string BM_CardRehab_Limit { get; set; }
        public string BM_ChScPra_Limit { get; set; }
        public string BM_CheOff_Limit { get; set; }
        public string BM_Chemo_Limit { get; set; }
        public string BM_Chiro_Limit { get; set; }
        public string BM_CochDvc_Limit { get; set; }
        public string BM_ConGlss_Limit { get; set; }
        public string BM_CosmtSur_Limit { get; set; }
        public string BM_Custdl_Limit { get; set; }
        public string BM_DMediEqp_Limit { get; set; }
        public string BM_DenSerAccOff_Limit { get; set; }
        public string BM_DenSerNonAccOff_Limit { get; set; }
        public string BM_Derma_Limit { get; set; }
        public string BM_DgnLbRdo_Limit { get; set; }
        public string BM_DiabeSupp_Limit { get; set; }
        public string BM_DntlAcdnt_Limit { get; set; }
        public string BM_DntlNonAcdnt_Limit { get; set; }
        public string BM_DurMedEquOff_Limit { get; set; }
        public string BM_EduSerOff_Limit { get; set; }
        public string BM_EduSrv_Limit { get; set; }
        public string BM_ElecTelePhy_Limit { get; set; }
        public string BM_EmeRooFacFee_Limit { get; set; }
        public string BM_EmrgRm_Limit { get; set; }
        public string BM_ExprDrug_Limit { get; set; }
        public string BM_ExprProc_Limit { get; set; }
        public string BM_ExrEqup_Limit { get; set; }
        public string BM_FMCoun_Limit { get; set; }
        public string BM_FcPeel_Limit { get; set; }
        public string BM_FBPrePhNum_Limit { get; set; }
        public string BM_FeBirCtrl_Limit { get; set; }
        public string BM_FeBirCtrlOff_Limit { get; set; }
        public string BM_GenTest_Limit { get; set; }
        public string BM_GrpThrp_Limit { get; set; }
        public string BM_HemOff_Limit { get; set; }
        public string BM_Hemo_Limit { get; set; }
        public string BM_HmHlCare_Limit { get; set; }
        public string BM_HosInPtn_Limit { get; set; }
        public string BM_HosOutPtnRtn_Limit { get; set; }
        public string BM_HosOutPtnSur_Limit { get; set; }
        public string BM_HosSrv_Limit { get; set; }
        public string BM_HrExTst_Limit { get; set; }
        public string BM_Hypno_Limit { get; set; }
        public string BM_InfDiaOff_Limit { get; set; }
        public string BM_InfSrv_Limit { get; set; }
        public string BM_InfTreOff_Limit { get; set; }
        public string BM_InvDrgPrc_Limit { get; set; }
        public string BM_LcmMgmt_Limit { get; set; }
        public string BM_MDSupp_Limit { get; set; }
        public string BM_MILIEUSit_Limit { get; set; }
        public string BM_MasTheOff_Limit { get; set; }
        public string BM_MatrSrv_Limit { get; set; }
        public string BM_MemReq_Limit { get; set; }
        public string BM_MntlIn_Limit { get; set; }
        public string BM_MntlOut_Limit { get; set; }
        public string BM_MorObeOff_Limit { get; set; }
        public string BM_MorObe_Limit { get; set; }
        public string BM_MorObeSurOff_Limit { get; set; }
        public string BM_Msg_Limit { get; set; }
        public string BM_NonRouHeaOff_Limit { get; set; }
        public string BM_NonRtnVsnCGC_Limit { get; set; }
        public string BM_NonRtnVsnC_Limit { get; set; }
        public string BM_NonRtnVsn_Limit { get; set; }
        public string BM_NutSupp_Limit { get; set; }
        public string BM_ObSurg_Limit { get; set; }
        public string BM_ObWtContr_Limit { get; set; }
        public string BM_OrtOff_Limit { get; set; }
        public string BM_OrthBNKW_Limit { get; set; }
        public string BM_OrthSho_Limit { get; set; }
        public string BM_OrtFot_Limit { get; set; }
        public string BM_OrthopOff_Limit { get; set; }
        public string BM_OutOccThrp_Limit { get; set; }
        public string BM_OutPhyThrp_Limit { get; set; }
        public string BM_OutSpchTh_Limit { get; set; }
        public string BM_PCPoNonRtnC_Limit { get; set; }
        public string BM_PhOfVstNRtn_Limit { get; set; }
        public string BM_PhySNFCon_Limit { get; set; }
        public string BM_PodiSrv_Limit { get; set; }
        public string BM_Podoff_Limit { get; set; }
        public string BM_ProOff_Limit { get; set; }
        public string BM_ProsthApp_Limit { get; set; }
        public string BM_PrsnCon_Limit { get; set; }
        public string BM_PulRehOff_Limit { get; set; }
        public string BM_PulReh_Limit { get; set; }
        public string BM_PvtDNurs_Limit { get; set; }
        public string BM_RadThr_Limit { get; set; }
        public string BM_RntNusry_Limit { get; set; }
        public string BM_RoboSurg_Limit { get; set; }
        public string BM_RtnHM_Limit { get; set; }
        public string BM_RtnHM_Limit2 { get; set; }
        public string BM_RtnVsn_Limit { get; set; }
        public string BM_STSurgOpn_Limit { get; set; }
        public string BM_SecSurOff_Limit { get; set; }
        public string BM_SelfInIn_Limit { get; set; }
        public string BM_SexDFunc_Limit { get; set; }
        public string BM_SexTransfrm_Limit { get; set; }
        public string BM_SkilNursFac_Limit { get; set; }
        public string BM_SleDisOff_Limit { get; set; }
        public string BM_SleDisStu_Limit { get; set; }
        public string BM_SleDisOrd_Limit { get; set; }
        public string BM_SmkCess_Limit { get; set; }
        public string BM_SmoCesOff_Limit { get; set; }
        public string BM_SplPhyoNRtn_Limit { get; set; }
        public string BM_SurgStk_Limit { get; set; }
        public string BM_SurgnFB_Limit { get; set; }
        public string BM_TMJNonSurAduOff_Limit { get; set; }
        public string BM_TMJNonSurPedOff_Limit { get; set; }
        public string BM_TMJSurAduOff_Limit { get; set; }
        public string BM_TMJSurPedOff_Limit { get; set; }
        public string BM_TMJT_Limit { get; set; }
        public string BM_TraOff_Limit { get; set; }
        public string BM_Transpl_Limit { get; set; }
        public string BM_UrgCarFac_Limit { get; set; }
        public string BM_UrgCareF_Limit { get; set; }
        public string BM_Vsctomy_Limit { get; set; }
        public string BM_WigOff_Limit { get; set; }
        public string BM_Wings_Limit { get; set; }
        
        

        public string FB_DED_T1_EPO { get; set; }
        public string FB_DED_T1_EPC { get; set; }
        public string FB_DED_T1_EPOC { get; set; }
        public string FB_DED_T2_EPO { get; set; }
        public string FB_DED_T2_EPC { get; set; }
        public string FB_DED_T2_EPOC { get; set; }
        public string FB_DED_T3_EPO { get; set; }
        public string FB_DED_T3_EPC { get; set; }
        public string FB_DED_T3_EPOC { get; set; }
        public string FB_DED_T4_EPO { get; set; }
        public string FB_DED_T4_EPC { get; set; }
        public string FB_DED_T4_EPOC { get; set; }

        public string FB_OOP_T1_EPO { get; set; }
        public string FB_OOP_T1_EPC { get; set; }
        public string FB_OOP_T1_EPOC { get; set; }
        public string FB_OOP_T2_EPO { get; set; }
        public string FB_OOP_T2_EPC { get; set; }
        public string FB_OOP_T2_EPOC { get; set; }
        public string FB_OOP_T3_EPO { get; set; }
        public string FB_OOP_T3_EPC { get; set; }
        public string FB_OOP_T3_EPOC { get; set; }
        public string FB_OOP_T4_EPO { get; set; }
        public string FB_OOP_T4_EPC { get; set; }
        public string FB_OOP_T4_EPOC { get; set; }















    }
}
