using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace tmg.equinox.applicationservices.viewmodels.Report
{
    public class SPDData
    {
        public string SPD_GrpName { get; set; }
        public string SPD_EffDate { get; set; }
        public string SPD_OrgEffDate { get; set; }
        public string SPD_UnPlnStats { get; set; }
        public string SPD_PlnSpnsrInfo_Name { get; set; }
        public string SPD_PlnSpnsrInfo_Address { get; set; }
        public string SPD_PlnSpnsrInfo_Phone { get; set; }
        public string SPD_TaxID { get; set; }
        public string SPD_PlnStats { get; set; }
        public string SPD_ErsPlnStats { get; set; }
        public string SPD_ErsPlnNo { get; set; }
        public string SPD_PlnYrBegnDt { get; set; }
        public string SPD_PlnYrEndDt { get; set; }
        public string SPD_PartEmpList { get; set; }
        public string SPD_AgentSrvPrc_Name { get; set; }
        public string SPD_AgentSrvPrc_Address { get; set; }
        public string SPD_AgentSrvPrc_Phone { get; set; }
        public string SPD_MtrElgMem { get; set; }
        public string SPD_InPtntPreCrtSrvs { get; set; }
        public string SPD_OutPtntPreCrtSrvs { get; set; }
        public string SPD_InPtntPreCrtPnlty { get; set; }
        public string SPD_InPtntPreCrtPnlty2 { get; set; }
        public string SPD_OutPtntPreCrtPnlty3 { get; set; }
        public string SPD_OutPtntPreCrtPnlty { get; set; }
        public string SPD_OutPtntPreCrtPnlty2 { get; set; }
        public string SPD_InPtntPreCrtPnlty3 { get; set; }
        public string SPD_OlogyBnfts { get; set; }
        public string SPD_WllnsPln { get; set; }
        public string SPD_AccmlnPrd { get; set; }
        public string Exc_StdLimitExcl { get; set; }
        public string Exc_StdLimitExcl_Hdr { get; set; }
        public string Exc_HzdPHobActLimitExcl_Hdr { get; set; }
        public string Exc_HzdPHobActLimitExcl_Info { get; set; }
        public string Exc_HzdInjTerrainCov { get; set; }
        public string Exc_FamMemLimitExc { get; set; }
        public string Exc_IllegActLimitExc { get; set; }
        public string Exc_IllegActLimitExcAdd { get; set; }
        public string Exc_OthLimitExc_HDr { get; set; }
        public string Exc_OthLimitExc { get; set; }
        public string Exc_OccuInjLimitExc { get; set; }
        public string Exc_OccuInjLimitExcAdd { get; set; }
        public string Exc_AddExcLimit_Trtment { get; set; }
        public string Exc_AddExcLimit_Lang { get; set; }
        public string SPD_ADM_MemEnr_MemElig_OpenEnro_EffeDt { get; set; }
        public string SPD_ADM_MemEnr_MemElig_FullTimeEmp { get; set; }
        public string SPD_ADM_MemEnr_MemElig_PartTimeEmp { get; set; }
        public string SPD_ADM_MemEnr_MemElig_AllowSplitCoverage { get; set; }
        public string SPD_ADM_MemEnr_MemElig_TermLangOpt1 { get; set; }
        public string SPD_ADM_MemEnr_MemElig_TermLangOpt2 { get; set; }
        public string SPD_ADM_MemEnr_MemElig_EligDependent { get; set; }
        public string SPD_ADM_Elig_EmployeeClass { get; set; }
        public string SPD_ADM_Elig_EnrollmentEffective { get; set; }
        public string SPD_ADM_Elig_WaitingPeriod { get; set; }
        public string SPD_ADM_Elig_TerminationEffective { get; set; }
        public string SPD_ADM_MemEnr_DepCovInfo_ChildDep_AgeLimit { get; set; }
        public string SPD_ADM_MemEnr_DepCovInfo_ChildDep_TerminEffective { get; set; }
        public string SPD_ADM_MemEnr_InCapChild_BeginingAge { get; set; }
        public string SPD_ADM_MemEnr_InCapChild_Lang1 { get; set; }
        public string SPD_ADM_MemEnr_InCapChild_Lang2 { get; set; }
        public string SPD_ADM_MemEnr_InCapChild_NonStandChildLang { get; set; }
        public string SPD_ADM_MemEnr_DependentCovInfo_Recertification { get; set; }
        public string SPD_ADM_Eligibility_Option1 { get; set; }
        public string SPD_ADM_Eligibility_Option2 { get; set; }
        public string SPD_ADM_Eligibility_NonStandardOption { get; set; }
        public string SPD_ADM_NewlyAcquiredDependents { get; set; }
        public string SPD_ADM_CoverageEmpAndDep { get; set; }
        public string SPD_ADM_ReqForEmpCover { get; set; }
        public string SPD_ADM_LossOfCoverage_CovOn { get; set; }
        public string SPD_ADM_LossOfCoverage_OtherOption { get; set; }
        public string SPD_ADM_EligNewDep_Othertext { get; set; }
        public string SPD_ADM_EligNewDep_EmpContCoverage_Layoff { get; set; }
        public string SPD_ADM_EligNewDep_EmpContCoverage_TotalDisability { get; set; }
        public string SPD_ADM_EligNewDep_EmpContCoverage_FMLA { get; set; }
        public string SPD_ADM_EligNewDep_EmpContCoverage_FMLAYES { get; set; }
        public string SPD_ADM_Elig_QualExi_Language1 { get; set; }
        public string SPD_ADM_Elig_QualExi_Language2 { get; set; }
        public string SPD_ADM_Elig_ContinDurUSERRA { get; set; }
        public string SPD_ADM_Elig_QualEven_IsLegSepQuaEvent { get; set; }
        public string SPD_ADM_Elig_QualEven_EmpQualEvent { get; set; }
        public string SPD_MED_Tim_Filing { get; set; }
        public string SPD_MED_TimFiling_Details { get; set; }
        public string SPD_MED_EOB_Comment { get; set; }
        public string SPD_MED_ClaimProc_Payment { get; set; }
        public string SPD_MED_Time_ClaimDec { get; set; }
        public string SPD_NonUS_Provider { get; set; }
        public string SPD_CorBen_Subrog { get; set; }
        public string SPD_CorBen_COB { get; set; }
        public string SPD_CorBen_COBNonMed { get; set; }
        public string SPD_CorBen_COBMed { get; set; }
        public string SPD_CorBen_RetCov { get; set; }
        public string SPD_ADM_GrpPlanDocDet { get; set; }
        public string SPD_MED_TimFilClamDecApealAdmConInfo_Type { get; set; }
        public string SPD_MED_TimFilClamDecApealAdmConInfo_ComName { get; set; }
        public string SPD_MED_TimFilClamDecApealAdmConInfo_ContName { get; set; }
        public string SPD_MED_TimFilClamDecApealAdmConInfo_Address { get; set; }
        public string SPD_MED_TimFilClamDecApealAdmConInfo_Fax { get; set; }
        public string SPD_MED_TimFilClamDecApealAdmConInfo_AddInfo { get; set; }
        public string SPD_MED_TimFilPresclamapeal_Type { get; set; }
        public string SPD_MED_TimFilPresclamapeal_ComName { get; set; }
        public string SPD_MED_TimFilPresclamapeal_ContName { get; set; }
        public string SPD_MED_TimFilPresclamapeal_Address { get; set; }
        public string SPD_MED_TimFilPresclamapeal_Fax { get; set; }
        public string SPD_MED_TimFilPresclamapeal_AddInfo { get; set; }
        public string SPD_ADM_GrpInfoPlanDocPrivOff_Name { get; set; }
        public string SPD_ADM_GrpInfoPlanDocPrivOff_Address { get; set; }
        public string SPD_ADM_GrpInfoPlanDocPrivOff_Phone { get; set; }
        public string SPD_MED_PresDrugMEDRxInteg { get; set; }
        public string SPD_MED_PresDrugPreCostShare { get; set; }
        public string SPD_Mscloskltl_Chiroprctic { get; set; }
        public string SPD_Maternity { get; set; }
        public string SPD_Mtrnty_Abort { get; set; }
        public string SPD_ADM_PlnDocDetls_Dylsis { get; set; }
        public string SPD_ADM_PlnDocDetls_Onclogy { get; set; }
        public string SPD_MED_PlanSpecificServicesQZ_Travel { get; set; }
        public string BAM_COBRA_BT { get; set; }
        public string BAM_COBRA_ConInfo { get; set; }
        public string BAM_COBRA_VenConInfo { get; set; }
        public string BAM_COBRA_TandReComm { get; set; }
        public string BAM_COBRA_TopA { get; set; }
        public string BAM_COBRA_SDT { get; set; }
        public string BAM_COBRA_Serv { get; set; }
        public string BAM_COBRA_UNameAndEg { get; set; }
        public string BAM_COBRA_PassAndEg { get; set; }
        public string BAM_COBRA_AdminContact { get; set; }
        public string BAM_HSA_FormLink { get; set; }
        public string BAM_HSA_HSBFormLink { get; set; }
        public string BAM_COBRA_TremClient { get; set; }
        public string SPD_EyeRefractns_Srvc { get; set; }
        public string SPD_Glaucoma_Srvc { get; set; }
        public string SPD_Gleevec_Srvc { get; set; }
        public string SPD_Bereavement_Srvc { get; set; }
        public string SPD_Infertility_Srvc { get; set; }
        public string SPD_TMJ_Srvc { get; set; }
        public string SPD_Sentinel_Srvc { get; set; }
        public string SPD_PreAdmsn_Srvc { get; set; }
        public string SPD_SecSurgical_Srvc { get; set; }
        public string BM_CS_VALS_T1 { get; set; }
        public string BM_CS_MNN_T1 { get; set; }
        public string BM_CS_VALS_T2 { get; set; }
        public string BM_CS_MNN_T2 { get; set; }
        public string BM_CS_VALS_T3 { get; set; }
        public string BM_CS_MNN_T3 { get; set; }
        public string BM_CS_VALS_T4 { get; set; }
        public string BM_CS_MNN_T4 { get; set; }
        public string BM_GI_Ded_NetworkInfo { get; set; }
        public string BM_GI_Ded_T1_Indv { get; set; }
        public string BM_GI_Ded_T1_Fmly { get; set; }
        public string BM_GI_Ded_T1_OT { get; set; }
        public string BM_GI_Ded_T1_OT2 { get; set; }
        public string BM_GI_Ded_T1_EmpPlusOneChild { get; set; }
        public string BM_GI_Ded_T2_Indv { get; set; }
        public string BM_GI_Ded_T2_Fmly { get; set; }
        public string BM_GI_Ded_T2_OT { get; set; }
        public string BM_GI_Ded_T2_OT2 { get; set; }
        public string BM_GI_Ded_T2_EmpPlusOneChild { get; set; }
        public string BM_GI_Ded_T3_Indv { get; set; }
        public string BM_GI_Ded_T3_Fmly { get; set; }
        public string BM_GI_Ded_T3_OT { get; set; }
        public string BM_GI_Ded_T3_OT2 { get; set; }
        public string BM_GI_Ded_T3_EmpPlusOneChild { get; set; }
        public string BM_GI_Ded_T4_Indv { get; set; }
        public string BM_GI_Ded_T4_Fmly { get; set; }
        public string BM_GI_Ded_T4_OT { get; set; }
        public string BM_GI_Ded_T4_OT2 { get; set; }
        public string BM_GI_Ded_T4_EmpPlusOneChild { get; set; }
        public string BM_GI_Ded_AddInfo { get; set; }
        public string BM_GI_Ded_AddInfo_2 { get; set; }
        public string BM_CS_DedAdditionalDedInfo { get; set; }
        public string BM_GI_Con_Value { get; set; }
        public string BM_GI_Con_T1_PlPy { get; set; }
        public string BM_GI_Con_T1_PtPy { get; set; }
        public string BM_GI_Con_T2_PlPy { get; set; }
        public string BM_GI_Con_T2_PtPy { get; set; }
        public string BM_GI_Con_T3_PlPy { get; set; }
        public string BM_GI_Con_T3_PtPy { get; set; }
        public string BM_GI_Con_T4_PlPy { get; set; }
        public string BM_GI_Con_T4_PtPy { get; set; }
        public string BM_GI_OutPkt_NtwrkInfo { get; set; }
        public string BM_GI_OutPkt_T1_Indv { get; set; }
        public string BM_GI_OutPkt_T1_Fmly { get; set; }
        public string BM_GI_OutPkt_T1_OT { get; set; }
        public string BM_GI_OutPkt_T1_OT2 { get; set; }
        public string BM_GI_OutPkt_T1_EmpPlusOneChild { get; set; }
        public string BM_GI_OutPkt_T2_Indv { get; set; }
        public string BM_GI_OutPkt_T2_Fmly { get; set; }
        public string BM_GI_OutPkt_T2_OT { get; set; }
        public string BM_GI_OutPkt_T2_OT2 { get; set; }
        public string BM_GI_OutPkt_T2_EmpPlusOneChild { get; set; }
        public string BM_GI_OutPkt_T3_Indv { get; set; }
        public string BM_GI_OutPkt_T3_Fmly { get; set; }
        public string BM_GI_OutPkt_T3_OT { get; set; }
        public string BM_GI_OutPkt_T3_OT2 { get; set; }
        public string BM_GI_OutPkt_T3_EmpPlusOneChild { get; set; }
        public string BM_GI_OutPkt_T4_Indv { get; set; }
        public string BM_GI_OutPkt_T4_Fmly { get; set; }
        public string BM_GI_OutPkt_T4_OT { get; set; }
        public string BM_GI_OutPkt_T4_OT2 { get; set; }
        public string BM_GI_OutPkt_T4_EmpPlusOneChild { get; set; }
        public string BM_GI_OutPkt_AddInfo { get; set; }
        public string BM_GI_OutPkt_AddInfo_1 { get; set; }
        public string BM_CopOutofPoc_Max { get; set; }
        public string BM_GI_OOPCopayInfo_T1_Indv { get; set; }
        public string BM_GI_OOPCopayInfo_T1_Fmly { get; set; }
        public string BM_GI_OOPCopayInfo_T1_OT { get; set; }
        public string BM_GI_OOPCopayInfo_T1_OT2 { get; set; }
        public string BM_GI_OOPCopayInfo_T1_EmpPlusOneChild { get; set; }
        public string BM_GI_OOPCopayInfo_T2_Indv { get; set; }
        public string BM_GI_OOPCopayInfo_T2_Fmly { get; set; }
        public string BM_GI_OOPCopayInfo_T2_OT { get; set; }
        public string BM_GI_OOPCopayInfo_T2_OT2 { get; set; }
        public string BM_GI_OOPCopayInfo_T2_EmpPlusOneChild { get; set; }
        public string BM_GI_OOPCopayInfo_T3_Indv { get; set; }
        public string BM_GI_OOPCopayInfo_T3_Fmly { get; set; }
        public string BM_GI_OOPCopayInfo_T3_OT { get; set; }
        public string BM_GI_OOPCopayInfo_T3_OT2 { get; set; }
        public string BM_GI_OOPCopayInfo_T3_EmpPlusOneChild { get; set; }
        public string BM_GI_OOPCopayInfo_T4_Indv { get; set; }
        public string BM_GI_OOPCopayInfo_T4_Fmly { get; set; }
        public string BM_GI_OOPCopayInfo_T4_OT { get; set; }
        public string BM_GI_OOPCopayInfo_T4_OT2 { get; set; }
        public string BM_GI_OOPCopayInfo_T4_EmpPlusOneChild { get; set; }
        public string BM_CopOutofPoc_Max_2 { get; set; }
        public string BM_T1_Aborsrv_OthrSrvWO { get; set; }
        public string BM_T2_Aborsrv_OthrSrvWO { get; set; }
        public string BM_T3_Aborsrv_OthrSrvWO { get; set; }
        public string BM_T4_Aborsrv_OthrSrvWO { get; set; }
        public string BM_Aborsrv_Limit { get; set; }
        public string BM_T1_AcuSerO_NotCov { get; set; }
        public string BM_T2_AcuSerO_NotCov { get; set; }
        public string BM_T3_AcuSerO_NotCov { get; set; }
        public string BM_T4_AcuSerO_NotCov { get; set; }
        public string BM_AcuSerO_Limit { get; set; }
        public string BM_T1_AcuSerO_NotCov_Spe { get; set; }
        public string BM_T2_AcuSerO_NotCov_Spe { get; set; }
        public string BM_T3_AcuSerO_NotCov_Spe { get; set; }
        public string BM_T4_AcuSerO_NotCov_Spe { get; set; }
        public string BM_AcuSerO_Spe_Limit { get; set; }
        public string BM_T1_AcuSer_NotCov { get; set; }
        public string BM_T2_AcuSer_NotCov { get; set; }
        public string BM_T3_AcuSer_NotCov { get; set; }
        public string BM_T4_AcuSer_NotCov { get; set; }
        public string BM_AcuSer_Limit { get; set; }
        public string BM_T1_AddADHD_Value { get; set; }
        public string BM_T2_AddADHD_Value { get; set; }
        public string BM_T3_AddADHD_Value { get; set; }
        public string BM_T4_AddADHD_Value { get; set; }
        public string BM_AddADHD_Limit { get; set; }
        public string BM_T1_AlrgOfcVist_PCP { get; set; }
        public string BM_T2_AlrgOfcVist_PCP { get; set; }
        public string BM_T3_AlrgOfcVist_PCP { get; set; }
        public string BM_T4_AlrgOfcVist_PCP { get; set; }
        public string BM_AlrgOfcVist_Limit { get; set; }
        public string BM_T1_AlrgOfcVist_PCP_Spe { get; set; }
        public string BM_T2_AlrgOfcVist_PCP_Spe { get; set; }
        public string BM_T3_AlrgOfcVist_PCP_Spe { get; set; }
        public string BM_T4_AlrgOfcVist_PCP_Spe { get; set; }
        public string BM_AlrgOfcVist_Spe_Limit { get; set; }
        public string BM_T1_AlrgTest_Value { get; set; }
        public string BM_T2_AlrgTest_Value { get; set; }
        public string BM_T3_AlrgTest_Value { get; set; }
        public string BM_T4_AlrgTest_Value { get; set; }
        public string BM_AlrgTest_Limit { get; set; }
        public string BM_T1_AlrgSerm_Value { get; set; }
        public string BM_T2_AlrgSerm_Value { get; set; }
        public string BM_T3_AlrgSerm_Value { get; set; }
        public string BM_T4_AlrgSerm_Value { get; set; }
        public string BM_AlrgSerm_Limit { get; set; }
        public string BM_T1_AmbSrv_Value { get; set; }
        public string BM_T2_AmbSrv_Value { get; set; }
        public string BM_T3_AmbSrv_Value { get; set; }
        public string BM_T4_AmbSrv_Value { get; set; }
        public string BM_AmbSrv_Limit { get; set; }
        public string BM_AmbSrv_AirAmbulance { get; set; }
        public string BM_AmbSrv_AirAmbulancePrecertForFToFTrans { get; set; }
        public string BM_AmbSrv_AirAmbulanceWhnAvaiActionalNWForFToFTrans { get; set; }
        public string BM_AmbSrv_ReviewComplByDentinel { get; set; }
        public string BM_AmbSrv_DoesClintElectWhnPossiForSentNegoWithProvideBehalfPlan { get; set; }
        public string BM_T1_AmbSurFac_Value { get; set; }
        public string BM_T2_AmbSurFac_Value { get; set; }
        public string BM_T3_AmbSurFac_Value { get; set; }
        public string BM_T4_AmbSurFac_Value { get; set; }
        public string BM_AmbSurFac_Limit { get; set; }
        public string BM_T1_AnesthSrv_Value { get; set; }
        public string BM_T2_AnesthSrv_Value { get; set; }
        public string BM_T3_AnesthSrv_Value { get; set; }
        public string BM_T4_AnesthSrv_Value { get; set; }
        public string BM_AnesthSrv_Limit { get; set; }
        public string BM_T1_AquaThrpy_Value { get; set; }
        public string BM_T2_AquaThrpy_Value { get; set; }
        public string BM_T3_AquaThrpy_Value { get; set; }
        public string BM_T4_AquaThrpy_Value { get; set; }
        public string BM_AquaThrpy_Limit { get; set; }
        public string BM_T1_Autsm_Value { get; set; }
        public string BM_T2_Autsm_Value { get; set; }
        public string BM_T3_Autsm_Value { get; set; }
        public string BM_T4_Autsm_Value { get; set; }
        public string BM_Autsm_Limit { get; set; }
        public string BM_T1_B12_Value { get; set; }
        public string BM_T2_B12_Value { get; set; }
        public string BM_T3_B12_Value { get; set; }
        public string BM_T4_B12_Value { get; set; }
        public string BM_B12_Limit { get; set; }
        public string BM_T1_BrthCent_Value { get; set; }
        public string BM_T2_BrthCent_Value { get; set; }
        public string BM_T3_BrthCent_Value { get; set; }
        public string BM_T4_BrthCent_Value { get; set; }
        public string BM_BrthCent_Limit { get; set; }
        public string BM_T1_BrthCntrl_Value { get; set; }
        public string BM_T2_BrthCntrl_Value { get; set; }
        public string BM_T3_BrthCntrl_Value { get; set; }
        public string BM_T4_BrthCntrl_Value { get; set; }
        public string BM_BrthCntrl_Limit { get; set; }
        public string BM_T1_BrthCntrlOffVst_Value { get; set; }
        public string BM_T2_BrthCntrlOffVst_Value { get; set; }
        public string BM_T3_BrthCntrlOffVst_Value { get; set; }
        public string BM_T4_BrthCntrlOffVst_Value { get; set; }
        public string BM_BrthCntrlOffVst_Limit { get; set; }
        public string BM_T1_BrthCntrlOffVst_Spe_Value { get; set; }
        public string BM_T2_BrthCntrlOffVst_Spe_Value { get; set; }
        public string BM_T3_BrthCntrlOffVst_Spe_Value { get; set; }
        public string BM_T4_BrthCntrlOffVst_Spe_Value { get; set; }
        public string BM_BrthCntrlOffVst_Spe_Limit { get; set; }
        public string BM_BrePump_AddInfo { get; set; }
        public string BM_PlanSpeciServDescribBrestPumpBenfit { get; set; }
        public string BM_BrstPump_Limit { get; set; }
        public string BM_T1_CardRehab_Value { get; set; }
        public string BM_T2_CardRehab_Value { get; set; }
        public string BM_T3_CardRehab_Value { get; set; }
        public string BM_T4_CardRehab_Value { get; set; }
        public string BM_CardRehab_Limit { get; set; }
        public string BM_T1_ConGlss_Value { get; set; }
        public string BM_T2_ConGlss_Value { get; set; }
        public string BM_T3_ConGlss_Value { get; set; }
        public string BM_T4_ConGlss_Value { get; set; }
        public string BM_ConGlss_Limit { get; set; }
        public string BM_T1_FcPeel_Value { get; set; }
        public string BM_T2_FcPeel_Value { get; set; }
        public string BM_T3_FcPeel_Value { get; set; }
        public string BM_T4_FcPeel_Value { get; set; }
        public string BM_FcPeel_Limit { get; set; }
        public string BM_T1_CheOff_Value { get; set; }
        public string BM_T2_CheOff_Value { get; set; }
        public string BM_T3_CheOff_Value { get; set; }
        public string BM_T4_CheOff_Value { get; set; }
        public string BM_CheOff_Limit { get; set; }
        public string BM_T1_CheOff_Spe_Value { get; set; }
        public string BM_T2_CheOff_Spe_Value { get; set; }
        public string BM_T3_CheOff_Spe_Value { get; set; }
        public string BM_T4_CheOff_Spe_Value { get; set; }
        public string BM_CheOff_Spe_Limit { get; set; }
        public string BM_T1_Chemo_Value { get; set; }
        public string BM_T2_Chemo_Value { get; set; }
        public string BM_T3_Chemo_Value { get; set; }
        public string BM_T4_Chemo_Value { get; set; }
        public string BM_Chemo_Limit { get; set; }
        public string BM_T1_Chiro_Value { get; set; }
        public string BM_T2_Chiro_Value { get; set; }
        public string BM_T3_Chiro_Value { get; set; }
        public string BM_T4_Chiro_Value { get; set; }
        public string BM_Chiro_Limit { get; set; }
        public string BM_T1_Chiro_PCP_Value { get; set; }
        public string BM_T2_Chiro_PCP_Value { get; set; }
        public string BM_T3_Chiro_PCP_Value { get; set; }
        public string BM_T4_Chiro_PCP_Value { get; set; }
        public string BM_Chiro_PCP_Limit { get; set; }
        public string BM_T1_Chiro_Spe_Value { get; set; }
        public string BM_T2_Chiro_Spe_Value { get; set; }
        public string BM_T3_Chiro_Spe_Value { get; set; }
        public string BM_T4_Chiro_Spe_Value { get; set; }
        public string BM_Chiro_Spe_Limit { get; set; }
        public string BM_T1_ChScPra_Value { get; set; }
        public string BM_T2_ChScPra_Value { get; set; }
        public string BM_T3_ChScPra_Value { get; set; }
        public string BM_T4_ChScPra_Value { get; set; }
        public string BM_ChScPra_Limit { get; set; }
        public string BM_T1_CochDvc_Value { get; set; }
        public string BM_T2_CochDvc_Value { get; set; }
        public string BM_T3_CochDvc_Value { get; set; }
        public string BM_T4_CochDvc_Value { get; set; }
        public string BM_CochDvc_Limit { get; set; }
        public string BM_T1_CosmtSur_Value { get; set; }
        public string BM_T2_CosmtSur_Value { get; set; }
        public string BM_T3_CosmtSur_Value { get; set; }
        public string BM_T4_CosmtSur_Value { get; set; }
        public string BM_CosmtSur_Limit { get; set; }
        public string BM_T1_Custdl_Value { get; set; }
        public string BM_T2_Custdl_Value { get; set; }
        public string BM_T3_Custdl_Value { get; set; }
        public string BM_T4_Custdl_Value { get; set; }
        public string BM_Custdl_Limit { get; set; }
        public string BM_T1_DenSerAccOff_Value { get; set; }
        public string BM_T2_DenSerAccOff_Value { get; set; }
        public string BM_T3_DenSerAccOff_Value { get; set; }
        public string BM_T4_DenSerAccOff_Value { get; set; }
        public string BM_DenSerAccOff_Limit { get; set; }
        public string BM_T1_DenSerAccOff_Spe_Value { get; set; }
        public string BM_T2_DenSerAccOff_Spe_Value { get; set; }
        public string BM_T3_DenSerAccOff_Spe_Value { get; set; }
        public string BM_T4_DenSerAccOff_Spe_Value { get; set; }
        public string BM_DenSerAccOff_Spe_Limit { get; set; }
        public string BM_T1_DntlAcdnt_Value { get; set; }
        public string BM_T2_DntlAcdnt_Value { get; set; }
        public string BM_T3_DntlAcdnt_Value { get; set; }
        public string BM_T4_DntlAcdnt_Value { get; set; }
        public string BM_DntlAcdnt_Limit { get; set; }
        public string BM_T1_DenSerNonAccOff_Value { get; set; }
        public string BM_T2_DenSerNonAccOff_Value { get; set; }
        public string BM_T3_DenSerNonAccOff_Value { get; set; }
        public string BM_T4_DenSerNonAccOff_Value { get; set; }
        public string BM_DenSerNonAccOff_Limit { get; set; }
        public string BM_T1_DenSerNonAccOff_Spe_Value { get; set; }
        public string BM_T2_DenSerNonAccOff_Spe_Value { get; set; }
        public string BM_T3_DenSerNonAccOff_Spe_Value { get; set; }
        public string BM_T4_DenSerNonAccOff_Spe_Value { get; set; }
        public string BM_DenSerNonAccOff_Spe_Limit { get; set; }
        public string BM_T1_DntlNonAcdnt_Value { get; set; }
        public string BM_T2_DntlNonAcdnt_Value { get; set; }
        public string BM_T3_DntlNonAcdnt_Value { get; set; }
        public string BM_T4_DntlNonAcdnt_Value { get; set; }
        public string BM_DntlNonAcdnt_Limit { get; set; }
        public string BM_T1_Derma_Value { get; set; }
        public string BM_T2_Derma_Value { get; set; }
        public string BM_T3_Derma_Value { get; set; }
        public string BM_T4_Derma_Value { get; set; }
        public string BM_Derma_Limit { get; set; }
        public string BM_T1_DiabeSupp_Value { get; set; }
        public string BM_T2_DiabeSupp_Value { get; set; }
        public string BM_T3_DiabeSupp_Value { get; set; }
        public string BM_T4_DiabeSupp_Value { get; set; }
        public string BM_DiabeSupp_Limit { get; set; }
        public string BM_T1_DgnLbRdo_value { get; set; }
        public string BM_T2_DgnLbRdo_value { get; set; }
        public string BM_T3_DgnLbRdo_value { get; set; }
        public string BM_T4_DgnLbRdo_value { get; set; }
        public string BM_DgnLbRdo_Limit { get; set; }
        public string BM_T1_DgnLbRdoSmipleDX { get; set; }
        public string BM_T2_DgnLbRdoSmipleDX { get; set; }
        public string BM_T3_DgnLbRdoSmipleDX { get; set; }
        public string BM_T4_DgnLbRdoSmipleDX { get; set; }
        public string BM_T1_DurMedEquOff_Value { get; set; }
        public string BM_T2_DurMedEquOff_Value { get; set; }
        public string BM_T3_DurMedEquOff_Value { get; set; }
        public string BM_T4_DurMedEquOff_Value { get; set; }
        public string BM_DurMedEquOff_Limit { get; set; }
        public string BM_T1_DurMedEquOff_Spe_Value { get; set; }
        public string BM_T2_DurMedEquOff_Spe_Value { get; set; }
        public string BM_T3_DurMedEquOff_Spe_Value { get; set; }
        public string BM_T4_DurMedEquOff_Spe_Value { get; set; }
        public string BM_DurMedEquOff_Spe_Limit { get; set; }
        public string BM_T1_DMediEqp_Value { get; set; }
        public string BM_T2_DMediEqp_Value { get; set; }
        public string BM_T3_DMediEqp_Value { get; set; }
        public string BM_T4_DMediEqp_Value { get; set; }
        public string BM_DMediEqp_Limit { get; set; }
        public string BM_T1_EduSerOff_Value { get; set; }
        public string BM_T2_EduSerOff_Value { get; set; }
        public string BM_T3_EduSerOff_Value { get; set; }
        public string BM_T4_EduSerOff_Value { get; set; }
        public string BM_EduSerOff_Limit { get; set; }
        public string BM_T1_EduSerOff_Spe_Value { get; set; }
        public string BM_T2_EduSerOff_Spe_Value { get; set; }
        public string BM_T3_EduSerOff_Spe_Value { get; set; }
        public string BM_T4_EduSerOff_Spe_Value { get; set; }
        public string BM_EduSerOff_Spe_Limit { get; set; }
        public string BM_T1_EduSrv_Value { get; set; }
        public string BM_T2_EduSrv_Value { get; set; }
        public string BM_T3_EduSrv_Value { get; set; }
        public string BM_T4_EduSrv_Value { get; set; }
        public string BM_EduSrv_Limit { get; set; }
        public string BM_T1_EmeRooFacFee_Value { get; set; }
        public string BM_T2_EmeRooFacFee_Value { get; set; }
        public string BM_T3_EmeRooFacFee_Value { get; set; }
        public string BM_T4_EmeRooFacFee_Value { get; set; }
        public string BM_EmeRooFacFee_Limit { get; set; }
        public string BM_T1_EmrgRm_Value { get; set; }
        public string BM_T1_EmrgRm_Value2 { get; set; }
        public string BM_T1_EmrgRm_Value3 { get; set; }
        public string BM_T2_EmrgRm_Value { get; set; }
        public string BM_T2_EmrgRm_Value2 { get; set; }
        public string BM_T2_EmrgRm_Value3 { get; set; }
        public string BM_T3_EmrgRm_Value { get; set; }
        public string BM_T3_EmrgRm_Value2 { get; set; }
        public string BM_T3_EmrgRm_Value3 { get; set; }
        public string BM_T4_EmrgRm_Value { get; set; }
        public string BM_T4_EmrgRm_Value2 { get; set; }
        public string BM_T4_EmrgRm_Value3 { get; set; }
        public string BM_EmrgRm_Limit { get; set; }
        public string BM_T1_ExrEqup_Value { get; set; }
        public string BM_T2_ExrEqup_Value { get; set; }
        public string BM_T3_ExrEqup_Value { get; set; }
        public string BM_T4_ExrEqup_Value { get; set; }
        public string BM_ExrEqup_Limit { get; set; }
        public string BM_T1_ExprDrug_Value { get; set; }
        public string BM_T2_ExprDrug_Value { get; set; }
        public string BM_T3_ExprDrug_Value { get; set; }
        public string BM_T4_ExprDrug_Value { get; set; }
        public string BM_ExprDrug_Limit { get; set; }
        public string BM_T1_ExprProc_Value { get; set; }
        public string BM_T2_ExprProc_Value { get; set; }
        public string BM_T3_ExprProc_Value { get; set; }
        public string BM_T4_ExprProc_Value { get; set; }
        public string BM_ExprProc_Limit { get; set; }
        public string BM_T1_FMCoun_Value { get; set; }
        public string BM_T2_FMCoun_Value { get; set; }
        public string BM_T3_FMCoun_Value { get; set; }
        public string BM_T4_FMCoun_Value { get; set; }
        public string BM_FMCoun_Limit { get; set; }
        public string BM_T1_GenDys_PCP_Value { get; set; }
        public string BM_T2_GenDys_PCP_Value { get; set; }
        public string BM_T3_GenDys_PCP_Value { get; set; }
        public string BM_T4_GenDys_PCP_Value { get; set; }
        public string BM_T1_GenDys_Spe_Value { get; set; }
        public string BM_T2_GenDys_Spe_Value { get; set; }
        public string BM_T3_GenDys_Spe_Value { get; set; }
        public string BM_T4_GenDys_Spe_Value { get; set; }
        public string BM_T1_GenDys_Value { get; set; }
        public string BM_T2_GenDys_Value { get; set; }
        public string BM_T3_GenDys_Value { get; set; }
        public string BM_T4_GenDys_Value { get; set; }
        public string BM_GenDys_Limit { get; set; }
        public string BM_T1_GenTest_Value { get; set; }
        public string BM_T2_GenTest_Value { get; set; }
        public string BM_T3_GenTest_Value { get; set; }
        public string BM_T4_GenTest_Value { get; set; }
        public string BM_GenTest_Limit { get; set; }
        public string BM_T1_GrpThrp_Value { get; set; }
        public string BM_T2_GrpThrp_Value { get; set; }
        public string BM_T3_GrpThrp_Value { get; set; }
        public string BM_T4_GrpThrp_Value { get; set; }
        public string BM_GrpThrp_Limit { get; set; }
        public string BM_T1_HemOff_Value { get; set; }
        public string BM_T2_HemOff_Value { get; set; }
        public string BM_T3_HemOff_Value { get; set; }
        public string BM_T4_HemOff_Value { get; set; }
        public string BM_HemOff_Limit { get; set; }
        public string BM_T1_HemOff_Spe_Value { get; set; }
        public string BM_T2_HemOff_Spe_Value { get; set; }
        public string BM_T3_HemOff_Spe_Value { get; set; }
        public string BM_T4_HemOff_Spe_Value { get; set; }
        public string BM_HemOff_Spe_Limit { get; set; }
        public string BM_T1_Hemo_value { get; set; }
        public string BM_T2_Hemo_value { get; set; }
        public string BM_T3_Hemo_value { get; set; }
        public string BM_T4_Hemo_value { get; set; }
        public string BM_Hemo_Limit { get; set; }
        public string BM_T1_HmHlCare_value { get; set; }
        public string BM_T2_HmHlCare_value { get; set; }
        public string BM_T3_HmHlCare_value { get; set; }
        public string BM_T4_HmHlCare_value { get; set; }
        public string BM_HmHlCare_Limit { get; set; }
        public string BM_T1_HosSrv_value { get; set; }
        public string BM_T2_HosSrv_value { get; set; }
        public string BM_T3_HosSrv_value { get; set; }
        public string BM_T4_HosSrv_value { get; set; }
        public string BM_HosSrv_Limit { get; set; }
        public string BM_T1_HosInPtn_value { get; set; }
        public string BM_T2_HosInPtn_value { get; set; }
        public string BM_T3_HosInPtn_value { get; set; }
        public string BM_T4_HosInPtn_value { get; set; }
        public string BM_HosInPtn_Limit { get; set; }
        public string BM_T1_HosOutPtnSur_value { get; set; }
        public string BM_T2_HosOutPtnSur_value { get; set; }
        public string BM_T3_HosOutPtnSur_value { get; set; }
        public string BM_T4_HosOutPtnSur_value { get; set; }
        public string BM_HosOutPtnSur_Limit { get; set; }
        public string BM_T1_HosOutPtnRtn_value { get; set; }
        public string BM_T2_HosOutPtnRtn_value { get; set; }
        public string BM_T3_HosOutPtnRtn_value { get; set; }
        public string BM_T4_HosOutPtnRtn_value { get; set; }
        public string BM_HosOutPtnRtn_Limit { get; set; }
        public string BM_T1_Hypno_Value { get; set; }
        public string BM_T2_Hypno_Value { get; set; }
        public string BM_T3_Hypno_Value { get; set; }
        public string BM_T4_Hypno_Value { get; set; }
        public string BM_Hypno_Limit { get; set; }
        public string BM_T1_InfDiaOff_Value { get; set; }
        public string BM_T2_InfDiaOff_Value { get; set; }
        public string BM_T3_InfDiaOff_Value { get; set; }
        public string BM_T4_InfDiaOff_Value { get; set; }
        public string BM_InfDiaOff_Limit { get; set; }
        public string BM_T1_InfDiaOff_Spe_Value { get; set; }
        public string BM_T2_InfDiaOff_Spe_Value { get; set; }
        public string BM_T3_InfDiaOff_Spe_Value { get; set; }
        public string BM_T4_InfDiaOff_Spe_Value { get; set; }
        public string BM_InfDiaOff_Spe_Limit { get; set; }
        public string BM_T1_InfTreOff_Value { get; set; }
        public string BM_T2_InfTreOff_Value { get; set; }
        public string BM_T3_InfTreOff_Value { get; set; }
        public string BM_T4_InfTreOff_Value { get; set; }
        public string BM_InfTreOff_Limit { get; set; }
        public string BM_T1_InfTreOff_Spe_Value { get; set; }
        public string BM_T2_InfTreOff_Spe_Value { get; set; }
        public string BM_T3_InfTreOff_Spe_Value { get; set; }
        public string BM_T4_InfTreOff_Spe_Value { get; set; }
        public string BM_InfTreOff_Spe_Limit { get; set; }
        public string BM_T1_InfSrv_Value { get; set; }
        public string BM_T2_InfSrv_Value { get; set; }
        public string BM_T3_InfSrv_Value { get; set; }
        public string BM_T4_InfSrv_Value { get; set; }
        public string BM_InfSrv_Limit { get; set; }
        public string BM_T1_InvDrgPrc_Value { get; set; }
        public string BM_T2_InvDrgPrc_Value { get; set; }
        public string BM_T3_InvDrgPrc_Value { get; set; }
        public string BM_T4_InvDrgPrc_Value { get; set; }
        public string BM_InvDrgPrc_Limit { get; set; }
        public string BM_T1_LcmMgmt_Value { get; set; }
        public string BM_T2_LcmMgmt_Value { get; set; }
        public string BM_T3_LcmMgmt_Value { get; set; }
        public string BM_T4_LcmMgmt_Value { get; set; }
        public string BM_LcmMgmt_Limit { get; set; }
        public string BM_T1_MasTheOff_Value { get; set; }
        public string BM_T2_MasTheOff_Value { get; set; }
        public string BM_T3_MasTheOff_Value { get; set; }
        public string BM_T4_MasTheOff_Value { get; set; }
        public string BM_MasTheOff_Limit { get; set; }
        public string BM_T1_MasTheOff_Spe_Value { get; set; }
        public string BM_T2_MasTheOff_Spe_Value { get; set; }
        public string BM_T3_MasTheOff_Spe_Value { get; set; }
        public string BM_T4_MasTheOff_Spe_Value { get; set; }
        public string BM_MasTheOff_Spe_Limit { get; set; }
        public string BM_T1_Msg_Value { get; set; }
        public string BM_T2_Msg_Value { get; set; }
        public string BM_T3_Msg_Value { get; set; }
        public string BM_T4_Msg_Value { get; set; }
        public string BM_Msg_Limit { get; set; }
        public string BM_T1_MatrSrv_Value { get; set; }
        public string BM_T2_MatrSrv_Value { get; set; }
        public string BM_T3_MatrSrv_Value { get; set; }
        public string BM_T4_MatrSrv_Value { get; set; }
        public string BM_MatrSrv_Limit { get; set; }
        public string BM_T1_MDSupp_Value { get; set; }
        public string BM_T2_MDSupp_Value { get; set; }
        public string BM_T3_MDSupp_Value { get; set; }
        public string BM_T4_MDSupp_Value { get; set; }
        public string BM_MDSupp_Limit { get; set; }
        public string BM_T1_MemReq_Value { get; set; }
        public string BM_T2_MemReq_Value { get; set; }
        public string BM_T3_MemReq_Value { get; set; }
        public string BM_T4_MemReq_Value { get; set; }
        public string BM_MemReq_Limit { get; set; }
        public string BM_T1_MntlIn_Value { get; set; }
        public string BM_T2_MntlIn_Value { get; set; }
        public string BM_T3_MntlIn_Value { get; set; }
        public string BM_T4_MntlIn_Value { get; set; }
        public string BM_MntlIn_Limit { get; set; }
        public string BM_T1_MntlOut_value { get; set; }
        public string BM_T2_MntlOut_value { get; set; }
        public string BM_T3_MntlOut_value { get; set; }
        public string BM_T4_MntlOut_value { get; set; }
        public string BM_MntlOut_Limit { get; set; }
        public string BM_T1_MILIEUSit_Value { get; set; }
        public string BM_T2_MILIEUSit_Value { get; set; }
        public string BM_T3_MILIEUSit_Value { get; set; }
        public string BM_T4_MILIEUSit_Value { get; set; }
        public string BM_MILIEUSit_Limit { get; set; }
        public string BM_T1_MorObeOff_Value { get; set; }
        public string BM_T2_MorObeOff_Value { get; set; }
        public string BM_T3_MorObeOff_Value { get; set; }
        public string BM_T4_MorObeOff_Value { get; set; }
        public string BM_MorObeOff_Limit { get; set; }
        public string BM_T1_MorObeOff_Spe_Value { get; set; }
        public string BM_T2_MorObeOff_Spe_Value { get; set; }
        public string BM_T3_MorObeOff_Spe_Value { get; set; }
        public string BM_T4_MorObeOff_Spe_Value { get; set; }
        public string BM_MorObeOff_Spe_Limit { get; set; }
        public string BM_T1_ObWtContr_Value { get; set; }
        public string BM_T2_ObWtContr_Value { get; set; }
        public string BM_T3_ObWtContr_Value { get; set; }
        public string BM_T4_ObWtContr_Value { get; set; }
        public string BM_ObWtContr_Limit { get; set; }
        public string BM_T1_MorObeSurOff_Value { get; set; }
        public string BM_T2_MorObeSurOff_Value { get; set; }
        public string BM_T3_MorObeSurOff_Value { get; set; }
        public string BM_T4_MorObeSurOff_Value { get; set; }
        public string BM_MorObeSurOff_Limit { get; set; }
        public string BM_T1_MorObeSurOff_Spe_Value { get; set; }
        public string BM_T2_MorObeSurOff_Spe_Value { get; set; }
        public string BM_T3_MorObeSurOff_Spe_Value { get; set; }
        public string BM_T4_MorObeSurOff_Spe_Value { get; set; }
        public string BM_MorObeSurOff_Spe_Limit { get; set; }
        public string BM_T1_ObSurg_Value { get; set; }
        public string BM_T2_ObSurg_Value { get; set; }
        public string BM_T3_ObSurg_Value { get; set; }
        public string BM_T4_ObSurg_Value { get; set; }
        public string BM_ObSurg_Limit { get; set; }
        public string BM_T1_HrExTst_Value { get; set; }
        public string BM_T2_HrExTst_Value { get; set; }
        public string BM_T3_HrExTst_Value { get; set; }
        public string BM_T4_HrExTst_Value { get; set; }
        public string BM_HrExTst_Limit { get; set; }
        public string BM_T1_NonRouHeaOff_Value { get; set; }
        public string BM_T2_NonRouHeaOff_Value { get; set; }
        public string BM_T3_NonRouHeaOff_Value { get; set; }
        public string BM_T4_NonRouHeaOff_Value { get; set; }
        public string BM_NonRouHeaOff_Limit { get; set; }
        public string BM_T1_NonRouHeaOff_Spe_Value { get; set; }
        public string BM_T2_NonRouHeaOff_Spe_Value { get; set; }
        public string BM_T3_NonRouHeaOff_Spe_Value { get; set; }
        public string BM_T4_NonRouHeaOff_Spe_Value { get; set; }
        public string BM_NonRouHeaOff_Spe_Limit { get; set; }
        public string BM_T1_NurPract_Value { get; set; }
        public string BM_T2_NurPract_Value { get; set; }
        public string BM_T3_NurPract_Value { get; set; }
        public string BM_T4_NurPract_Value { get; set; }
        public string BM_NurPract_Limit { get; set; }
        public string BM_T1_NutCoun_Value { get; set; }
        public string BM_T2_NutCoun_Value { get; set; }
        public string BM_T3_NutCoun_Value { get; set; }
        public string BM_T4_NutCoun_Value { get; set; }
        public string BM_NutCoun_Limit { get; set; }
        public string BM_T1_NutSupp_Value { get; set; }
        public string BM_T2_NutSupp_Value { get; set; }
        public string BM_T3_NutSupp_Value { get; set; }
        public string BM_T4_NutSupp_Value { get; set; }
        public string BM_NutSupp_Limit { get; set; }
        public string BM_T1_OrtOff_Value { get; set; }
        public string BM_T2_OrtOff_Value { get; set; }
        public string BM_T3_OrtOff_Value { get; set; }
        public string BM_T4_OrtOff_Value { get; set; }
        public string BM_OrtOff_Limit { get; set; }
        public string BM_T1_OrtOff_Spe_Value { get; set; }
        public string BM_T2_OrtOff_Spe_Value { get; set; }
        public string BM_T3_OrtOff_Spe_Value { get; set; }
        public string BM_T4_OrtOff_Spe_Value { get; set; }
        public string BM_OrtOff_Spe_Limit { get; set; }
        public string BM_T1_OrthBNKW_Value { get; set; }
        public string BM_T2_OrthBNKW_Value { get; set; }
        public string BM_T3_OrthBNKW_Value { get; set; }
        public string BM_T4_OrthBNKW_Value { get; set; }
        public string BM_OrthBNKW_Limit { get; set; }
        public string BM_T1_OrthopOff_Value { get; set; }
        public string BM_T2_OrthopOff_Value { get; set; }
        public string BM_T3_OrthopOff_Value { get; set; }
        public string BM_T4_OrthopOff_Value { get; set; }
        public string BM_OrthopOff_Limit { get; set; }
        public string BM_T1_OrthopOff_Spe_Value { get; set; }
        public string BM_T2_OrthopOff_Spe_Value { get; set; }
        public string BM_T3_OrthopOff_Spe_Value { get; set; }
        public string BM_T4_OrthopOff_Spe_Value { get; set; }
        public string BM_OrthopOff_Spe_Limit { get; set; }
        public string BM_T1_OrthSho_Value { get; set; }
        public string BM_T2_OrthSho_Value { get; set; }
        public string BM_T3_OrthSho_Value { get; set; }
        public string BM_T4_OrthSho_Value { get; set; }
        public string BM_OrthSho_Limit { get; set; }
        public string BM_T1_OutOccThrp_Value { get; set; }
        public string BM_T2_OutOccThrp_Value { get; set; }
        public string BM_T3_OutOccThrp_Value { get; set; }
        public string BM_T4_OutOccThrp_Value { get; set; }
        public string BM_OutOccThrp_Limit { get; set; }
        public string BM_T1_OutPhyThrp_Value { get; set; }
        public string BM_T2_OutPhyThrp_Value { get; set; }
        public string BM_T3_OutPhyThrp_Value { get; set; }
        public string BM_T4_OutPhyThrp_Value { get; set; }
        public string BM_OutPhyThrp_Limit { get; set; }
        public string BM_T1_OutSpchTh_Value { get; set; }
        public string BM_T2_OutSpchTh_Value { get; set; }
        public string BM_T3_OutSpchTh_Value { get; set; }
        public string BM_T4_OutSpchTh_Value { get; set; }
        public string BM_OutSpchTh_Limit { get; set; }
        public string BM_T1_PainMngmnt_Value { get; set; }
        public string BM_T2_PainMngmnt_Value { get; set; }
        public string BM_T3_PainMngmnt_Value { get; set; }
        public string BM_T4_PainMngmnt_Value { get; set; }
        public string BM_PainMngmnt_Limit { get; set; }
        public string BM_T1_PrsnCon_Value { get; set; }
        public string BM_T2_PrsnCon_Value { get; set; }
        public string BM_T3_PrsnCon_Value { get; set; }
        public string BM_T4_PrsnCon_Value { get; set; }
        public string BM_PrsnCon_Limit { get; set; }
        public string BM_T1_PhySNFCon_Value { get; set; }
        public string BM_T2_PhySNFCon_Value { get; set; }
        public string BM_T3_PhySNFCon_Value { get; set; }
        public string BM_T4_PhySNFCon_Value { get; set; }
        public string BM_PhySNFCon_Limit { get; set; }
        public string BM_T1_Podoff_Value { get; set; }
        public string BM_T2_Podoff_Value { get; set; }
        public string BM_T3_Podoff_Value { get; set; }
        public string BM_T4_Podoff_Value { get; set; }
        public string BM_Podoff_Limit { get; set; }
        public string BM_T1_Podoff_Spe_Value { get; set; }
        public string BM_T2_Podoff_Spe_Value { get; set; }
        public string BM_T3_Podoff_Spe_Value { get; set; }
        public string BM_T4_Podoff_Spe_Value { get; set; }
        public string BM_Podoff_Spe_Limit { get; set; }
        public string BM_T1_PodiSrv_Value { get; set; }
        public string BM_T2_PodiSrv_Value { get; set; }
        public string BM_T3_PodiSrv_Value { get; set; }
        public string BM_T4_PodiSrv_Value { get; set; }
        public string BM_PodiSrv_Limit { get; set; }
        public string BM_T1_PostSurgicalBars_Value { get; set; }
        public string BM_T2_PostSurgicalBars_Value { get; set; }
        public string BM_T3_PostSurgicalBars_Value { get; set; }
        public string BM_T4_PostSurgicalBars_Value { get; set; }
        public string BM_PostSurgicalBars_Limit { get; set; }
        public string BM_T1_PreAddTest_Value { get; set; }
        public string BM_T2_PreAddTest_Value { get; set; }
        public string BM_T3_PreAddTest_Value { get; set; }
        public string BM_T4_PreAddTest_Value { get; set; }
        public string BM_PreAddTest_Limit { get; set; }
        public string BM_PCPoNonRtnC_T1_Value { get; set; }
        public string BM_PCPoNonRtnC_T2_Value { get; set; }
        public string BM_PCPoNonRtnC_T3_Value { get; set; }
        public string BM_PCPoNonRtnC_T4_Value { get; set; }
        public string BM_PCPoNonRtnC_Limit { get; set; }
        public string BM_T1_PvtDNurs_Value { get; set; }
        public string BM_T2_PvtDNurs_Value { get; set; }
        public string BM_T3_PvtDNurs_Value { get; set; }
        public string BM_T4_PvtDNurs_Value { get; set; }
        public string BM_PvtDNurs_Limit { get; set; }
        public string BM_T1_ProOff_Value { get; set; }
        public string BM_T2_ProOff_Value { get; set; }
        public string BM_T3_ProOff_Value { get; set; }
        public string BM_T4_ProOff_Value { get; set; }
        public string BM_ProOff_Limit { get; set; }
        public string BM_T1_ProOff_Spe_Value { get; set; }
        public string BM_T2_ProOff_Spe_Value { get; set; }
        public string BM_T3_ProOff_Spe_Value { get; set; }
        public string BM_T4_ProOff_Spe_Value { get; set; }
        public string BM_ProOff_Spe_Limit { get; set; }
        public string BM_T1_ProsthApp_Value { get; set; }
        public string BM_T2_ProsthApp_Value { get; set; }
        public string BM_T3_ProsthApp_Value { get; set; }
        public string BM_T4_ProsthApp_Value { get; set; }
        public string BM_ProsthApp_Limit { get; set; }
        public string BM_T1_PulRehOff_Value { get; set; }
        public string BM_T2_PulRehOff_Value { get; set; }
        public string BM_T3_PulRehOff_Value { get; set; }
        public string BM_T4_PulRehOff_Value { get; set; }
        public string BM_PulRehOff_Limit { get; set; }
        public string BM_T1_PulRehOff_Spe_Value { get; set; }
        public string BM_T2_PulRehOff_Spe_Value { get; set; }
        public string BM_T3_PulRehOff_Spe_Value { get; set; }
        public string BM_T4_PulRehOff_Spe_Value { get; set; }
        public string BM_PulRehOff_Spe_Limit { get; set; }
        public string BM_T1_PulReh_Value { get; set; }
        public string BM_T2_PulReh_Value { get; set; }
        public string BM_T3_PulReh_Value { get; set; }
        public string BM_T4_PulReh_Value { get; set; }
        public string BM_PulReh_Limit { get; set; }
        public string BM_T1_RadThr_Value { get; set; }
        public string BM_T2_RadThr_Value { get; set; }
        public string BM_T3_RadThr_Value { get; set; }
        public string BM_T4_RadThr_Value { get; set; }
        public string BM_RadThr_Limit { get; set; }
        public string BM_T1_RetCen_Value { get; set; }
        public string BM_T2_RetCen_Value { get; set; }
        public string BM_T3_RetCen_Value { get; set; }
        public string BM_T4_RetCen_Value { get; set; }
        public string BM_RetCen_Limit { get; set; }
        public string BM_T1_RoboSurg_Value { get; set; }
        public string BM_T2_RoboSurg_Value { get; set; }
        public string BM_T3_RoboSurg_Value { get; set; }
        public string BM_T4_RoboSurg_Value { get; set; }
        public string BM_RoboSurg_Limit { get; set; }
        public string BM_T1_RtnHM_Value { get; set; }
        public string BM_T2_RtnHM_Value { get; set; }
        public string BM_T3_RtnHM_Value { get; set; }
        public string BM_T4_RtnHM_Value { get; set; }
        public string BM_PlanSpecSerQZPlanUseUSPrevenServTaskForcABGuiCovRoutCove { get; set; }
        public string BM_AdditionalPreventiveServicesUS { get; set; }
        public string BM_Add_Cov_Rout_Adut_Svr { get; set; }
        public string BM_Add_Cov_Ped_Svr { get; set; }
        public string BM_RoutinePhysicalAnnually { get; set; }
        public string BM_RoutinePhysicalPerPediatricRecommendationsChid { get; set; }
        public string BM_RoutineOBGYNExam { get; set; }
        public string BM_RoutineMammogram { get; set; }
        public string BM_RoutinePapSmear { get; set; }
        public string BM_RoutineLabPathology { get; set; }
        public string BM_RoutineBoneDensity { get; set; }
        public string BM_FluShot { get; set; }
        public string BM_FluMist { get; set; }
        public string BM_RoutineImmunizations { get; set; }
        public string BM_HPVTesting { get; set; }
        public string BM_RoutineColonoscopy { get; set; }
        public string BM_RoutineSigmoidoscopy { get; set; }
        public string BM_RoutineHearingExam { get; set; }
        public string BM_RoutineVisionExam { get; set; }
        public string BM_RtnHM_Limit { get; set; }
        public string BM_RtnHM_Limit2 { get; set; }
        public string BM_T1_RntNusry_Value { get; set; }
        public string BM_T2_RntNusry_Value { get; set; }
        public string BM_T3_RntNusry_Value { get; set; }
        public string BM_T4_RntNusry_Value { get; set; }
        public string BM_RntNusry_Limit { get; set; }
        public string BM_T1_SecSurOff_Value { get; set; }
        public string BM_T2_SecSurOff_Value { get; set; }
        public string BM_T3_SecSurOff_Value { get; set; }
        public string BM_T4_SecSurOff_Value { get; set; }
        public string BM_SecSurOff_Limit { get; set; }
        public string BM_T1_SecSurOff_Spe_Value { get; set; }
        public string BM_T2_SecSurOff_Spe_Value { get; set; }
        public string BM_T3_SecSurOff_Spe_Value { get; set; }
        public string BM_T4_SecSurOff_Spe_Value { get; set; }
        public string BM_SecSurOff_Spe_Limit { get; set; }
        public string BM_T1_SelfInfInjury_Value { get; set; }
        public string BM_T2_SelfInfInjury_Value { get; set; }
        public string BM_T3_SelfInfInjury_Value { get; set; }
        public string BM_T4_SelfInfInjury_Value { get; set; }
        public string BM_SelfInIn_Limit { get; set; }
        public string BM_T1_SexDFunc_Value { get; set; }
        public string BM_T2_SexDFunc_Value { get; set; }
        public string BM_T3_SexDFunc_Value { get; set; }
        public string BM_T4_SexDFunc_Value { get; set; }
        public string BM_SexDFunc_Limit { get; set; }
        public string BM_T1_SexTransfrm_Value { get; set; }
        public string BM_T2_SexTransfrm_Value { get; set; }
        public string BM_T3_SexTransfrm_Value { get; set; }
        public string BM_T4_SexTransfrm_Value { get; set; }
        public string BM_SexTransfrm_Limit { get; set; }
        public string BM_T1_SkilNursFac_PCP { get; set; }
        public string BM_T2_SkilNursFac_PCP { get; set; }
        public string BM_T3_SkilNursFac_PCP { get; set; }
        public string BM_T4_SkilNursFac_PCP { get; set; }
        public string BM_SkilNursFac_Limit { get; set; }
        public string BM_T1_SleDisOff_Value { get; set; }
        public string BM_T2_SleDisOff_Value { get; set; }
        public string BM_T3_SleDisOff_Value { get; set; }
        public string BM_T4_SleDisOff_Value { get; set; }
        public string BM_SleDisOff_Limit { get; set; }
        public string BM_T1_SleDisOff_Spe_Value { get; set; }
        public string BM_T2_SleDisOff_Spe_Value { get; set; }
        public string BM_T3_SleDisOff_Spe_Value { get; set; }
        public string BM_T4_SleDisOff_Spe_Value { get; set; }
        public string BM_SleDisOff_Spe_Limit { get; set; }
        public string BM_T1_SleDisStu_Value { get; set; }
        public string BM_T2_SleDisStu_Value { get; set; }
        public string BM_T3_SleDisStu_Value { get; set; }
        public string BM_T4_SleDisStu_Value { get; set; }
        public string BM_SleDisStu_Limit { get; set; }
        public string BM_T1_SleDisStu_Spe_Value { get; set; }
        public string BM_T2_SleDisStu_Spe_Value { get; set; }
        public string BM_T3_SleDisStu_Spe_Value { get; set; }
        public string BM_T4_SleDisStu_Spe_Value { get; set; }
        public string BM_SleDisStu_Spe_Limit { get; set; }
        public string BM_T1_SleDisOrd_Value { get; set; }
        public string BM_T2_SleDisOrd_Value { get; set; }
        public string BM_T3_SleDisOrd_Value { get; set; }
        public string BM_T4_SleDisOrd_Value { get; set; }
        public string BM_SleDisOrd_Limit { get; set; }
        public string BM_T1_SmoCesOff_Value { get; set; }
        public string BM_T2_SmoCesOff_Value { get; set; }
        public string BM_T3_SmoCesOff_Value { get; set; }
        public string BM_T4_SmoCesOff_Value { get; set; }
        public string BM_SmoCesOff_Limit { get; set; }
        public string BM_T1_SmoCesOff_Spe_Value { get; set; }
        public string BM_T2_SmoCesOff_Spe_Value { get; set; }
        public string BM_T3_SmoCesOff_Spe_Value { get; set; }
        public string BM_T4_SmoCesOff_Spe_Value { get; set; }
        public string BM_SmoCesOff_Spe_Limit { get; set; }
        public string BM_T1_SmkCess_Value { get; set; }
        public string BM_T2_SmkCess_Value { get; set; }
        public string BM_T3_SmkCess_Value { get; set; }
        public string BM_T4_SmkCess_Value { get; set; }
        public string BM_SmkCess_Limit { get; set; }
        public string BM_SplPhyoNRtn_T1_Spe_Value { get; set; }
        public string BM_SplPhyoNRtn_T2_Spe_Value { get; set; }
        public string BM_SplPhyoNRtn_T3_Spe_Value { get; set; }
        public string BM_SplPhyoNRtn_T4_Spe_Value { get; set; }
        public string BM_SplPhyoNRtn_Spe_Limit { get; set; }
        public string BM_T1_SurgnFB_Value { get; set; }
        public string BM_T2_SurgnFB_Value { get; set; }
        public string BM_T3_SurgnFB_Value { get; set; }
        public string BM_T4_SurgnFB_Value { get; set; }
        public string BM_SurgnFB_Limit { get; set; }
        public string BM_T1_SurgStk_Value { get; set; }
        public string BM_T2_SurgStk_Value { get; set; }
        public string BM_T3_SurgStk_Value { get; set; }
        public string BM_T4_SurgStk_Value { get; set; }
        public string BM_SurgStk_Limit { get; set; }
        public string BM_T1_ElecTelePhy_Value { get; set; }
        public string BM_T2_ElecTelePhy_Value { get; set; }
        public string BM_T3_ElecTelePhy_Value { get; set; }
        public string BM_T4_ElecTelePhy_Value { get; set; }
        public string BM_ElecTelePhy_Limit { get; set; }
        public string BM_T1_TMJNonSurPedOff_Value { get; set; }
        public string BM_T2_TMJNonSurPedOff_Value { get; set; }
        public string BM_T3_TMJNonSurPedOff_Value { get; set; }
        public string BM_T4_TMJNonSurPedOff_Value { get; set; }
        public string BM_TMJNonSurPedOff_Limit { get; set; }
        public string BM_T1_TMJNonSurPedOff_Spe_Value { get; set; }
        public string BM_T2_TMJNonSurPedOff_Spe_Value { get; set; }
        public string BM_T3_TMJNonSurPedOff_Spe_Value { get; set; }
        public string BM_T4_TMJNonSurPedOff_Spe_Value { get; set; }
        public string BM_TMJNonSurPedOff_Spe_Limit { get; set; }
        public string BM_T1_TMJSurPedOff_Value { get; set; }
        public string BM_T2_TMJSurPedOff_Value { get; set; }
        public string BM_T3_TMJSurPedOff_Value { get; set; }
        public string BM_T4_TMJSurPedOff_Value { get; set; }
        public string BM_TMJSurPedOff_Limit { get; set; }
        public string BM_T1_TMJSurPedOff_Spe_Value { get; set; }
        public string BM_T2_TMJSurPedOff_Spe_Value { get; set; }
        public string BM_T3_TMJSurPedOff_Spe_Value { get; set; }
        public string BM_T4_TMJSurPedOff_Spe_Value { get; set; }
        public string BM_TMJSurPedOff_Spe_Limit { get; set; }
        public string BM_T1_TMJNonSurAduOff_Value { get; set; }
        public string BM_T2_TMJNonSurAduOff_Value { get; set; }
        public string BM_T3_TMJNonSurAduOff_Value { get; set; }
        public string BM_T4_TMJNonSurAduOff_Value { get; set; }
        public string BM_TMJNonSurAduOff_Limit { get; set; }
        public string BM_T1_TMJNonSurAduOff_Spe_Value { get; set; }
        public string BM_T2_TMJNonSurAduOff_Spe_Value { get; set; }
        public string BM_T3_TMJNonSurAduOff_Spe_Value { get; set; }
        public string BM_T4_TMJNonSurAduOff_Spe_Value { get; set; }
        public string BM_TMJNonSurAduOff_Spe_Limit { get; set; }
        public string BM_T1_TMJSurAduOff_Value { get; set; }
        public string BM_T2_TMJSurAduOff_Value { get; set; }
        public string BM_T3_TMJSurAduOff_Value { get; set; }
        public string BM_T4_TMJSurAduOff_Value { get; set; }
        public string BM_TMJSurAduOff_Limit { get; set; }
        public string BM_T1_TMJSurAduOff_Spe_Value { get; set; }
        public string BM_T2_TMJSurAduOff_Spe_Value { get; set; }
        public string BM_T3_TMJSurAduOff_Spe_Value { get; set; }
        public string BM_T4_TMJSurAduOff_Spe_Value { get; set; }
        public string BM_TMJSurAduOff_Spe_Limit { get; set; }
        public string BM_T1_TMJT_value { get; set; }
        public string BM_T2_TMJT_value { get; set; }
        public string BM_T3_TMJT_value { get; set; }
        public string BM_T4_TMJT_value { get; set; }
        public string BM_TMJT_Limit { get; set; }
        public string BM_T1_TraOff_Value { get; set; }
        public string BM_T2_TraOff_Value { get; set; }
        public string BM_T3_TraOff_Value { get; set; }
        public string BM_T4_TraOff_Value { get; set; }
        public string BM_TraOff_Limit { get; set; }
        public string BM_T1_TraOff_Spe_Value { get; set; }
        public string BM_T2_TraOff_Spe_Value { get; set; }
        public string BM_T3_TraOff_Spe_Value { get; set; }
        public string BM_T4_TraOff_Spe_Value { get; set; }
        public string BM_TraOff_Spe_Limit { get; set; }
        public string BM_T1_Transpl_value { get; set; }
        public string BM_T2_Transpl_value { get; set; }
        public string BM_T3_Transpl_value { get; set; }
        public string BM_T4_Transpl_value { get; set; }
        public string BM_Transpl_Limit { get; set; }
        public string BM_T1_UrgCarFac_Value { get; set; }
        public string BM_T2_UrgCarFac_Value { get; set; }
        public string BM_T3_UrgCarFac_Value { get; set; }
        public string BM_T4_UrgCarFac_Value { get; set; }
        public string BM_UrgCarFac_Limit { get; set; }
        public string BM_T1_UrgCareF_value { get; set; }
        public string BM_T2_UrgCareF_value { get; set; }
        public string BM_T3_UrgCareF_value { get; set; }
        public string BM_T4_UrgCareF_value { get; set; }
        public string BM_UrgCareF_Limit { get; set; }
        public string BM_T1_Vsctomy_Value { get; set; }
        public string BM_T2_Vsctomy_Value { get; set; }
        public string BM_T3_Vsctomy_Value { get; set; }
        public string BM_T4_Vsctomy_Value { get; set; }
        public string BM_Vsctomy_Limit { get; set; }
        public string BM_T1_NonRtnVsn_OV { get; set; }
        public string BM_T2_NonRtnVsn_OV { get; set; }
        public string BM_T3_NonRtnVsn_OV { get; set; }
        public string BM_T4_NonRtnVsn_OV { get; set; }
        public string BM_NonRtnVsn_Limit { get; set; }
        public string BM_T1_NonRtnVsn_OV_Spe { get; set; }
        public string BM_T2_NonRtnVsn_OV_Spe { get; set; }
        public string BM_T3_NonRtnVsn_OV_Spe { get; set; }
        public string BM_T4_NonRtnVsn_OV_Spe { get; set; }
        public string BM_NonRtnVsn_Spe_Limit { get; set; }
        public string BM_T1_NonRtnVsnC_Value { get; set; }
        public string BM_T2_NonRtnVsnC_Value { get; set; }
        public string BM_T3_NonRtnVsnC_Value { get; set; }
        public string BM_T4_NonRtnVsnC_Value { get; set; }
        public string BM_NonRtnVsnC_Limit { get; set; }
        public string BM_T1_NonRtnVsnCGC_Value { get; set; }
        public string BM_T2_NonRtnVsnCGC_Value { get; set; }
        public string BM_T3_NonRtnVsnCGC_Value { get; set; }
        public string BM_T4_NonRtnVsnCGC_Value { get; set; }
        public string BM_NonRtnVsnCGC_Limit { get; set; }
        public string BM_T1_RtnVsn_Value { get; set; }
        public string BM_T2_RtnVsn_Value { get; set; }
        public string BM_T3_RtnVsn_Value { get; set; }
        public string BM_T4_RtnVsn_Value { get; set; }
        public string BM_RtnVsn_Limit { get; set; }
        public string BM_T1_WigOff_Value { get; set; }
        public string BM_T2_WigOff_Value { get; set; }
        public string BM_T3_WigOff_Value { get; set; }
        public string BM_T4_WigOff_Value { get; set; }
        public string BM_WigOff_Limit { get; set; }
        public string BM_T1_WigOff_Spe_Value { get; set; }
        public string BM_T2_WigOff_Spe_Value { get; set; }
        public string BM_T3_WigOff_Spe_Value { get; set; }
        public string BM_T4_WigOff_Spe_Value { get; set; }
        public string BM_WigOff_Spe_Limit { get; set; }
        public string BM_T1_Wings_value { get; set; }
        public string BM_T2_Wings_value { get; set; }
        public string BM_T3_Wings_value { get; set; }
        public string BM_T4_Wings_value { get; set; }
        public string BM_Wings_Limit { get; set; }
        public string BM_CS_MSN_T1 { get; set; }
        public string BM_CS_MSN_T2 { get; set; }
        public string BM_CS_MSN_T3 { get; set; }
        public string BM_CS_MSN_T4 { get; set; }
        public string BM_CL_NotApplicable { get; set; }
        public string BM_CL_T1_Indv { get; set; }
        public string BM_CL_T1_Fmly { get; set; }
        public string BM_CL_T1_EmpPlusOne { get; set; }
        public string BM_CL_T1_EmpPlusChild { get; set; }
        public string BM_CL_T1_EmpPlusOneChild { get; set; }
        public string BM_CL_NotApplicableStaticText { get; set; }
        public string BM_CL_T2_Indv { get; set; }
        public string BM_CL_T2_Fmly { get; set; }
        public string BM_CL_T2_EmpPlusOne { get; set; }
        public string BM_CL_T2_EmpPlusChild { get; set; }
        public string BM_CL_T2_EmpPlusOneChild { get; set; }
        public string BM_CL_T3_Indv { get; set; }
        public string BM_CL_T3_Fmly { get; set; }
        public string BM_CL_T3_EmpPlusOne { get; set; }
        public string BM_CL_T3_EmpPlusChild { get; set; }
        public string BM_CL_T3_EmpPlusOneChild { get; set; }
        public string BM_CL_T4_Indv { get; set; }
        public string BM_CL_T4_Fmly { get; set; }
        public string BM_CL_T4_EmpPlusOne { get; set; }
        public string BM_CL_T4_EmpPlusChild { get; set; }
        public string BM_CL_T4_EmpPlusOneChild { get; set; }
        public string BM_CS_OPSL_T1_StaticText { get; set; }
        public string BM_CS_OPSL_T2_StaticText { get; set; }
        public string BM_CS_OPSL_T3_StaticText { get; set; }
        public string BM_CS_OPSL_T4_StaticText { get; set; }
        public string BM_GI_OutPkt_ExclusionsLimit { get; set; }
        public string BM_T1_NonRoutOffVisit_ChrgOnlyPCP { get; set; }
        public string BM_T2_NonRoutOffVisit_ChrgOnlyPCP { get; set; }
        public string BM_T3_NonRoutOffVisit_ChrgOnlyPCP { get; set; }
        public string BM_T4_NonRoutOffVisit_ChrgOnlyPCP { get; set; }
        public string BM_T1_NonRoutOffVisit_ServWithOVChrgPCP { get; set; }
        public string BM_T2_NonRoutOffVisit_ServWithOVChrgPCP { get; set; }
        public string BM_T3_NonRoutOffVisit_ServWithOVChrgPCP { get; set; }
        public string BM_T4_NonRoutOffVisit_ServWithOVChrgPCP { get; set; }
        public string BM_T1_NonRoutOffVisit_ServWithNoOVChrgPCP { get; set; }
        public string BM_T2_NonRoutOffVisit_ServWithNoOVChrgPCP { get; set; }
        public string BM_T3_NonRoutOffVisit_ServWithNoOVChrgPCP { get; set; }
        public string BM_T4_NonRoutOffVisit_ServWithNoOVChrgPCP { get; set; }
        public string BM_T1_NonRoutOffVisit_ChrgOnlySpec { get; set; }
        public string BM_T2_NonRoutOffVisit_ChrgOnlySpec { get; set; }
        public string BM_T3_NonRoutOffVisit_ChrgOnlySpec { get; set; }
        public string BM_T4_NonRoutOffVisit_ChrgOnlySpec { get; set; }
        public string BM_T1_NonRoutOffVisit_ServWithOVChrgSpec { get; set; }
        public string BM_T2_NonRoutOffVisit_ServWithOVChrgSpec { get; set; }
        public string BM_T3_NonRoutOffVisit_ServWithOVChrgSpec { get; set; }
        public string BM_T4_NonRoutOffVisit_ServWithOVChrgSpec { get; set; }
        public string BM_T1_NonRoutOffVisit_ServWithNoOVChrgSpec { get; set; }
        public string BM_T2_NonRoutOffVisit_ServWithNoOVChrgSpec { get; set; }
        public string BM_T3_NonRoutOffVisit_ServWithNoOVChrgSpec { get; set; }
        public string BM_T4_NonRoutOffVisit_ServWithNoOVChrgSpec { get; set; }
        public string BM_T1_BioFed_Value { get; set; }
        public string BM_T2_BioFed_Value { get; set; }
        public string BM_T3_BioFed_Value { get; set; }
        public string BM_T4_BioFed_Value { get; set; }
        public string BM_BioFed_Limit { get; set; }
        public string BM_T1_BrthCntrlEleStr_Value { get; set; }
        public string BM_T2_BrthCntrlEleStr_Value { get; set; }
        public string BM_T3_BrthCntrlEleStr_Value { get; set; }
        public string BM_T4_BrthCntrlEleStr_Value { get; set; }
        public string BM_BrthCntrlEleStr_Limit { get; set; }
        public string BM_T1_BrthCntrlRevStr_Value { get; set; }
        public string BM_T2_BrthCntrlRevStr_Value { get; set; }
        public string BM_T3_BrthCntrlRevStr_Value { get; set; }
        public string BM_T4_BrthCntrlRevStr_Value { get; set; }
        public string BM_BrthCntrlRevStr_Limit { get; set; }
        public string BM_BrePump_Info3 { get; set; }
        public string BM_T1_BrePump_Value { get; set; }
        public string BM_T2_BrePump_Value { get; set; }
        public string BM_T3_BrePump_Value { get; set; }
        public string BM_T4_BrePump_Value { get; set; }
        public string BM_BrePump_Info1 { get; set; }
        public string BM_BrePump_Info4 { get; set; }
        public string BM_BrePump_Info2 { get; set; }
        public string BM_BrePump_Info { get; set; }
        public string BM_T1_DiagnosticLab_PathologyInOffice { get; set; }
        public string BM_T2_DiagnosticLab_PathologyInOffice { get; set; }
        public string BM_T3_DiagnosticLab_PathologyInOffice { get; set; }
        public string BM_T4_DiagnosticLab_PathologyInOffice { get; set; }
        public string BM_T1_DiagnosticLab_PathologyIndependentLab { get; set; }
        public string BM_T2_DiagnosticLab_PathologyIndependentLab { get; set; }
        public string BM_T3_DiagnosticLab_PathologyIndependentLab { get; set; }
        public string BM_T4_DiagnosticLab_PathologyIndependentLab { get; set; }
        public string BM_T1_DiagnosticLab_PathologyOutpatient { get; set; }
        public string BM_T2_DiagnosticLab_PathologyOutpatient { get; set; }
        public string BM_T3_DiagnosticLab_PathologyOutpatient { get; set; }
        public string BM_T4_DiagnosticLab_PathologyOutpatient { get; set; }
        public string BM_T1_DiagnosticRadiology_HighTechOffice { get; set; }
        public string BM_T2_DiagnosticRadiology_HighTechOffice { get; set; }
        public string BM_T3_DiagnosticRadiology_HighTechOffice { get; set; }
        public string BM_T4_DiagnosticRadiology_HighTechOffice { get; set; }
        public string BM_T1_DiagnosticRadiology_HighTechOutpatient { get; set; }
        public string BM_T2_DiagnosticRadiology_HighTechOutpatient { get; set; }
        public string BM_T3_DiagnosticRadiology_HighTechOutpatient { get; set; }
        public string BM_T4_DiagnosticRadiology_HighTechOutpatient { get; set; }
        public string BM_T1_DiagnosticRadiology_SimpleRxOffice { get; set; }
        public string BM_T2_DiagnosticRadiology_SimpleRxOffice { get; set; }
        public string BM_T3_DiagnosticRadiology_SimpleRxOffice { get; set; }
        public string BM_T4_DiagnosticRadiology_SimpleRxOffice { get; set; }
        public string BM_PlanSpeSerIP_Mammography { get; set; }
        public string BM_T1_DiagnosticRadiology_SimpleRxOutpatient { get; set; }
        public string BM_T2_DiagnosticRadiology_SimpleRxOutpatient { get; set; }
        public string BM_T3_DiagnosticRadiology_SimpleRxOutpatient { get; set; }
        public string BM_T4_DiagnosticRadiology_SimpleRxOutpatient { get; set; }
        public string BM_EmrgTm_Limit { get; set; }
        public string BM_EmrgRmCopayInfo_EmrgRmTreatCopayApply { get; set; }
        public string BM_EmrgRmCopayInfo_EmrgRmTreatCopayWaived { get; set; }
        public string BM_PlanSpeSerAH_GeneticTest { get; set; }
        public string BM_Hemo_HemodialysisIsCovered { get; set; }
        public string BM_Network_Renalogic_Utilize { get; set; }
        public string BM_HmHelth { get; set; }
        public string BM_T1_HmInServ_value { get; set; }
        public string BM_T2_HmInServ_value { get; set; }
        public string BM_T3_HmInServ_value { get; set; }
        public string BM_T4_HmInServ_value { get; set; }
        public string BM_HmInServ_Limit { get; set; }
        public string BM_T1_MntOffV_Value { get; set; }
        public string BM_T2_MntOffV_Value { get; set; }
        public string BM_T3_MntOffV_Value { get; set; }
        public string BM_T4_MntOffV_Value { get; set; }
        public string BM_MntOffV_Limit { get; set; }
        public string BM_T1_MntRes_Value { get; set; }
        public string BM_T2_MntRes_Value { get; set; }
        public string BM_T3_MntRes_Value { get; set; }
        public string BM_T4_MntRes_Value { get; set; }
        public string BM_MntRes_Limit { get; set; }
        public string BM_RntNuBSer { get; set; }
        public string BM_T1_SubAbuse_Value { get; set; }
        public string BM_T2_SubAbuse_Value { get; set; }
        public string BM_T3_SubAbuse_Value { get; set; }
        public string BM_T4_SubAbuse_Value { get; set; }
        public string BM_SubAbuse_Limit { get; set; }
        public string BM_T1_SubAb_Value { get; set; }
        public string BM_T2_SubAb_Value { get; set; }
        public string BM_T3_SubAb_Value { get; set; }
        public string BM_T4_SubAb_Value { get; set; }
        public string BM_SubAb_Limit { get; set; }
        public string BM_T1_SubAbOut_value { get; set; }
        public string BM_T2_SubAbOut_value { get; set; }
        public string BM_T3_SubAbOut_value { get; set; }
        public string BM_T4_SubAbOut_value { get; set; }
        public string BM_SubAbOut_Limit { get; set; }
        public string BM_T1_SubAbRes_value { get; set; }
        public string BM_T2_SubAbRes_value { get; set; }
        public string BM_T3_SubAbRes_value { get; set; }
        public string BM_T4_SubAbRes_value { get; set; }
        public string BM_SubAbRes_Limit { get; set; }

    }

    public class PlanSponsorInfoData
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }

    public class SPDLimits
    {
        public string Limit_Description { get; set; }
        public string Amount { get; set; }
        public string Amount_Type { get; set; }
        public string Frequency { get; set; }
        public string Limit_Type { get; set; }
    }

    public class AgentServiceProcess
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    }

    public class SPDDeductibles
    {
        public string CoverageLevel { get; set; }
        public string Tier1Data { get; set; }
        public string Tier2Data { get; set; }
        public string Tier3Data { get; set; }
        public string Tier4Data { get; set; }
    }

    public class PrescriptionOOPMaximums
    {
        public string CoverageLevel { get; set; }
        public string RxOOPMaximum { get; set; }
    }
}


