using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace tmg.equinox.applicationservices.viewmodels.Report
{
    public class VisionMatrixReportData
    {
        public string VM_BP_SpecialAnnouncements { get; set; }
        public string VM_BP_PlanNews { get; set; }
        public string VN_Hdr_GrpName { get; set; }
        public string VN_Hdr_BCltName { get; set; }
        public string VN_Hdr_CustSrv_Ph { get; set; }
        public string VN_Hdr_TrfNo { get; set; }
        public string VN_Hdr_EffDt { get; set; }
        public string BM_Hdr_Bulletin { get; set; }
        public string VN_BO_Vision1 { get; set; }
        public string VN_BO_Vision2 { get; set; }
        public string VN_BP_CalYr_Frm { get; set; }
        public string VN_BP_CalYr_To { get; set; }
        public string VN_COB_Value1 { get; set; }
        public string VN_COB_Value2 { get; set; }
        public string VN_ChlAg_Thrg { get; set; }
        public string VN_ChlAg_End { get; set; }
        public string VN_DE_COV { get; set; }
        public string VN_DE_NotCOV { get; set; }
        public string VN_ChlAg_Incap1 { get; set; }
        public string VN_ChlAg_Incap2 { get; set; }
        public string VN_Subro_Value1 { get; set; }
        public string VN_Subro_Value2_1 { get; set; }
        public string VN_Subro_Value2_2 { get; set; }
        public string VN_Subro_Value3 { get; set; }
        public string VN_Ntw_NtwInfo_Value { get; set; }
        public string VN_Ntw_NtwInfo_MasterNtw { get; set; }
        public string VN_Ntw_UCR_Value { get; set; }
        public string VN_ClmInfo_EOB { get; set; }
        public string VN_ClmInfo_ClmTmfrm { get; set; }
        public string VN_ClmInfo_ClmpayCycl { get; set; }
        public string VN_AdmSrv_EmpID { get; set; }
        public string VN_TrmnDate_Value { get; set; }

        public string VN_Ded_IsApplicable { get; set; }
        public string VN_T1_Ded_CvrgLvls { get; set; }
        public string VN_T2_Ded_CvrgLvls { get; set; }
        public string VN_T3_Ded_CvrgLvls { get; set; }

        public string VN_Cop_IsApplicable { get; set; }
        public string VN_T1_Copays { get; set; }
        public string VN_T2_Copays { get; set; }
        public string VN_T3_Copays { get; set; }

        public string VN_Coin_IsApplicable { get; set; }
        public string VN_T1_Coins { get; set; }
        public string VN_T2_Coins { get; set; }
        public string VN_T3_Coins { get; set; }

        public string VN_PlanMxms_IsApplicable { get; set; }
        public string VN_OvrLftm_T1 { get; set; }
        public string VN_OvrLftm_T2 { get; set; }
        public string VN_OvrLftm_T3 { get; set; }

        public string VN_OvrAnnl_T1 { get; set; }
        public string VN_OvrAnnl_T2 { get; set; }
        public string VN_OvrAnnl_T3 { get; set; }

        public string VN_RestBen_T1 { get; set; }
        public string VN_RestBen_T2 { get; set; }
        public string VN_RestBen_T3 { get; set; }

        
        public string VN_Anti_Reflective_Coating_T1 { get; set; }
        public string VN_Bifocal_Contacts_T1 { get; set; }
        public string VN_Bifocals_T1 { get; set; }
        public string VN_Colored_Contact_Lens_T1 { get; set; }
        public string VN_Cosmetic_Contacts_T1 { get; set; }
        public string VN_Disposable_Contacts_T1 { get; set; }
        public string VN_Eye_Glass_Care_T1 { get; set; }
        public string VN_Frames_T1 { get; set; }
        public string VN_Hard_Contacts_T1 { get; set; }
        public string VN_Lasik_Surgery_T1 { get; set; }
        public string VN_Lens_Tinting_T1 { get; set; }
        public string VN_Lenticular_Lens_T1 { get; set; }
        public string VN_Mirror_Coating_T1 { get; set; }
        public string VN_Non_Prescription_Lens_T1 { get; set; }
        public string VN_Other_T1 { get; set; }
        public string VN_PRK_Surgery_T1 { get; set; }
        public string VN_Safety_Eyeglass_Frames_T1 { get; set; }
        public string VN_Single_Vision_Lens_T1 { get; set; }
        public string VN_Soft_Contacts_T1 { get; set; }
        public string VN_Sunglass_Frames_T1 { get; set; }
        public string VN_Trifocals_T1 { get; set; }
        public string VN_Radial_Keratotomy_T1 { get; set; }
        public string VN_Vision_Exam_T1 { get; set; }
        public string VN_Refractive_Eye_Surgery_T1 { get; set; }

        public string VN_Anti_Reflective_Coating_T2 { get; set; }
        public string VN_Bifocal_Contacts_T2 { get; set; }
        public string VN_Bifocals_T2 { get; set; }
        public string VN_Colored_Contact_Lens_T2 { get; set; }
        public string VN_Cosmetic_Contacts_T2 { get; set; }
        public string VN_Disposable_Contacts_T2 { get; set; }
        public string VN_Eye_Glass_Care_T2 { get; set; }
        public string VN_Frames_T2 { get; set; }
        public string VN_Hard_Contacts_T2 { get; set; }
        public string VN_Lasik_Surgery_T2 { get; set; }
        public string VN_Lens_Tinting_T2 { get; set; }
        public string VN_Lenticular_Lens_T2 { get; set; }
        public string VN_Mirror_Coating_T2 { get; set; }
        public string VN_Non_Prescription_Lens_T2 { get; set; }
        public string VN_Other_T2 { get; set; }
        public string VN_PRK_Surgery_T2 { get; set; }
        public string VN_Safety_Eyeglass_Frames_T2 { get; set; }
        public string VN_Single_Vision_Lens_T2 { get; set; }
        public string VN_Soft_Contacts_T2 { get; set; }
        public string VN_Sunglass_Frames_T2 { get; set; }
        public string VN_Trifocals_T2 { get; set; }
        public string VN_Radial_Keratotomy_T2 { get; set; }
        public string VN_Vision_Exam_T2 { get; set; }
        public string VN_Refractive_Eye_Surgery_T2 { get; set; }

        public string VN_Anti_Reflective_Coating_T3 { get; set; }
        public string VN_Bifocal_Contacts_T3 { get; set; }
        public string VN_Bifocals_T3 { get; set; }
        public string VN_Colored_Contact_Lens_T3 { get; set; }
        public string VN_Cosmetic_Contacts_T3 { get; set; }
        public string VN_Disposable_Contacts_T3 { get; set; }
        public string VN_Eye_Glass_Care_T3 { get; set; }
        public string VN_Frames_T3 { get; set; }
        public string VN_Hard_Contacts_T3 { get; set; }
        public string VN_Lasik_Surgery_T3 { get; set; }
        public string VN_Lens_Tinting_T3 { get; set; }
        public string VN_Lenticular_Lens_T3 { get; set; }
        public string VN_Mirror_Coating_T3 { get; set; }
        public string VN_Non_Prescription_Lens_T3 { get; set; }
        public string VN_Other_T3 { get; set; }
        public string VN_PRK_Surgery_T3 { get; set; }
        public string VN_Safety_Eyeglass_Frames_T3 { get; set; }
        public string VN_Single_Vision_Lens_T3 { get; set; }
        public string VN_Soft_Contacts_T3 { get; set; }
        public string VN_Sunglass_Frames_T3 { get; set; }
        public string VN_Trifocals_T3 { get; set; }
        public string VN_Radial_Keratotomy_T3 { get; set; }
        public string VN_Vision_Exam_T3 { get; set; }
        public string VN_Refractive_Eye_Surgery_T3 { get; set; }

        public string VN_Anti_Reflective_Coating_Limits { get; set; }
        public string VN_Bifocal_Contacts_Limits { get; set; }
        public string VN_Bifocals_Limits { get; set; }
        public string VN_Colored_Contact_Lens_Limits { get; set; }
        public string VN_Cosmetic_Contacts_Limits { get; set; }
        public string VN_Disposable_Contacts_Limits { get; set; }
        public string VN_Eye_Glass_Care_Limits { get; set; }
        public string VN_Frames_Limits { get; set; }
        public string VN_Hard_Contacts_Limits { get; set; }
        public string VN_Lasik_Surgery_Limits { get; set; }
        public string VN_Lens_Tinting_Limits { get; set; }
        public string VN_Lenticular_Lens_Limits { get; set; }
        public string VN_Mirror_Coating_Limits { get; set; }
        public string VN_Non_Prescription_Lens_Limits { get; set; }
        public string VN_Other_Limits { get; set; }
        public string VN_PRK_Surgery_Limits { get; set; }
        public string VN_Radial_Keratotomy_Limits { get; set; }
        public string VN_Refractive_Eye_Surgery_Limits { get; set; }
        public string VN_Safety_Eyeglass_Frames_Limits { get; set; }
        public string VN_Single_Vision_Lens_Limits { get; set; }
        public string VN_Soft_Contacts_Limits { get; set; }
        public string VN_Sunglass_Frames_Limits { get; set; }
        public string VN_Trifocals_Limits { get; set; }
        public string VN_Vision_Exam_Limits { get; set; }






        //#region
        //public string Exc_IllegActLimitExcAdd { get; set; }
        //public string Exc_OccuInjLimitExcAdd { get; set; }
        //public string Exc_StdLimitExcl_Hdr { get; set; }
        //public string VN_Aborsrv_Limit { get; set; }
        //public string VN_AcuSerO_Limit { get; set; }
        //public string VN_AcuSer_Limit { get; set; }
        //public string VN_AddADHD_AddInfo { get; set; }
        //public string VN_AddADHD_Limit { get; set; }
        //public string VN_AdmSrv_COBRA { get; set; }
        //public string VN_AdmSrv_COBCONT { get; set; }
        //public string VN_AdmSrv_FSA { get; set; }
        //public string VN_AdmSrv_Forms { get; set; }
        //public string VN_AdmSrv_HIPPACer { get; set; }
        //public string VN_AdmSrv_LifeBill { get; set; }
        //public string VN_AdmSrv_MediPart { get; set; }
        //public string VN_AdmSrv_RetireeBill { get; set; }
        //public string VN_AdmSrv_SBCDis { get; set; }
        //public string VN_AlrgOfcVist_Limit { get; set; }
        //public string VN_AlrgSerm_Limit { get; set; }
        //public string VN_AlrgTest_Limit { get; set; }
        //public string VN_AmbSrv_AddInfo { get; set; }
        //public string VN_AmbSrv_Limit { get; set; }
        //public string VN_AmbSurFac_Limit { get; set; }
        //public string VN_AnesthSrv_Limit { get; set; }
        //public string VN_Autsm_AddInfo { get; set; }
        //public string VN_Autsm_Limit { get; set; }
        //public string VN_B12_AddInfo { get; set; }
        //public string VN_B12_Limit { get; set; }
        //public string VN_BO_Dental1 { get; set; }
        //public string VN_BO_Dental2 { get; set; }
        //public string VN_BO_Dental3 { get; set; }
        //public string VN_BO_Medical { get; set; }
        //public string VN_BO_Vision3 { get; set; }
        //public string VN_BrePump_AddInfo { get; set; }
        //public string VN_BrstPump_Limit { get; set; }
        //public string VN_BrthCent_Limit { get; set; }
        //public string VN_BrthCntrlOffVst_Limit { get; set; }
        //public string VN_BrthCntrl_Limit { get; set; }
        //public string VN_BrthCntrl_Value_AddInfo { get; set; }
        //public string VN_CMGMT_PRECETI_SERV_IH { get; set; }
        //public string VN_CardRehab_Limit { get; set; }
        //public string VN_ChScPra_Limit { get; set; }
        //public string VN_CheOff_Limit { get; set; }
        //public string VN_Chemo_Limit { get; set; }
        //public string VN_Chiro_Limit { get; set; }
        //public string VN_ClmInfo_Add { get; set; }
        //public string VN_ClmInfo_AppTmfrm { get; set; }
        //public string VN_Cmgmt_CertNonSchd { get; set; }
        //public string VN_Cmgmt_CertNonSchd_tm { get; set; }
        //public string VN_Cmgmt_CertOthrPro { get; set; }
        //public string VN_Cmgmt_CertOthrPro_dtl { get; set; }
        //public string VN_Cmgmt_NtwrkAdd1 { get; set; }
        //public string VN_Cmgmt_NtwrkAdd2 { get; set; }
        //public string VN_Cmgmt_PreCeti { get; set; }
        //public string VN_Cmgmt_PreCeti_Dtl { get; set; }
        //public string VN_Cmgmt_Referal { get; set; }
        //public string VN_Cmgmt_Value1 { get; set; }
        //public string VN_Cmgmt_Value2 { get; set; }
        //public string VN_CochDvc_Limit { get; set; }
        //public string VN_ConGlss_Limit { get; set; }
        //public string VN_CosmtSur_AddInfo { get; set; }
        //public string VN_CosmtSur_Limit { get; set; }
        //public string VN_Custdl_Limit { get; set; }
        //public string VN_DMediEqp_Limit { get; set; }
        //public string VN_DenSerAccOff_Limit { get; set; }
        //public string VN_DenSerNonAccOff_Limit { get; set; }
        //public string VN_Derma_Limit { get; set; }
        //public string VN_DgnLbRdo_Limit { get; set; }
        //public string VN_DiabeSupp_Limit { get; set; }
        //public string VN_DntlAcdnt_AddInfo { get; set; }
        //public string VN_DntlAcdnt_Limit { get; set; }
        //public string VN_DntlNonAcdnt_Limit { get; set; }
        //public string VN_DurMedEquOff_Limit { get; set; }
        //public string VN_EAP_Value1 { get; set; }
        //public string VN_EAP_Value2 { get; set; }
        //public string VN_ERISA_Value { get; set; }
        //public string VN_EduSerOff_Limit { get; set; }
        //public string VN_EduSrv_Limit { get; set; }
        //public string VN_ElecTelePhy_Limit { get; set; }
        //public string VN_EmeRooFacFee_Limit { get; set; }
        //public string VN_EmrgRm_AddInfo { get; set; }
        //public string VN_EmrgRm_Limit { get; set; }
        //public string VN_ExprDrug_Limit { get; set; }
        //public string VN_ExprProc_AddInfo { get; set; }
        //public string VN_ExprProc_Limit { get; set; }
        //public string VN_ExrEqup_Limit { get; set; }
        //public string VN_FMCoun_Limit { get; set; }
        //public string VN_FcPeel_Limit { get; set; }
        //public string VN_GI_Con_T1_PlPy { get; set; }
        //public string VN_GI_Con_T1_PtPy { get; set; }
        //public string VN_GI_Con_T2_PlPy { get; set; }
        //public string VN_GI_Con_T2_PtPy { get; set; }
        //public string VN_GI_Con_T3_PlPy { get; set; }
        //public string VN_GI_Con_T3_PtPy { get; set; }
        //public string VN_GI_Con_T4_PlPy { get; set; }
        //public string VN_GI_Con_T4_PtPy { get; set; }
        //public string VN_GI_Con_Value { get; set; }
        //public string VN_GI_Ded_AddInfo { get; set; }
        //public string VN_GI_Ded_AddInfo_2 { get; set; }
        //public string VN_GI_Ded_NetworkInfo { get; set; }
        //public string VN_GI_Ded_T1_Fmly { get; set; }
        //public string VN_GI_Ded_T1_Indv { get; set; }
        //public string VN_GI_Ded_T1_OT { get; set; }
        //public string VN_GI_Ded_T2_Fmly { get; set; }
        //public string VN_GI_Ded_T2_Indv { get; set; }
        //public string VN_GI_Ded_T2_OT { get; set; }
        //public string VN_GI_Ded_T3_Fmly { get; set; }
        //public string VN_GI_Ded_T3_Indv { get; set; }
        //public string VN_GI_Ded_T3_OT { get; set; }
        //public string VN_GI_Ded_T4_Fmly { get; set; }
        //public string VN_GI_Ded_T4_Indv { get; set; }
        //public string VN_GI_Ded_T4_OT { get; set; }
        //public string VN_GI_OutPkt_AddInfo { get; set; }
        //public string VN_GI_OutPkt_AddInfo_1 { get; set; }
        //public string VN_GI_OutPkt_AddInfo_2 { get; set; }
        //public string VN_GI_OutPkt_NtwrkInfo { get; set; }
        //public string VN_GI_OutPkt_T1_Fmly { get; set; }
        //public string VN_GI_OutPkt_T1_Indv { get; set; }
        //public string VN_GI_OutPkt_T1_OT { get; set; }
        //public string VN_GI_OutPkt_T2_Fmly { get; set; }
        //public string VN_GI_OutPkt_T2_Indv { get; set; }
        //public string VN_GI_OutPkt_T2_OT { get; set; }
        //public string VN_GI_OutPkt_T3_Fmly { get; set; }
        //public string VN_GI_OutPkt_T3_Indv { get; set; }
        //public string VN_GI_OutPkt_T3_OT { get; set; }
        //public string VN_GI_OutPkt_T4_Fmly { get; set; }
        //public string VN_GI_OutPkt_T4_Indv { get; set; }
        //public string VN_GI_OutPkt_T4_OT { get; set; }
        //public string VN_GenTest_AddInfo { get; set; }
        //public string VN_GenTest_Limit { get; set; }
        //public string VN_GrndFthr_Value { get; set; }
        //public string VN_GrpThrp_Limit { get; set; }
        //public string VN_Hdr_Bulletin { get; set; }
        //public string VN_Hdr_Plan1 { get; set; }
        //public string VN_Hdr_Plan2 { get; set; }
        //public string VN_Hdr_Plan3 { get; set; }
        //public string VN_HemOff_Limit { get; set; }
        //public string VN_Hemo_Limit { get; set; }
        //public string VN_HmHlCare_Limit { get; set; }
        //public string VN_HosInPtn_AddInfo { get; set; }
        //public string VN_HosInPtn_Limit { get; set; }
        //public string VN_HosOutPtnRtn_Limit { get; set; }
        //public string VN_HosOutPtnSur_Limit { get; set; }
        //public string VN_HosSrv_AddInfo { get; set; }
        //public string VN_HosSrv_Limit { get; set; }
        //public string VN_HrExTst_Limit { get; set; }
        //public string VN_Hypno_Limit { get; set; }
        //public string VN_InfDiaOff_Limit { get; set; }
        //public string VN_InfSrv_AddInfo { get; set; }
        //public string VN_InfSrv_Limit { get; set; }
        //public string VN_InfTreOff_Limit { get; set; }
        //public string VN_InvDrgPrc_Limit { get; set; }
        //public string VN_LcmMgmt_Limit { get; set; }
        //public string VN_MDSupp_Limit { get; set; }
        //public string VN_MILIEUSit_Limit { get; set; }
        //public string VN_MasTheOff_Limit { get; set; }
        //public string VN_MatrSrv_AddInfo { get; set; }
        //public string VN_MatrSrv_Limit { get; set; }
        //public string VN_MemReq_AddInfo { get; set; }
        //public string VN_MemReq_Limit { get; set; }
        //public string VN_MntlIn_AddInfo { get; set; }
        //public string VN_MntlIn_Limit { get; set; }
        //public string VN_MntlOut_AddInfo { get; set; }
        //public string VN_MntlOut_Limit { get; set; }
        //public string VN_MorObeOff_Limit { get; set; }
        //public string VN_MorObeSurOff_Limit { get; set; }
        //public string VN_Msg_Limit { get; set; }
        //public string VN_NonRouHeaOff_Limit { get; set; }
        //public string VN_NonRtnVsnCGC_Limit { get; set; }
        //public string VN_NonRtnVsnC_Limit { get; set; }
        //public string VN_NonRtnVsn_AddInfo { get; set; }
        //public string VN_NonRtnVsn_Limit { get; set; }
        //public string VN_NtwInfo_Ntwrk { get; set; }
        //public string VN_NtwInfo_OutNtwrk1 { get; set; }
        //public string VN_NtwInfo_OutNtwrk2 { get; set; }
        //public string VN_NtwInfo_OutNtwrk3 { get; set; }
        //public string VN_NtwInfo_UCRval { get; set; }
        //public string VN_NutSupp_Limit { get; set; }
        //public string VN_ObSurg_AddInfo { get; set; }
        //public string VN_ObSurg_Limit { get; set; }
        //public string VN_ObWtContr_Limit { get; set; }
        //public string VN_Onco_Value1 { get; set; }
        //public string VN_Onco_Value2 { get; set; }
        //public string VN_OrtOff_Limit { get; set; }
        //public string VN_OrthBNKW_AddInfo { get; set; }
        //public string VN_OrthBNKW_Limit { get; set; }
        //public string VN_OrthSho_AddInfo { get; set; }
        //public string VN_OrthSho_Limit { get; set; }
        //public string VN_OrthopOff_Limit { get; set; }
        //public string VN_OutOccThrp_AddInfo { get; set; }
        //public string VN_OutOccThrp_Limit { get; set; }
        //public string VN_OutPhyThrp_Limit { get; set; }
        //public string VN_OutSpchTh_AddInfo { get; set; }
        //public string VN_OutSpchTh_Limit { get; set; }
        //public string VN_PCPoNonRtnC_AddInfo { get; set; }
        //public string VN_PCPoNonRtnC_Limit { get; set; }
        //public string VN_PCPoNonRtnC_T1_Value { get; set; }
        //public string VN_PCPoNonRtnC_T2_Value { get; set; }
        //public string VN_PCPoNonRtnC_T3_Value { get; set; }
        //public string VN_PCPoNonRtnC_T4_Value { get; set; }
        //public string VN_PhOfVstNRtn_AddInfo { get; set; }
        //public string VN_PhOfVstNRtn_Limit { get; set; }
        //public string VN_PhrmcyBnftMgr_Val10 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val11 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val12 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val13 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val14 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val1 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val2 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val3 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val4 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val5 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val6 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val7 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val8 { get; set; }
        //public string VN_PhrmcyBnftMgr_Val9 { get; set; }
        //public string VN_PhySNFCon_Limit { get; set; }
        //public string VN_PodiSrv_AddInfo { get; set; }
        //public string VN_PodiSrv_Limit { get; set; }
        //public string VN_Podoff_Limit { get; set; }
        //public string VN_PrExConWt_Value { get; set; }
        //public string VN_PreBen_3DGen { get; set; }
        //public string VN_PreBen_3DPrefBrand { get; set; }
        //public string VN_PreBen_3DNonPrefBrand { get; set; }
        //public string VN_PreBen_3DSplMedi { get; set; }
        //public string VN_PreBen_3DSRGen { get; set; }
        //public string VN_PreBen_3DSRPrefBrand { get; set; }
        //public string VN_PreBen_3DSRNonPrefBrand { get; set; }
        //public string VN_PreBen_3DSRSplMedi { get; set; }
        //public string VN_PreBen_31DSMGen { get; set; }
        //public string VN_PreBen_31DSMPrefBrand { get; set; }
        //public string VN_PreBen_31DSMNonPrefBrand { get; set; }
        //public string VN_PreBen_31DSMSplMedi { get; set; }
        //public string VN_PreBen_31DSRGen { get; set; }
        //public string VN_PreBen_31DSRPrefBrand { get; set; }
        //public string VN_PreBen_31DSRNonPrefBrand { get; set; }
        //public string VN_PreBen_31DSRSplMedi { get; set; }
        //public string VN_PreBen_34DSMGen { get; set; }
        //public string VN_PreBen_34DSMPrefBrand { get; set; }
        //public string VN_PreBen_34DSMNonPrefBrand { get; set; }
        //public string VN_PreBen_34DSMSplMedi { get; set; }
        //public string VN_PreBen_34DSRGen { get; set; }
        //public string VN_PreBen_34DSRPrefBrand { get; set; }
        //public string VN_PreBen_34DSRNonPrefBrand { get; set; }
        //public string VN_PreBen_34DSRSplMedi { get; set; }
        //public string VN_PreBen_303134DSMGen { get; set; }
        //public string VN_PreBen_303134DSMPrefBrand { get; set; }
        //public string VN_PreBen_303134DSMNonPrefBrand { get; set; }
        //public string VN_PreBen_303134DSMSplMedi { get; set; }
        //public string VN_PreBen_303134DSRGen { get; set; }
        //public string VN_PreBen_303134DSRPrefBrand { get; set; }
        //public string VN_PreBen_303134DSRNonPrefBrand { get; set; }
        //public string VN_PreBen_303134DSRSplMedi { get; set; }
        //public string VN_PreBen_60DSMGen { get; set; }
        //public string VN_PreBen_60DSMPrefBrand { get; set; }
        //public string VN_PreBen_60DSMNonPrefBrand { get; set; }
        //public string VN_PreBen_60DSMSplMedi { get; set; }
        //public string VN_PreBen_60DSRGen { get; set; }
        //public string VN_PreBen_60DSRPrefBrand { get; set; }
        //public string VN_PreBen_60DSRNonPrefBrand { get; set; }
        //public string VN_PreBen_60DSRSplMedi { get; set; }
        //public string VN_PreBen_60D90SRGen { get; set; }
        //public string VN_PreBen_60D90SRPrefBrand { get; set; }
        //public string VN_PreBen_60D90SRNonPrefBrand { get; set; }
        //public string VN_PreBen_60D90SRSplMedi { get; set; }
        //public string VN_PreBen_60D90SMGen { get; set; }
        //public string VN_PreBen_60D90SMPrefBrand { get; set; }
        //public string VN_PreBen_60D90SMNonPrefBrand { get; set; }
        //public string VN_PreBen_60D90SMSplMedi { get; set; }
        //public string VN_PreBen_90DSGen { get; set; }
        //public string VN_PreBen_90DSPrefBrand { get; set; }
        //public string VN_PreBen_90DSNonPrefBrand { get; set; }
        //public string VN_PreBen_90DSSplMedi { get; set; }
        //public string VN_ProOff_Limit { get; set; }
        //public string VN_ProsthApp_AddInfo { get; set; }
        //public string VN_ProsthApp_Limit { get; set; }
        //public string VN_PrsnCon_Limit { get; set; }
        //public string VN_PulRehOff_Limit { get; set; }
        //public string VN_PulReh_Limit { get; set; }
        //public string VN_PvtDNurs_Limit { get; set; }
        //public string VN_RadThr_Limit { get; set; }
        //public string VN_RntNusry_AddInfo { get; set; }
        //public string VN_RntNusry_Limit { get; set; }
        //public string VN_RoboSurg_Limit { get; set; }
        //public string VN_RtnHM_AddInfo { get; set; }
        //public string VN_RtnHM_Limit { get; set; }
        //public string VN_RtnVsn_Limit { get; set; }
        //public string VN_STSurgOpn_Limit { get; set; }
        //public string VN_SecSurOff_Limit { get; set; }
        //public string VN_SelfInIn_Limit { get; set; }
        //public string VN_SexDFunc_AddInfo { get; set; }
        //public string VN_SexDFunc_Limit { get; set; }
        //public string VN_SexTransfrm_AddInfo { get; set; }
        //public string VN_SexTransfrm_Limit { get; set; }
        //public string VN_SkilNursFac_AddInfo { get; set; }
        //public string VN_SkilNursFac_Limit { get; set; }
        //public string VN_SleDisOff_Limit { get; set; }
        //public string VN_SleDisStu_Limit { get; set; }
        //public string VN_SleDis_AddInfo { get; set; }
        //public string VN_SmkCess_Limit { get; set; }
        //public string VN_SmoCesOff_Limit { get; set; }
        //public string VN_SmoCes_AddInfo { get; set; }
        //public string VN_SplPhyoNRtn_Limit { get; set; }
        //public string VN_SplPhyoNRtn_T1_Value { get; set; }
        //public string VN_SplPhyoNRtn_T2_Value { get; set; }
        //public string VN_SplPhyoNRtn_T3_Value { get; set; }
        //public string VN_SplPhyoNRtn_T4_Value { get; set; }
        //public string VN_SurgStk_Limit { get; set; }
        //public string VN_SurgnFB_Limit { get; set; }
        //public string VN_T1_Aborsrv_AddInfo { get; set; }
        //public string VN_T1_Aborsrv_OthrSrvWO { get; set; }
        //public string VN_T1_AcuSerO_NotCov { get; set; }
        //public string VN_T1_AcuSer_NotCov { get; set; }
        //public string VN_T1_AddADHD_Value { get; set; }
        //public string VN_T1_AlrgOfcVist_PCP { get; set; }
        //public string VN_T1_AlrgSerm_Value { get; set; }
        //public string VN_T1_AlrgTest_Value { get; set; }
        //public string VN_T1_AmbSrv_Value { get; set; }
        //public string VN_T1_AmbSurFac_Value { get; set; }
        //public string VN_T1_AnesthSrv_Value { get; set; }
        //public string VN_T1_Autsm_Value { get; set; }
        //public string VN_T1_B12_Value { get; set; }
        //public string VN_T1_BrthCent_Value { get; set; }
        //public string VN_T1_BrthCntrlOffVst_Value { get; set; }
        //public string VN_T1_BrthCntrl_Value { get; set; }
        //public string VN_T1_CardRehab_Value { get; set; }
        //public string VN_T1_ChScPra_Value { get; set; }
        //public string VN_T1_CheOff_Value { get; set; }
        //public string VN_T1_Chemo_Value { get; set; }
        //public string VN_T1_Chiro_Value { get; set; }
        //public string VN_T1_CochDvc_Value { get; set; }
        //public string VN_T1_ConGlss_Value { get; set; }
        //public string VN_T1_CosmtSur_Value { get; set; }
        //public string VN_T1_Custdl_Value { get; set; }
        //public string VN_T1_DMediEqp_Value { get; set; }
        //public string VN_T1_DenSerAccOff_Value { get; set; }
        //public string VN_T1_DenSerNonAccOff_Value { get; set; }
        //public string VN_T1_Derma_Value { get; set; }
        //public string VN_T1_DgnLbRdo_value { get; set; }
        //public string VN_T1_DiabeSupp_Value { get; set; }
        //public string VN_T1_DntlAcdnt_Value { get; set; }
        //public string VN_T1_DntlNonAcdnt_Value { get; set; }
        //public string VN_T1_DurMedEquOff_Value { get; set; }
        //public string VN_T1_EduSerOff_Value { get; set; }
        //public string VN_T1_EduSrv_Value { get; set; }
        //public string VN_T1_ElecTelePhy_Value { get; set; }
        //public string VN_T1_EmeRooFacFee_Value { get; set; }
        //public string VN_T1_EmrgRm_Value2 { get; set; }
        //public string VN_T1_EmrgRm_Value { get; set; }
        //public string VN_T1_ExprDrug_Value { get; set; }
        //public string VN_T1_ExprProc_Value { get; set; }
        //public string VN_T1_ExrEqup_Value { get; set; }
        //public string VN_T1_FMCoun_Value { get; set; }
        //public string VN_T1_FcPeel_Value { get; set; }
        //public string VN_T1_GenTest_Value { get; set; }
        //public string VN_T1_GrpThrp_Value { get; set; }
        //public string VN_T1_HemOff_Value { get; set; }
        //public string VN_T1_Hemo_value { get; set; }
        //public string VN_T1_HmHlCare_value { get; set; }
        //public string VN_T1_HosInPtn_value { get; set; }
        //public string VN_T1_HosOutPtnRtn_value { get; set; }
        //public string VN_T1_HosOutPtnSur_value { get; set; }
        //public string VN_T1_HosSrv_value { get; set; }
        //public string VN_T1_HrExTst_Value { get; set; }
        //public string VN_T1_Hypno_Value { get; set; }
        //public string VN_T1_InfDiaOff_Value { get; set; }
        //public string VN_T1_InfSrv_Value { get; set; }
        //public string VN_T1_InfTreOff_Value { get; set; }
        //public string VN_T1_InvDrgPrc_Value { get; set; }
        //public string VN_T1_LcmMgmt_Value { get; set; }
        //public string VN_T1_MDSupp_Value { get; set; }
        //public string VN_T1_MILIEUSit_Value { get; set; }
        //public string VN_T1_MasTheOff_Value { get; set; }
        //public string VN_T1_MatrSrv_Value { get; set; }
        //public string VN_T1_MemReq_Value { get; set; }
        //public string VN_T1_MntlIn_Value { get; set; }
        //public string VN_T1_MntlOut_value { get; set; }
        //public string VN_T1_MorObeOff_Value { get; set; }
        //public string VN_T1_MorObeSurOff_Value { get; set; }
        //public string VN_T1_Msg_Value { get; set; }
        //public string VN_T1_NonRouHeaOff_Value { get; set; }
        //public string VN_T1_NonRtnVsnCGC_Value { get; set; }
        //public string VN_T1_NonRtnVsnC_Value { get; set; }
        //public string VN_T1_NonRtnVsn_Con { get; set; }
        //public string VN_T1_NonRtnVsn_OV { get; set; }
        //public string VN_T1_NonRtnVsn_OfSrv { get; set; }
        //public string VN_T1_NutSupp_Value { get; set; }
        //public string VN_T1_ObSurg_Value { get; set; }
        //public string VN_T1_ObWtContr_Value { get; set; }
        //public string VN_T1_OrtOff_Value { get; set; }
        //public string VN_T1_OrthBNKW_Value { get; set; }
        //public string VN_T1_OrthSho_Value { get; set; }
        //public string VN_T1_OrthopOff_Value { get; set; }
        //public string VN_T1_OutOccThrp_Value { get; set; }
        //public string VN_T1_OutPhyThrp_Value { get; set; }
        //public string VN_T1_OutSpchTh_Value { get; set; }
        //public string VN_T1_PhOfVstNRtn_Value { get; set; }
        //public string VN_T1_PhySNFCon_Value { get; set; }
        //public string VN_T1_PodiSrv_Value { get; set; }
        //public string VN_T1_Podoff_Value { get; set; }
        //public string VN_T1_ProOff_Value { get; set; }
        //public string VN_T1_ProsthApp_Value { get; set; }
        //public string VN_T1_PrsnCon_Value { get; set; }
        //public string VN_T1_PulRehOff_Value { get; set; }
        //public string VN_T1_PulReh_Value { get; set; }
        //public string VN_T1_PvtDNurs_Value { get; set; }
        //public string VN_T1_RadThr_Value { get; set; }
        //public string VN_T1_RntNusry_Value { get; set; }
        //public string VN_T1_RoboSurg_Value { get; set; }
        //public string VN_T1_RtnHM_Value { get; set; }
        //public string VN_T1_RtnVsn_Value { get; set; }
        //public string VN_T1_STSurgOpn_PCP { get; set; }
        //public string VN_T1_SecSurOff_Value { get; set; }
        //public string VN_T1_SexDFunc_Value { get; set; }
        //public string VN_T1_SexTransfrm_Value { get; set; }
        //public string VN_T1_SkilNursFac_PCP { get; set; }
        //public string VN_T1_SleDisOff_Value { get; set; }
        //public string VN_T1_SleDisStu_Value { get; set; }
        //public string VN_T1_SleepDis_Lab { get; set; }
        //public string VN_T1_SleepDis_OthrSrvW { get; set; }
        //public string VN_T1_SleepDis_OthrSrvWo { get; set; }
        //public string VN_T1_SleepDis_PCP { get; set; }
        //public string VN_T1_SleepDis_Spl { get; set; }
        //public string VN_T1_SleepDis_Xray { get; set; }
        //public string VN_T1_SmkCess_Value { get; set; }
        //public string VN_T1_SmoCesOff_Value { get; set; }
        //public string VN_T1_SurgStk_Value { get; set; }
        //public string VN_T1_SurgnFB_Value { get; set; }
        //public string VN_T1_TMJNonSurAduOff_Value { get; set; }
        //public string VN_T1_TMJNonSurPedOff_Value { get; set; }
        //public string VN_T1_TMJSurAduOff_Value { get; set; }
        //public string VN_T1_TMJSurPedOff_Value { get; set; }
        //public string VN_T1_TMJT_value { get; set; }
        //public string VN_T1_TraOff_Value { get; set; }
        //public string VN_T1_Transpl_value { get; set; }
        //public string VN_T1_UrgCarFac_Value { get; set; }
        //public string VN_T1_UrgCareF_value { get; set; }
        //public string VN_T1_Vsctomy_Value { get; set; }
        //public string VN_T1_WigOff_Value { get; set; }
        //public string VN_T1_Wings_value { get; set; }
        //public string VN_T2_Aborsrv_OthrSrvWO { get; set; }
        //public string VN_T2_AcuSerO_NotCov { get; set; }
        //public string VN_T2_AcuSer_NotCov { get; set; }
        //public string VN_T2_AddADHD_Value { get; set; }
        //public string VN_T2_AlrgOfcVist_PCP { get; set; }
        //public string VN_T2_AlrgSerm_Value { get; set; }
        //public string VN_T2_AlrgTest_Value { get; set; }
        //public string VN_T3_AlrgTest_Value { get; set; }
        //public string VN_T4_AlrgTest_Value { get; set; }
        //public string VN_T2_AmbSrv_Value { get; set; }
        //public string VN_T2_AmbSurFac_Value { get; set; }
        //public string VN_T2_AnesthSrv_Value { get; set; }
        //public string VN_T2_Autsm_Value { get; set; }
        //public string VN_T2_B12_Value { get; set; }
        //public string VN_T2_BrthCent_Value { get; set; }
        //public string VN_T2_BrthCntrlOffVst_Value { get; set; }
        //public string VN_T2_BrthCntrl_Value { get; set; }
        //public string VN_T2_CardRehab_Value { get; set; }
        //public string VN_T2_ChScPra_Value { get; set; }
        //public string VN_T2_CheOff_Value { get; set; }
        //public string VN_T2_Chemo_Value { get; set; }
        //public string VN_T2_Chiro_Value { get; set; }
        //public string VN_T2_CochDvc_Value { get; set; }
        //public string VN_T2_ConGlss_Value { get; set; }
        //public string VN_T2_CosmtSur_Value { get; set; }
        //public string VN_T2_Custdl_Value { get; set; }
        //public string VN_T2_DMediEqp_Value { get; set; }
        //public string VN_T2_DenSerAccOff_Value { get; set; }
        //public string VN_T2_DenSerNonAccOff_Value { get; set; }
        //public string VN_T2_Derma_Value { get; set; }
        //public string VN_T2_DgnLbRdo_value { get; set; }
        //public string VN_T2_DiabeSupp_Value { get; set; }
        //public string VN_T2_DntlAcdnt_Value { get; set; }
        //public string VN_T2_DntlNonAcdnt_Value { get; set; }
        //public string VN_T2_DurMedEquOff_Value { get; set; }
        //public string VN_T2_EduSerOff_Value { get; set; }
        //public string VN_T2_EduSrv_Value { get; set; }
        //public string VN_T2_ElecTelePhy_Value { get; set; }
        //public string VN_T2_EmeRooFacFee_Value { get; set; }
        //public string VN_T2_EmrgRm_Value2 { get; set; }
        //public string VN_T2_EmrgRm_Value { get; set; }
        //public string VN_T2_ExprDrug_Value { get; set; }
        //public string VN_T2_ExprProc_Value { get; set; }
        //public string VN_T2_ExrEqup_Value { get; set; }
        //public string VN_T2_FMCoun_Value { get; set; }
        //public string VN_T2_FcPeel_Value { get; set; }
        //public string VN_T2_GenTest_Value { get; set; }
        //public string VN_T2_GrpThrp_Value { get; set; }
        //public string VN_T2_HemOff_Value { get; set; }
        //public string VN_T2_Hemo_value { get; set; }
        //public string VN_T2_HmHlCare_value { get; set; }
        //public string VN_T2_HosInPtn_value { get; set; }
        //public string VN_T2_HosOutPtnRtn_value { get; set; }
        //public string VN_T2_HosOutPtnSur_value { get; set; }
        //public string VN_T2_HosSrv_value { get; set; }
        //public string VN_T2_HrExTst_Value { get; set; }
        //public string VN_T2_Hypno_Value { get; set; }
        //public string VN_T2_InfDiaOff_Value { get; set; }
        //public string VN_T2_InfSrv_Value { get; set; }
        //public string VN_T2_InfTreOff_Value { get; set; }
        //public string VN_T2_InvDrgPrc_Value { get; set; }
        //public string VN_T2_LcmMgmt_Value { get; set; }
        //public string VN_T2_MDSupp_Value { get; set; }
        //public string VN_T2_MILIEUSit_Value { get; set; }
        //public string VN_T2_MasTheOff_Value { get; set; }
        //public string VN_T2_MatrSrv_Value { get; set; }
        //public string VN_T2_MemReq_Value { get; set; }
        //public string VN_T2_MntlIn_Value { get; set; }
        //public string VN_T2_MntlOut_value { get; set; }
        //public string VN_T2_MorObeOff_Value { get; set; }
        //public string VN_T2_MorObeSurOff_Value { get; set; }
        //public string VN_T2_Msg_Value { get; set; }
        //public string VN_T2_NonRouHeaOff_Value { get; set; }
        //public string VN_T2_NonRtnVsnCGC_Value { get; set; }
        //public string VN_T2_NonRtnVsnC_Value { get; set; }
        //public string VN_T2_NonRtnVsn_OV { get; set; }
        //public string VN_T2_NutSupp_Value { get; set; }
        //public string VN_T2_ObSurg_Value { get; set; }
        //public string VN_T2_ObWtContr_Value { get; set; }
        //public string VN_T2_OrtOff_Value { get; set; }
        //public string VN_T2_OrthBNKW_Value { get; set; }
        //public string VN_T2_OrthSho_Value { get; set; }
        //public string VN_T2_OrthopOff_Value { get; set; }
        //public string VN_T2_OutOccThrp_Value { get; set; }
        //public string VN_T2_OutPhyThrp_Value { get; set; }
        //public string VN_T2_OutSpchTh_Value { get; set; }
        //public string VN_T2_PhOfVstNRtn_Value { get; set; }
        //public string VN_T2_PhySNFCon_Value { get; set; }
        //public string VN_T2_PodiSrv_Value { get; set; }
        //public string VN_T2_Podoff_Value { get; set; }
        //public string VN_T2_ProOff_Value { get; set; }
        //public string VN_T2_ProsthApp_Value { get; set; }
        //public string VN_T2_PrsnCon_Value { get; set; }
        //public string VN_T2_PulRehOff_Value { get; set; }
        //public string VN_T2_PulReh_Value { get; set; }
        //public string VN_T2_PvtDNurs_Value { get; set; }
        //public string VN_T2_RadThr_Value { get; set; }
        //public string VN_T2_RntNusry_Value { get; set; }
        //public string VN_T2_RoboSurg_Value { get; set; }
        //public string VN_T2_RtnVsn_Value { get; set; }
        //public string VN_T2_STSurgOpn_PCP { get; set; }
        //public string VN_T2_SecSurOff_Value { get; set; }
        //public string VN_T2_SexDFunc_Value { get; set; }
        //public string VN_T2_SexTransfrm_Value { get; set; }
        //public string VN_T2_SkilNursFac_PCP { get; set; }
        //public string VN_T2_SleDisOff_Value { get; set; }
        //public string VN_T2_SleDisStu_Value { get; set; }
        //public string VN_T2_SleepDis_LABFB { get; set; }
        //public string VN_T2_SleepDis_LABPB { get; set; }
        //public string VN_T2_SleepDis_OthrSrvW { get; set; }
        //public string VN_T2_SleepDis_OthrSrvWo { get; set; }
        //public string VN_T2_SleepDis_PCP { get; set; }
        //public string VN_T2_SleepDis_Spl { get; set; }
        //public string VN_T2_SmkCess_Value { get; set; }
        //public string VN_T2_SmoCesOff_Value { get; set; }
        //public string VN_T2_SurgStk_Value { get; set; }
        //public string VN_T2_SurgnFB_Value { get; set; }
        //public string VN_T2_TMJNonSurAduOff_Value { get; set; }
        //public string VN_T2_TMJNonSurPedOff_Value { get; set; }
        //public string VN_T2_TMJSurAduOff_Value { get; set; }
        //public string VN_T2_TMJSurPedOff_Value { get; set; }
        //public string VN_T2_TMJT_value { get; set; }
        //public string VN_T2_TraOff_Value { get; set; }
        //public string VN_T2_Transpl_value { get; set; }
        //public string VN_T2_UrgCarFac_Value { get; set; }
        //public string VN_T2_UrgCareF_value { get; set; }
        //public string VN_T2_Vsctomy_Value { get; set; }
        //public string VN_T2_WigOff_Value { get; set; }
        //public string VN_T2_Wings_value { get; set; }
        //public string VN_T3_Aborsrv_OthrSrvWO { get; set; }
        //public string VN_T3_AcuSerO_NotCov { get; set; }
        //public string VN_T3_AcuSer_NotCov { get; set; }
        //public string VN_T3_AddADHD_Value { get; set; }
        //public string VN_T3_AlrgOfcVist_PCP { get; set; }
        //public string VN_T3_AlrgSerm_Value { get; set; }
        //public string VN_T3_AmbSrv_Value { get; set; }
        //public string VN_T3_AmbSurFac_Value { get; set; }
        //public string VN_T3_AnesthSrv_Value { get; set; }
        //public string VN_T3_Autsm_Value { get; set; }
        //public string VN_T3_B12_Value { get; set; }
        //public string VN_T3_BrthCent_Value { get; set; }
        //public string VN_T3_BrthCntrlOffVst_Value { get; set; }
        //public string VN_T3_BrthCntrl_Value { get; set; }
        //public string VN_T3_CardRehab_Value { get; set; }
        //public string VN_T3_ChScPra_Value { get; set; }
        //public string VN_T3_CheOff_Value { get; set; }
        //public string VN_T3_Chemo_Value { get; set; }
        //public string VN_T3_Chiro_Value { get; set; }
        //public string VN_T3_CochDvc_Value { get; set; }
        //public string VN_T3_ConGlss_Value { get; set; }
        //public string VN_T3_CosmtSur_Value { get; set; }
        //public string VN_T3_Custdl_Value { get; set; }
        //public string VN_T3_DMediEqp_AddInfo { get; set; }
        //public string VN_T3_DMediEqp_Value { get; set; }
        //public string VN_T3_DenSerAccOff_Value { get; set; }
        //public string VN_T3_DenSerNonAccOff_Value { get; set; }
        //public string VN_T3_Derma_Value { get; set; }
        //public string VN_T3_DgnLbRdo_value { get; set; }
        //public string VN_T3_DiabeSupp_Value { get; set; }
        //public string VN_T3_DntlAcdnt_Value { get; set; }
        //public string VN_T3_DntlNonAcdnt_Value { get; set; }
        //public string VN_T3_DurMedEquOff_Value { get; set; }
        //public string VN_T3_EduSerOff_Value { get; set; }
        //public string VN_T3_EduSrv_Value { get; set; }
        //public string VN_T3_ElecTelePhy_Value { get; set; }
        //public string VN_T3_EmeRooFacFee_Value { get; set; }
        //public string VN_T3_EmrgRm_Value2 { get; set; }
        //public string VN_T3_EmrgRm_Value { get; set; }
        //public string VN_T3_ExprDrug_Value { get; set; }
        //public string VN_T3_ExprProc_Value { get; set; }
        //public string VN_T3_ExrEqup_Value { get; set; }
        //public string VN_T3_FMCoun_Value { get; set; }
        //public string VN_T3_FcPeel_Value { get; set; }
        //public string VN_T3_GenTest_Value { get; set; }
        //public string VN_T3_GrpThrp_Value { get; set; }
        //public string VN_T3_HemOff_Value { get; set; }
        //public string VN_T3_Hemo_value { get; set; }
        //public string VN_T3_HmHlCare_value { get; set; }
        //public string VN_T3_HosInPtn_value { get; set; }
        //public string VN_T3_HosOutPtnRtn_value { get; set; }
        //public string VN_T3_HosOutPtnSur_value { get; set; }
        //public string VN_T3_HosSrv_value { get; set; }
        //public string VN_T3_HrExTst_Value { get; set; }
        //public string VN_T3_Hypno_Value { get; set; }
        //public string VN_T3_InfDiaOff_Value { get; set; }
        //public string VN_T3_InfSrv_Value { get; set; }
        //public string VN_T3_InfTreOff_Value { get; set; }
        //public string VN_T3_InvDrgPrc_Value { get; set; }
        //public string VN_T3_LcmMgmt_Value { get; set; }
        //public string VN_T3_MDSupp_Value { get; set; }
        //public string VN_T3_MILIEUSit_Value { get; set; }
        //public string VN_T3_MasTheOff_Value { get; set; }
        //public string VN_T3_MatrSrv_Value { get; set; }
        //public string VN_T3_MemReq_Value { get; set; }
        //public string VN_T3_MntlIn_Value { get; set; }
        //public string VN_T3_MntlOut_value { get; set; }
        //public string VN_T3_MorObeOff_Value { get; set; }
        //public string VN_T3_MorObeSurOff_Value { get; set; }
        //public string VN_T3_Msg_Value { get; set; }
        //public string VN_T3_NonRouHeaOff_Value { get; set; }
        //public string VN_T3_NonRtnVsnCGC_Value { get; set; }
        //public string VN_T3_NonRtnVsnC_Value { get; set; }
        //public string VN_T3_NonRtnVsn_OV { get; set; }
        //public string VN_T3_NutSupp_Value { get; set; }
        //public string VN_T3_ObSurg_Value { get; set; }
        //public string VN_T3_ObWtContr_Value { get; set; }
        //public string VN_T3_OrtOff_Value { get; set; }
        //public string VN_T3_OrthBNKW_Value { get; set; }
        //public string VN_T3_OrthSho_Value { get; set; }
        //public string VN_T3_OrthopOff_Value { get; set; }
        //public string VN_T3_OutOccThrp_Value { get; set; }
        //public string VN_T3_OutPhyThrp_Value { get; set; }
        //public string VN_T3_OutSpchTh_Value { get; set; }
        //public string VN_T3_PhOfVstNRtn_Value { get; set; }
        //public string VN_T3_PhySNFCon_Value { get; set; }
        //public string VN_T3_PodiSrv_Value { get; set; }
        //public string VN_T3_Podoff_Value { get; set; }
        //public string VN_T3_ProOff_Value { get; set; }
        //public string VN_T3_ProsthApp_Value { get; set; }
        //public string VN_T3_PrsnCon_Value { get; set; }
        //public string VN_T3_PulRehOff_Value { get; set; }
        //public string VN_T3_PulReh_Value { get; set; }
        //public string VN_T3_PvtDNurs_Value { get; set; }
        //public string VN_T3_RadThr_Value { get; set; }
        //public string VN_T3_RntNusry_Value { get; set; }
        //public string VN_T3_RoboSurg_Value { get; set; }
        //public string VN_T3_RtnHM_Value { get; set; }
        //public string VN_T3_RtnVsn_Value { get; set; }
        //public string VN_T3_STSurgOpn_PCP { get; set; }
        //public string VN_T3_SecSurOff_Value { get; set; }
        //public string VN_T3_SexDFunc_Value { get; set; }
        //public string VN_T3_SexTransfrm_Value { get; set; }
        //public string VN_T3_SkilNursFac_PCP { get; set; }
        //public string VN_T3_SleDisOff_Value { get; set; }
        //public string VN_T3_SleDisStu_Value { get; set; }
        //public string VN_T3_SleepDis_Value { get; set; }
        //public string VN_T3_SmkCess_Value { get; set; }
        //public string VN_T3_SmoCesOff_Value { get; set; }
        //public string VN_T3_SurgStk_Value { get; set; }
        //public string VN_T3_SurgnFB_Value { get; set; }
        //public string VN_T3_TMJNonSurAduOff_Value { get; set; }
        //public string VN_T3_TMJNonSurPedOff_Value { get; set; }
        //public string VN_T3_TMJSurAduOff_Value { get; set; }
        //public string VN_T3_TMJSurPedOff_Value { get; set; }
        //public string VN_T3_TMJT_value { get; set; }
        //public string VN_T3_TraOff_Value { get; set; }
        //public string VN_T3_Transpl_value { get; set; }
        //public string VN_T3_UrgCarFac_Value { get; set; }
        //public string VN_T3_UrgCareF_value { get; set; }
        //public string VN_T3_Vsctomy_Value { get; set; }
        //public string VN_T3_WigOff_Value { get; set; }
        //public string VN_T3_Wings_value { get; set; }
        //public string VN_T4_Aborsrv_OthrSrvWO { get; set; }
        //public string VN_T4_AcuOff_Value { get; set; }
        //public string VN_T4_AcuSerO_NotCov { get; set; }
        //public string VN_T4_AcuSer_NotCov { get; set; }
        //public string VN_T4_AddADHD_Value { get; set; }
        //public string VN_T4_AlrgInj_value { get; set; }
        //public string VN_T4_AlrgOfcVist_PCP { get; set; }
        //public string VN_T4_AlrgSerm_Value { get; set; }
        //public string VN_T4_AmbSrv_Value { get; set; }
        //public string VN_T4_AmbSurFac_Value { get; set; }
        //public string VN_T4_AnesthSrv_Value { get; set; }
        //public string VN_T4_Autsm_Value { get; set; }
        //public string VN_T4_B12_Value { get; set; }
        //public string VN_T4_BrthCent_Value { get; set; }
        //public string VN_T4_BrthCntrlOffVst_Value { get; set; }
        //public string VN_T4_BrthCntrl_Value { get; set; }
        //public string VN_T4_CardRehab_Value { get; set; }
        //public string VN_T4_ChScPra_Value { get; set; }
        //public string VN_T4_CheOff_Value { get; set; }
        //public string VN_T4_Chemo_Value { get; set; }
        //public string VN_T4_Chiro_Value { get; set; }
        //public string VN_T4_ClncTrls_Value { get; set; }
        //public string VN_T4_CochDvc_Value { get; set; }
        //public string VN_T4_ConGlss_Value { get; set; }
        //public string VN_T4_CosmtSur_Value { get; set; }
        //public string VN_T4_Custdl_Value { get; set; }
        //public string VN_T4_DMediEqp_Value { get; set; }
        //public string VN_T4_DenSerAccOff_Value { get; set; }
        //public string VN_T4_DenSerNonAccOff_Value { get; set; }
        //public string VN_T4_Derma_Value { get; set; }
        //public string VN_T4_DgnLbRdo_value { get; set; }
        //public string VN_T4_DiabeSupp_Value { get; set; }
        //public string VN_T4_DntlAcdnt_Value { get; set; }
        //public string VN_T4_DntlNonAcdnt_Value { get; set; }
        //public string VN_T4_DurMedEquOff_Value { get; set; }
        //public string VN_T4_EduSerOff_Value { get; set; }
        //public string VN_T4_EduSrv_Value { get; set; }
        //public string VN_T4_ElecTelePhy_Value { get; set; }
        //public string VN_T4_EmeRooFacFee_Value { get; set; }
        //public string VN_T4_EmrgRm_Value2 { get; set; }
        //public string VN_T4_EmrgRm_Value { get; set; }
        //public string VN_T4_ExprDrug_Value { get; set; }
        //public string VN_T4_ExprProc_Value { get; set; }
        //public string VN_T4_ExrEqup_Value { get; set; }
        //public string VN_T4_FMCoun_Value { get; set; }
        //public string VN_T4_FcPeel_Value { get; set; }
        //public string VN_T4_GenTest_Value { get; set; }
        //public string VN_T4_GrpThrp_Value { get; set; }
        //public string VN_T4_HemOff_Value { get; set; }
        //public string VN_T4_Hemo_value { get; set; }
        //public string VN_T4_HmHlCare_value { get; set; }
        //public string VN_T4_HosInPtn_value { get; set; }
        //public string VN_T4_HosOutPtnRtn_value { get; set; }
        //public string VN_T4_HosOutPtnSur_value { get; set; }
        //public string VN_T4_HosSrv_value { get; set; }
        //public string VN_T4_HrExTst_Value { get; set; }
        //public string VN_T4_Hypno_Value { get; set; }
        //public string VN_T4_InfDiaOff_Value { get; set; }
        //public string VN_T4_InfSrv_Value { get; set; }
        //public string VN_T4_InfTreOff_Value { get; set; }
        //public string VN_T4_InfsonSrv_Value { get; set; }
        //public string VN_T4_InvDrgPrc_Value { get; set; }
        //public string VN_T4_LcmMgmt_Value { get; set; }
        //public string VN_T4_MDSupp_Value { get; set; }
        //public string VN_T4_MILIEUSit_Value { get; set; }
        //public string VN_T4_MasTheOff_Value { get; set; }
        //public string VN_T4_MatrSrv_Value { get; set; }
        //public string VN_T4_MemReq_Value { get; set; }
        //public string VN_T4_MntlIn_Value { get; set; }
        //public string VN_T4_MntlOut_value { get; set; }
        //public string VN_T4_MorObeOff_Value { get; set; }
        //public string VN_T4_MorObeSurOff_Value { get; set; }
        //public string VN_T4_Msg_Value { get; set; }
        //public string VN_T4_NonRouHeaOff_Value { get; set; }
        //public string VN_T4_NonRtnVsnCGC_Value { get; set; }
        //public string VN_T4_NonRtnVsnC_Value { get; set; }
        //public string VN_T4_NonRtnVsn_OV { get; set; }
        //public string VN_T4_NutSupp_Value { get; set; }
        //public string VN_T4_ObSurg_Value { get; set; }
        //public string VN_T4_ObWtContr_Value { get; set; }
        //public string VN_T4_OrtOff_Value { get; set; }
        //public string VN_T4_OrthBNKW_Value { get; set; }
        //public string VN_T4_OrthShFt_Value { get; set; }
        //public string VN_T4_OrthSho_Value { get; set; }
        //public string VN_T4_OrthopOff_Value { get; set; }
        //public string VN_T4_OutOccThrp_Value { get; set; }
        //public string VN_T4_OutPhyThrp_Value { get; set; }
        //public string VN_T4_OutSpchTh_Value { get; set; }
        //public string VN_T4_PhOfVstNRtn_Value { get; set; }
        //public string VN_T4_PhySNFCon_Value { get; set; }
        //public string VN_T4_PodiSrv_Value { get; set; }
        //public string VN_T4_Podoff_Value { get; set; }
        //public string VN_T4_ProOff_Value { get; set; }
        //public string VN_T4_ProsthApp_Value { get; set; }
        //public string VN_T4_PrsnCon_Value { get; set; }
        //public string VN_T4_PulRehOff_Value { get; set; }
        //public string VN_T4_PulReh_Value { get; set; }
        //public string VN_T4_PvtDNurs_Value { get; set; }
        //public string VN_T4_PvtDutNsr_Value { get; set; }
        //public string VN_T4_PvtNurD_Value { get; set; }
        //public string VN_T4_RadThe_Value { get; set; }
        //public string VN_T4_RadThr_Value { get; set; }
        //public string VN_T4_Resther_Value { get; set; }
        //public string VN_T4_RntNusry_Value { get; set; }
        //public string VN_T4_RoboSurg_Value { get; set; }
        //public string VN_T4_RtnBC_Value { get; set; }
        //public string VN_T4_RtnHM_Value { get; set; }
        //public string VN_T4_RtnVsn_Value { get; set; }
        //public string VN_T4_STSurgOpn_PCP { get; set; }
        //public string VN_T4_SecSurOff_Value { get; set; }
        //public string VN_T4_SexDFunc_Value { get; set; }
        //public string VN_T4_SexTransfrm_Value { get; set; }
        //public string VN_T4_SkilNursFac_PCP { get; set; }
        //public string VN_T4_SleDisOff_Value { get; set; }
        //public string VN_T4_SleDisStu_Value { get; set; }
        //public string VN_T4_SleepDis_Value { get; set; }
        //public string VN_T4_SmkCess_Value { get; set; }
        //public string VN_T4_SmoCesOff_Value { get; set; }
        //public string VN_T4_SurgStk_Value { get; set; }
        //public string VN_T4_SurgnFB_Value { get; set; }
        //public string VN_T4_TMJNonSurAduOff_Value { get; set; }
        //public string VN_T4_TMJNonSurPedOff_Value { get; set; }
        //public string VN_T4_TMJSurAduOff_Value { get; set; }
        //public string VN_T4_TMJSurPedOff_Value { get; set; }
        //public string VN_T4_TMJT_value { get; set; }
        //public string VN_T4_TraOff_Value { get; set; }
        //public string VN_T4_Transpl_value { get; set; }
        //public string VN_T4_UrgCarFac_Value { get; set; }
        //public string VN_T4_UrgCareF_value { get; set; }
        //public string VN_T4_VisnSrv_value { get; set; }
        //public string VN_T4_Vsctomy_Value { get; set; }
        //public string VN_T4_WigOff_Value { get; set; }
        //public string VN_T4_Wings_value { get; set; }
        //public string VN_TMJNonSurAduOff_Limit { get; set; }
        //public string VN_TMJNonSurPedOff_Limit { get; set; }
        //public string VN_TMJSurAduOff_Limit { get; set; }
        //public string VN_TMJSurPedOff_Limit { get; set; }
        //public string VN_TMJT_Limit { get; set; }
        //public string VN_TmjTre_AddInfo { get; set; }
        //public string VN_TraOff_Limit { get; set; }
        //public string VN_Transpl_AddInfo { get; set; }
        //public string VN_Transpl_Limit { get; set; }
        //public string VN_UrgCarFac_Limit { get; set; }
        //public string VN_UrgCareF_Limit { get; set; }
        //public string VN_Vsctomy_Limit { get; set; }
        //public string VN_WigOff_Limit { get; set; }
        //public string VN_Wings_AddInfo { get; set; }
        //public string VN_Wings_Limit { get; set; }
        //public string VN_Chirop_AddInfo { get; set; }
        //public string VN_LCM_AddInfo { get; set; }

        //public string VN_CS_VALS_T1 { get; set; }
        //public string VN_CS_VALS_T2 { get; set; }
        //public string VN_CS_VALS_T3 { get; set; }
        //public string VN_CS_VALS_T4 { get; set; }

        //public string VN_T1_EmrgRm_Value3 { get; set; }
        //public string VN_T2_EmrgRm_Value3 { get; set; }
        //public string VN_T3_EmrgRm_Value3 { get; set; }
        //public string VN_T4_EmrgRm_Value3 { get; set; }

        //public string VN_SleDisOrd_Limit { get; set; }
        //public string VN_T1_SleDisOrd_Value { get; set; }
        //public string VN_T2_SleDisOrd_Value { get; set; }
        //public string VN_T3_SleDisOrd_Value { get; set; }
        //public string VN_T4_SleDisOrd_Value { get; set; }

        //public string VN_T1_SelfInfInjury_Value { get; set; }
        //public string VN_T2_SelfInfInjury_Value { get; set; }
        //public string VN_T3_SelfInfInjury_Value { get; set; }
        //public string VN_T4_SelfInfInjury_Value { get; set; }
        //public string Exc_HzdInjTerrainCov { get; set; }
        //public string VN_NtwInfo_AddInfo { get; set; }

        //public string VN_Add_PlanInfo { get; set; }
        //public string VN_AddAdmstr_SvcInfo { get; set; }
        //public string VN_ClmInfo_AddInfo { get; set; }
        //public string VN_PhrmcyBnftMgr_AddInfo { get; set; }
        //public string VN_NtwrkInfo_AddInfo { get; set; }
        //public string VN_Vndr_AddInfo { get; set; }
        //public string VN_Precert_AddInfo { get; set; }

        //public string VN_PreBen_90DSRtGen { get; set; }
        //public string VN_PreBen_90DSRtPrefBrand { get; set; }
        //public string VN_PreBen_90DSRtNonPrefBrand { get; set; }
        //public string VN_PreBen_90DSRtSplMedi { get; set; }

        //public string VN_T2_RtnHM_Value { get; set; }

        //#region Exclusions
        //public string Exc_StdLimitExcl { get; set; }
        //public string Exc_HzdPHobActLimitExcl_Hdr { get; set; }
        //public string Exc_HzdPHobActLimitExcl_Info { get; set; }
        //public string Exc_FamMemLimitExc { get; set; }
        //public string Exc_IllegActLimitExc { get; set; }
        //public string Exc_OthLimitExc_HDr { get; set; }
        //public string Exc_OthLimitExc { get; set; }
        //public string Exc_OccuInjLimitExc { get; set; }
        //public string Exc_AddExcLimit_Trtment { get; set; }
        //public string Exc_AddExcLimit_Lang { get; set; }
        //#endregion

        //#region Additional PlaceHolders to accomodate, Office Visit Charge split up into two-  "Office Visit Charge - PCP"  and  "Office Visit Charge - Specialist"
        //public string VN_T1_AcuSerO_NotCov_Spe { get; set; }
        //public string VN_T1_AlrgOfcVist_PCP_Spe { get; set; }
        //public string VN_T1_BrthCntrlOffVst_Spe_Value { get; set; }
        //public string VN_T1_CheOff_Spe_Value { get; set; }
        //public string VN_T1_DenSerAccOff_Spe_Value { get; set; }
        //public string VN_T1_DenSerNonAccOff_Spe_Value { get; set; }
        //public string VN_T1_DurMedEquOff_Spe_Value { get; set; }
        //public string VN_T1_EduSerOff_Spe_Value { get; set; }
        //public string VN_T1_HemOff_Spe_Value { get; set; }
        //public string VN_T1_InfDiaOff_Spe_Value { get; set; }
        //public string VN_T1_InfTreOff_Spe_Value { get; set; }
        //public string VN_T1_MasTheOff_Spe_Value { get; set; }
        //public string VN_T1_MorObeOff_Spe_Value { get; set; }
        //public string VN_T1_MorObeSurOff_Spe_Value { get; set; }
        //public string VN_T1_NonRouHeaOff_Spe_Value { get; set; }
        //public string VN_T1_OrtOff_Spe_Value { get; set; }
        //public string VN_T1_OrthopOff_Spe_Value { get; set; }
        //public string VN_T1_Podoff_Spe_Value { get; set; }
        //public string VN_T1_ProOff_Spe_Value { get; set; }
        //public string VN_T1_PulRehOff_Spe_Value { get; set; }
        //public string VN_T1_SecSurOff_Spe_Value { get; set; }
        //public string VN_T1_SleDisOff_Spe_Value { get; set; }
        //public string VN_T1_SmoCesOff_Spe_Value { get; set; }
        //public string VN_SplPhyoNRtn_T1_Spe_Value { get; set; }
        //public string VN_T1_TMJNonSurPedOff_Spe_Value { get; set; }
        //public string VN_T1_TMJSurPedOff_Spe_Value { get; set; }
        //public string VN_T1_TMJNonSurAduOff_Spe_Value { get; set; }
        //public string VN_T1_TMJSurAduOff_Spe_Value { get; set; }
        //public string VN_T1_TraOff_Spe_Value { get; set; }
        //public string VN_T1_NonRtnVsn_OV_Spe { get; set; }
        //public string VN_T1_WigOff_Spe_Value { get; set; }

        //public string VN_T2_AcuSerO_NotCov_Spe { get; set; }
        //public string VN_T2_AlrgOfcVist_PCP_Spe { get; set; }
        //public string VN_T2_BrthCntrlOffVst_Spe_Value { get; set; }
        //public string VN_T2_CheOff_Spe_Value { get; set; }
        //public string VN_T2_DenSerAccOff_Spe_Value { get; set; }
        //public string VN_T2_DenSerNonAccOff_Spe_Value { get; set; }
        //public string VN_T2_DurMedEquOff_Spe_Value { get; set; }
        //public string VN_T2_EduSerOff_Spe_Value { get; set; }
        //public string VN_T2_HemOff_Spe_Value { get; set; }
        //public string VN_T2_InfDiaOff_Spe_Value { get; set; }
        //public string VN_T2_InfTreOff_Spe_Value { get; set; }
        //public string VN_T2_MasTheOff_Spe_Value { get; set; }
        //public string VN_T2_MorObeOff_Spe_Value { get; set; }
        //public string VN_T2_MorObeSurOff_Spe_Value { get; set; }
        //public string VN_T2_NonRouHeaOff_Spe_Value { get; set; }
        //public string VN_T2_OrtOff_Spe_Value { get; set; }
        //public string VN_T2_OrthopOff_Spe_Value { get; set; }
        //public string VN_T2_Podoff_Spe_Value { get; set; }
        //public string VN_T2_ProOff_Spe_Value { get; set; }
        //public string VN_T2_PulRehOff_Spe_Value { get; set; }
        //public string VN_T2_SecSurOff_Spe_Value { get; set; }
        //public string VN_T2_SleDisOff_Spe_Value { get; set; }
        //public string VN_T2_SmoCesOff_Spe_Value { get; set; }
        //public string VN_SplPhyoNRtn_T2_Spe_Value { get; set; }
        //public string VN_T2_TMJNonSurPedOff_Spe_Value { get; set; }
        //public string VN_T2_TMJSurPedOff_Spe_Value { get; set; }
        //public string VN_T2_TMJNonSurAduOff_Spe_Value { get; set; }
        //public string VN_T2_TMJSurAduOff_Spe_Value { get; set; }
        //public string VN_T2_TraOff_Spe_Value { get; set; }
        //public string VN_T2_NonRtnVsn_OV_Spe { get; set; }
        //public string VN_T2_WigOff_Spe_Value { get; set; }

        //public string VN_T3_AcuSerO_NotCov_Spe { get; set; }
        //public string VN_T3_AlrgOfcVist_PCP_Spe { get; set; }
        //public string VN_T3_BrthCntrlOffVst_Spe_Value { get; set; }
        //public string VN_T3_CheOff_Spe_Value { get; set; }
        //public string VN_T3_DenSerAccOff_Spe_Value { get; set; }
        //public string VN_T3_DenSerNonAccOff_Spe_Value { get; set; }
        //public string VN_T3_DurMedEquOff_Spe_Value { get; set; }
        //public string VN_T3_EduSerOff_Spe_Value { get; set; }
        //public string VN_T3_HemOff_Spe_Value { get; set; }
        //public string VN_T3_InfDiaOff_Spe_Value { get; set; }
        //public string VN_T3_InfTreOff_Spe_Value { get; set; }
        //public string VN_T3_MasTheOff_Spe_Value { get; set; }
        //public string VN_T3_MorObeOff_Spe_Value { get; set; }
        //public string VN_T3_MorObeSurOff_Spe_Value { get; set; }
        //public string VN_T3_NonRouHeaOff_Spe_Value { get; set; }
        //public string VN_T3_OrtOff_Spe_Value { get; set; }
        //public string VN_T3_OrthopOff_Spe_Value { get; set; }
        //public string VN_T3_Podoff_Spe_Value { get; set; }
        //public string VN_T3_ProOff_Spe_Value { get; set; }
        //public string VN_T3_PulRehOff_Spe_Value { get; set; }
        //public string VN_T3_SecSurOff_Spe_Value { get; set; }
        //public string VN_T3_SleDisOff_Spe_Value { get; set; }
        //public string VN_T3_SmoCesOff_Spe_Value { get; set; }
        //public string VN_SplPhyoNRtn_T3_Spe_Value { get; set; }
        //public string VN_T3_TMJNonSurPedOff_Spe_Value { get; set; }
        //public string VN_T3_TMJSurPedOff_Spe_Value { get; set; }
        //public string VN_T3_TMJNonSurAduOff_Spe_Value { get; set; }
        //public string VN_T3_TMJSurAduOff_Spe_Value { get; set; }
        //public string VN_T3_TraOff_Spe_Value { get; set; }
        //public string VN_T3_NonRtnVsn_OV_Spe { get; set; }
        //public string VN_T3_WigOff_Spe_Value { get; set; }

        //public string VN_T4_AcuSerO_NotCov_Spe { get; set; }
        //public string VN_T4_AlrgOfcVist_PCP_Spe { get; set; }
        //public string VN_T4_BrthCntrlOffVst_Spe_Value { get; set; }
        //public string VN_T4_CheOff_Spe_Value { get; set; }
        //public string VN_T4_DenSerAccOff_Spe_Value { get; set; }
        //public string VN_T4_DenSerNonAccOff_Spe_Value { get; set; }
        //public string VN_T4_DurMedEquOff_Spe_Value { get; set; }
        //public string VN_T4_EduSerOff_Spe_Value { get; set; }
        //public string VN_T4_HemOff_Spe_Value { get; set; }
        //public string VN_T4_InfDiaOff_Spe_Value { get; set; }
        //public string VN_T4_InfTreOff_Spe_Value { get; set; }
        //public string VN_T4_MasTheOff_Spe_Value { get; set; }
        //public string VN_T4_MorObeOff_Spe_Value { get; set; }
        //public string VN_T4_MorObeSurOff_Spe_Value { get; set; }
        //public string VN_T4_NonRouHeaOff_Spe_Value { get; set; }
        //public string VN_T4_OrtOff_Spe_Value { get; set; }
        //public string VN_T4_OrthopOff_Spe_Value { get; set; }
        //public string VN_T4_Podoff_Spe_Value { get; set; }
        //public string VN_T4_ProOff_Spe_Value { get; set; }
        //public string VN_T4_PulRehOff_Spe_Value { get; set; }
        //public string VN_T4_SecSurOff_Spe_Value { get; set; }
        //public string VN_T4_SleDisOff_Spe_Value { get; set; }
        //public string VN_T4_SmoCesOff_Spe_Value { get; set; }
        //public string VN_SplPhyoNRtn_T4_Spe_Value { get; set; }
        //public string VN_T4_TMJNonSurPedOff_Spe_Value { get; set; }
        //public string VN_T4_TMJSurPedOff_Spe_Value { get; set; }
        //public string VN_T4_TMJNonSurAduOff_Spe_Value { get; set; }
        //public string VN_T4_TMJSurAduOff_Spe_Value { get; set; }
        //public string VN_T4_TraOff_Spe_Value { get; set; }
        //public string VN_T4_NonRtnVsn_OV_Spe { get; set; }
        //public string VN_T4_WigOff_Spe_Value { get; set; }

        ///*** Limits  ***/
        //public string VN_AcuSerO_Spe_Limit { get; set; }
        //public string VN_AlrgOfcVist_Spe_Limit { get; set; }
        //public string VN_BrthCntrlOffVst_Spe_Limit { get; set; }
        //public string VN_CheOff_Spe_Limit { get; set; }
        //public string VN_DenSerAccOff_Spe_Limit { get; set; }
        //public string VN_DenSerNonAccOff_Spe_Limit { get; set; }
        //public string VN_DurMedEquOff_Spe_Limit { get; set; }
        //public string VN_EduSerOff_Spe_Limit { get; set; }
        //public string VN_HemOff_Spe_Limit { get; set; }
        //public string VN_InfDiaOff_Spe_Limit { get; set; }
        //public string VN_InfTreOff_Spe_Limit { get; set; }
        //public string VN_MasTheOff_Spe_Limit { get; set; }
        //public string VN_MorObeOff_Spe_Limit { get; set; }
        //public string VN_MorObeSurOff_Spe_Limit { get; set; }
        //public string VN_NonRouHeaOff_Spe_Limit { get; set; }
        //public string VN_OrtOff_Spe_Limit { get; set; }
        //public string VN_OrthopOff_Spe_Limit { get; set; }
        //public string VN_Podoff_Spe_Limit { get; set; }
        //public string VN_ProOff_Spe_Limit { get; set; }
        //public string VN_PulRehOff_Spe_Limit { get; set; }
        //public string VN_SecSurOff_Spe_Limit { get; set; }
        //public string VN_SleDisOff_Spe_Limit { get; set; }
        //public string VN_SmoCesOff_Spe_Limit { get; set; }
        //public string VN_SplPhyoNRtn_Spe_Limit { get; set; }
        //public string VN_TMJNonSurPedOff_Spe_Limit { get; set; }
        //public string VN_TMJSurPedOff_Spe_Limit { get; set; }
        //public string VN_TMJNonSurAduOff_Spe_Limit { get; set; }
        //public string VN_TMJSurAduOff_Spe_Limit { get; set; }
        //public string VN_TraOff_Spe_Limit { get; set; }
        //public string VN_NonRtnVsn_Spe_Limit { get; set; }
        //public string VN_WigOff_Spe_Limit { get; set; }
        //#endregion

        //#region EQN-930 "Sleep Disorders"  and "Chiropractic" Services weren't included in EQN-806 as a part of the Benefit Matrix Mockup
        //public string VN_T1_Chiro_PCP_Value { get; set; }
        //public string VN_T2_Chiro_PCP_Value { get; set; }
        //public string VN_T3_Chiro_PCP_Value { get; set; }
        //public string VN_T4_Chiro_PCP_Value { get; set; }
        //public string VN_Chiro_PCP_Limit { get; set; }

        //public string VN_T1_Chiro_Spe_Value { get; set; }
        //public string VN_T2_Chiro_Spe_Value { get; set; }
        //public string VN_T3_Chiro_Spe_Value { get; set; }
        //public string VN_T4_Chiro_Spe_Value { get; set; }
        //public string VN_Chiro_Spe_Limit { get; set; }

        //public string VN_T1_SleDisStu_Spe_Value { get; set; }
        //public string VN_T2_SleDisStu_Spe_Value { get; set; }
        //public string VN_T3_SleDisStu_Spe_Value { get; set; }
        //public string VN_T4_SleDisStu_Spe_Value { get; set; }
        //public string VN_SleDisStu_Spe_Limit { get; set; }
        //#endregion

        //#region Adding corresponding mapping properties for "0-90 Day Supply - Mail"  and  "0-90 Day Supply - Retail" added to the Prescription Drug Repeater in Medical Document.
        //public string VN_PreBen_090DSMailGen { get; set; }
        //public string VN_PreBen_090DSMailPref { get; set; }
        //public string VN_PreBen_090DSMailNonPref { get; set; }
        //public string VN_PreBen_090DSMailSpe { get; set; }

        //public string VN_PreBen_090DSRetailGen { get; set; }
        //public string VN_PreBen_090DSRetailPref { get; set; }
        //public string VN_PreBen_090DSRetailNonPref { get; set; }
        //public string VN_PreBen_090DSRetailSpe { get; set; }
        //#endregion

        //#region Add 4 new dropdown options for Benefit Supply - "35-90 Day Supply - Mail"  ;  "35-90 Day Supply - Retail"  ;  "30 Day Supply – Preferred Retail"  and  "90 Day Supply – Preferred Mail"
        //public string VN_PreBen_3DSPRGen { get; set; }
        //public string VN_PreBen_3DSPRPrefBrand { get; set; }
        //public string VN_PreBen_3DSPRNonPrefBrand { get; set; }
        //public string VN_PreBen_3DSPRSplMedi { get; set; }

        //public string VN_PreBen_3590DSMGen { get; set; }
        //public string VN_PreBen_3590DSMPrefBrand { get; set; }
        //public string VN_PreBen_3590DSMNonPrefBrand { get; set; }
        //public string VN_PreBen_3590DSMSplMedi { get; set; }

        //public string VN_PreBen_3590DSRGen { get; set; }
        //public string VN_PreBen_3590DSRPrefBrand { get; set; }
        //public string VN_PreBen_3590DSRNonPrefBrand { get; set; }
        //public string VN_PreBen_3590DSRSplMedi { get; set; }

        //public string VN_PreBen_90DSPGen { get; set; }
        //public string VN_PreBen_90DSPPrefBrand { get; set; }
        //public string VN_PreBen_90DSPNonPrefBrand { get; set; }
        //public string VN_PreBen_90DSPSplMedi { get; set; }
        //#endregion

        //#region Add two elements in the Admin Form named "Termination Date" and "Run Outs"
        //public string VN_RunOuts_Value { get; set; }
        //#endregion

        //#region OOP Copay Information

        //public string VN_CopOutofPoc_Max { get; set; }
        //public string VN_CopOutofPoc_Max_2 { get; set; }
        //public string VN_GI_OOPCopayInfo_T1_Fmly { get; set; }
        //public string VN_GI_OOPCopayInfo_T1_Indv { get; set; }
        //public string VN_GI_OOPCopayInfo_T1_OT { get; set; }
        //public string VN_GI_OOPCopayInfo_T2_Fmly { get; set; }
        //public string VN_GI_OOPCopayInfo_T2_Indv { get; set; }
        //public string VN_GI_OOPCopayInfo_T2_OT { get; set; }
        //public string VN_GI_OOPCopayInfo_T3_Fmly { get; set; }
        //public string VN_GI_OOPCopayInfo_T3_Indv { get; set; }
        //public string VN_GI_OOPCopayInfo_T3_OT { get; set; }
        //public string VN_GI_OOPCopayInfo_T4_Fmly { get; set; }
        //public string VN_GI_OOPCopayInfo_T4_Indv { get; set; }
        //public string VN_GI_OOPCopayInfo_T4_OT { get; set; }
        //#endregion

        //#endregion

    }
}