//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace tmg.equinox.integration.qhplite.Ver2016.XMLExport
{
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.18020.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("excelCellVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class ExcelCellVO
    {

        private string cellNameField;

        private string cellValueField;

        private string rowNumberField;

        private string colNumberField;

        private string cellLocationField;

        /// <remarks/>
        public string cellName
        {
            get
            {
                return this.cellNameField;
            }
            set
            {
                this.cellNameField = value;
            }
        }

        /// <remarks/>
        public string cellValue
        {
            get
            {
                return this.cellValueField;
            }
            set
            {
                this.cellValueField = value;
            }
        }

        /// <remarks/>
        public string rowNumber
        {
            get
            {
                return this.rowNumberField;
            }
            set
            {
                this.rowNumberField = value;
            }
        }

        /// <remarks/>
        public string colNumber
        {
            get
            {
                return this.colNumberField;
            }
            set
            {
                this.colNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cellLocation
        {
            get
            {
                return this.cellLocationField;
            }
            set
            {
                this.cellLocationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("headerVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class HeaderVO
    {

        private ExcelCellVO issuerIdField;

        private ExcelCellVO statePostalCodeField;

        private ExcelCellVO statePostalNameField;

        private ExcelCellVO marketCoverageField;

        private ExcelCellVO dentalPlanOnlyIndField;

        private ExcelCellVO tinField;

        private string applicationIdField;

        /// <remarks/>
        public ExcelCellVO issuerId
        {
            get
            {
                return this.issuerIdField;
            }
            set
            {
                this.issuerIdField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO statePostalCode
        {
            get
            {
                return this.statePostalCodeField;
            }
            set
            {
                this.statePostalCodeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO statePostalName
        {
            get
            {
                return this.statePostalNameField;
            }
            set
            {
                this.statePostalNameField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO marketCoverage
        {
            get
            {
                return this.marketCoverageField;
            }
            set
            {
                this.marketCoverageField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO dentalPlanOnlyInd
        {
            get
            {
                return this.dentalPlanOnlyIndField;
            }
            set
            {
                this.dentalPlanOnlyIndField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }

        /// <remarks/>
        public string applicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("benefitAttributeVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class BenefitAttributeVO
    {

        private ExcelCellVO benefitTypeCodeField;

        private ExcelCellVO isEHBField;

        private ExcelCellVO isStateMandateField;

        private ExcelCellVO isBenefitCoveredField;

        private ExcelCellVO serviceLimitField;

        private ExcelCellVO quantityLimitField;

        private ExcelCellVO unitLimitField;

        private ExcelCellVO minimumStayField;

        private ExcelCellVO exclusionField;

        private ExcelCellVO explanationField;

        private ExcelCellVO ehbVarianceReasonField;

        private ExcelCellVO subjectToDeductibleTier1Field;

        private ExcelCellVO subjectToDeductibleTier2Field;

        private ExcelCellVO excludedInNetworkMOOPField;

        private ExcelCellVO excludedOutOfNetworkMOOPField;

        /// <remarks/>
        public ExcelCellVO benefitTypeCode
        {
            get
            {
                return this.benefitTypeCodeField;
            }
            set
            {
                this.benefitTypeCodeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isEHB
        {
            get
            {
                return this.isEHBField;
            }
            set
            {
                this.isEHBField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isStateMandate
        {
            get
            {
                return this.isStateMandateField;
            }
            set
            {
                this.isStateMandateField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isBenefitCovered
        {
            get
            {
                return this.isBenefitCoveredField;
            }
            set
            {
                this.isBenefitCoveredField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO serviceLimit
        {
            get
            {
                return this.serviceLimitField;
            }
            set
            {
                this.serviceLimitField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO quantityLimit
        {
            get
            {
                return this.quantityLimitField;
            }
            set
            {
                this.quantityLimitField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO unitLimit
        {
            get
            {
                return this.unitLimitField;
            }
            set
            {
                this.unitLimitField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO minimumStay
        {
            get
            {
                return this.minimumStayField;
            }
            set
            {
                this.minimumStayField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO exclusion
        {
            get
            {
                return this.exclusionField;
            }
            set
            {
                this.exclusionField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO explanation
        {
            get
            {
                return this.explanationField;
            }
            set
            {
                this.explanationField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO ehbVarianceReason
        {
            get
            {
                return this.ehbVarianceReasonField;
            }
            set
            {
                this.ehbVarianceReasonField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO subjectToDeductibleTier1
        {
            get
            {
                return this.subjectToDeductibleTier1Field;
            }
            set
            {
                this.subjectToDeductibleTier1Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO subjectToDeductibleTier2
        {
            get
            {
                return this.subjectToDeductibleTier2Field;
            }
            set
            {
                this.subjectToDeductibleTier2Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO excludedInNetworkMOOP
        {
            get
            {
                return this.excludedInNetworkMOOPField;
            }
            set
            {
                this.excludedInNetworkMOOPField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO excludedOutOfNetworkMOOP
        {
            get
            {
                return this.excludedOutOfNetworkMOOPField;
            }
            set
            {
                this.excludedOutOfNetworkMOOPField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("planAttributeVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class PlanAttributeVO
    {

        private ExcelCellVO standardComponentIDField;

        private ExcelCellVO planMarketingNameField;

        private ExcelCellVO hiosProductIDField;

        private ExcelCellVO hpidField;

        private ExcelCellVO networkIDField;

        private ExcelCellVO serviceAreaIDField;

        private ExcelCellVO formularyIDField;

        private ExcelCellVO isNewPlanField;

        private ExcelCellVO planTypeField;

        private ExcelCellVO metalLevelField;

        private ExcelCellVO uniquePlanDesignField;

        private ExcelCellVO qhpOrNonQhpField;

        private ExcelCellVO insurancePlanPregnancyNoticeReqIndField;

        private ExcelCellVO isSpecialistReferralRequiredField;

        private ExcelCellVO healthCareSpecialistReferralTypeField;

        private ExcelCellVO insurancePlanBenefitExclusionTextField;

        private ExcelCellVO indianPlanVariationField;

        private ExcelCellVO hsaEligibilityField;

        private ExcelCellVO employerHSAHRAContributionIndicatorField;

        private ExcelCellVO empContributionAmountForHSAOrHRAField;

        private ExcelCellVO childOnlyOfferingField;

        private ExcelCellVO childOnlyPlanIDField;

        private ExcelCellVO isWellnessProgramOfferedField;

        private ExcelCellVO isDiseaseMgmtProgramsOfferedField;

        private ExcelCellVO ehbApportionmentForPediatricDentalField;

        private ExcelCellVO guaranteedVsEstimatedRateField;

        private ExcelCellVO maximumCoinsuranceForSpecialtyDrugsField;

        private ExcelCellVO maxNumDaysForChargingInpatientCopayField;

        private ExcelCellVO beginPrimaryCareDeductibleOrCoinsuranceAfterSetNumberCopaysField;

        private ExcelCellVO beginPrimaryCareCostSharingAfterSetNumberVisitsField;

        private ExcelCellVO planEffectiveDateField;

        private ExcelCellVO planExpirationDateField;

        private ExcelCellVO outOfCountryCoverageField;

        private ExcelCellVO outOfCountryCoverageDescriptionField;

        private ExcelCellVO outOfServiceAreaCoverageField;

        private ExcelCellVO outOfServiceAreaCoverageDescriptionField;

        private ExcelCellVO nationalNetworkField;

        private ExcelCellVO summaryBenefitAndCoverageURLField;

        private ExcelCellVO enrollmentPaymentURLField;

        private ExcelCellVO planBrochureField;

        /// <remarks/>
        public ExcelCellVO standardComponentID
        {
            get
            {
                return this.standardComponentIDField;
            }
            set
            {
                this.standardComponentIDField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO planMarketingName
        {
            get
            {
                return this.planMarketingNameField;
            }
            set
            {
                this.planMarketingNameField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO hiosProductID
        {
            get
            {
                return this.hiosProductIDField;
            }
            set
            {
                this.hiosProductIDField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO hpid
        {
            get
            {
                return this.hpidField;
            }
            set
            {
                this.hpidField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO networkID
        {
            get
            {
                return this.networkIDField;
            }
            set
            {
                this.networkIDField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO serviceAreaID
        {
            get
            {
                return this.serviceAreaIDField;
            }
            set
            {
                this.serviceAreaIDField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO formularyID
        {
            get
            {
                return this.formularyIDField;
            }
            set
            {
                this.formularyIDField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isNewPlan
        {
            get
            {
                return this.isNewPlanField;
            }
            set
            {
                this.isNewPlanField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO planType
        {
            get
            {
                return this.planTypeField;
            }
            set
            {
                this.planTypeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO metalLevel
        {
            get
            {
                return this.metalLevelField;
            }
            set
            {
                this.metalLevelField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO uniquePlanDesign
        {
            get
            {
                return this.uniquePlanDesignField;
            }
            set
            {
                this.uniquePlanDesignField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO qhpOrNonQhp
        {
            get
            {
                return this.qhpOrNonQhpField;
            }
            set
            {
                this.qhpOrNonQhpField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO insurancePlanPregnancyNoticeReqInd
        {
            get
            {
                return this.insurancePlanPregnancyNoticeReqIndField;
            }
            set
            {
                this.insurancePlanPregnancyNoticeReqIndField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isSpecialistReferralRequired
        {
            get
            {
                return this.isSpecialistReferralRequiredField;
            }
            set
            {
                this.isSpecialistReferralRequiredField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO healthCareSpecialistReferralType
        {
            get
            {
                return this.healthCareSpecialistReferralTypeField;
            }
            set
            {
                this.healthCareSpecialistReferralTypeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO insurancePlanBenefitExclusionText
        {
            get
            {
                return this.insurancePlanBenefitExclusionTextField;
            }
            set
            {
                this.insurancePlanBenefitExclusionTextField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO indianPlanVariation
        {
            get
            {
                return this.indianPlanVariationField;
            }
            set
            {
                this.indianPlanVariationField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO hsaEligibility
        {
            get
            {
                return this.hsaEligibilityField;
            }
            set
            {
                this.hsaEligibilityField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO employerHSAHRAContributionIndicator
        {
            get
            {
                return this.employerHSAHRAContributionIndicatorField;
            }
            set
            {
                this.employerHSAHRAContributionIndicatorField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO empContributionAmountForHSAOrHRA
        {
            get
            {
                return this.empContributionAmountForHSAOrHRAField;
            }
            set
            {
                this.empContributionAmountForHSAOrHRAField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO childOnlyOffering
        {
            get
            {
                return this.childOnlyOfferingField;
            }
            set
            {
                this.childOnlyOfferingField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO childOnlyPlanID
        {
            get
            {
                return this.childOnlyPlanIDField;
            }
            set
            {
                this.childOnlyPlanIDField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isWellnessProgramOffered
        {
            get
            {
                return this.isWellnessProgramOfferedField;
            }
            set
            {
                this.isWellnessProgramOfferedField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO isDiseaseMgmtProgramsOffered
        {
            get
            {
                return this.isDiseaseMgmtProgramsOfferedField;
            }
            set
            {
                this.isDiseaseMgmtProgramsOfferedField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO ehbApportionmentForPediatricDental
        {
            get
            {
                return this.ehbApportionmentForPediatricDentalField;
            }
            set
            {
                this.ehbApportionmentForPediatricDentalField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO guaranteedVsEstimatedRate
        {
            get
            {
                return this.guaranteedVsEstimatedRateField;
            }
            set
            {
                this.guaranteedVsEstimatedRateField = value;
            }
        }



        /// <remarks/>
        public ExcelCellVO planEffectiveDate
        {
            get
            {
                return this.planEffectiveDateField;
            }
            set
            {
                this.planEffectiveDateField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO planExpirationDate
        {
            get
            {
                return this.planExpirationDateField;
            }
            set
            {
                this.planExpirationDateField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfCountryCoverage
        {
            get
            {
                return this.outOfCountryCoverageField;
            }
            set
            {
                this.outOfCountryCoverageField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfCountryCoverageDescription
        {
            get
            {
                return this.outOfCountryCoverageDescriptionField;
            }
            set
            {
                this.outOfCountryCoverageDescriptionField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfServiceAreaCoverage
        {
            get
            {
                return this.outOfServiceAreaCoverageField;
            }
            set
            {
                this.outOfServiceAreaCoverageField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfServiceAreaCoverageDescription
        {
            get
            {
                return this.outOfServiceAreaCoverageDescriptionField;
            }
            set
            {
                this.outOfServiceAreaCoverageDescriptionField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO nationalNetwork
        {
            get
            {
                return this.nationalNetworkField;
            }
            set
            {
                this.nationalNetworkField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO summaryBenefitAndCoverageURL
        {
            get
            {
                return this.summaryBenefitAndCoverageURLField;
            }
            set
            {
                this.summaryBenefitAndCoverageURLField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO enrollmentPaymentURL
        {
            get
            {
                return this.enrollmentPaymentURLField;
            }
            set
            {
                this.enrollmentPaymentURLField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO planBrochure
        {
            get
            {
                return this.planBrochureField;
            }
            set
            {
                this.planBrochureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("sBCVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class SBCVO
    {

        private ExcelCellVO havingBabyDeductibleField;

        private ExcelCellVO havingBabyCoPaymentField;

        private ExcelCellVO havingBabyCoInsuranceField;

        private ExcelCellVO havingBabyLimitField;

        private ExcelCellVO havingDiabetesDeductibleField;

        private ExcelCellVO havingDiabetesCopayField;

        private ExcelCellVO havingDiabetesCoInsuranceField;

        private ExcelCellVO havingDiabetesLimitField;

        private ExcelCellVO treatmentDeductibleField;

        private ExcelCellVO treatmentCopayField;

        private ExcelCellVO treatmentCoInsuranceField;

        private ExcelCellVO treatmentLimitField;

        /// <remarks/>
        public ExcelCellVO havingBabyDeductible
        {
            get
            {
                return this.havingBabyDeductibleField;
            }
            set
            {
                this.havingBabyDeductibleField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingBabyCoPayment
        {
            get
            {
                return this.havingBabyCoPaymentField;
            }
            set
            {
                this.havingBabyCoPaymentField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingBabyCoInsurance
        {
            get
            {
                return this.havingBabyCoInsuranceField;
            }
            set
            {
                this.havingBabyCoInsuranceField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingBabyLimit
        {
            get
            {
                return this.havingBabyLimitField;
            }
            set
            {
                this.havingBabyLimitField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingDiabetesDeductible
        {
            get
            {
                return this.havingDiabetesDeductibleField;
            }
            set
            {
                this.havingDiabetesDeductibleField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingDiabetesCopay
        {
            get
            {
                return this.havingDiabetesCopayField;
            }
            set
            {
                this.havingDiabetesCopayField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingDiabetesCoInsurance
        {
            get
            {
                return this.havingDiabetesCoInsuranceField;
            }
            set
            {
                this.havingDiabetesCoInsuranceField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO havingDiabetesLimit
        {
            get
            {
                return this.havingDiabetesLimitField;
            }
            set
            {
                this.havingDiabetesLimitField = value;
            }
        }

        public ExcelCellVO treatmentDeductible
        {
            get
            {
                return this.treatmentDeductibleField;
            }
            set
            {
                this.treatmentDeductibleField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO treatmentCopay
        {
            get
            {
                return this.treatmentCopayField;
            }
            set
            {
                this.treatmentCopayField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO treatmentCoInsurance
        {
            get
            {
                return this.treatmentCoInsuranceField;
            }
            set
            {
                this.treatmentCoInsuranceField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO treatmentLimit
        {
            get
            {
                return this.treatmentLimitField;
            }
            set
            {
                this.treatmentLimitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("AVCalVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class AVCalVO
    {

        private ExcelCellVO maximumCoinsuranceForSpecialtyDrugsField;

        private ExcelCellVO maxNumDaysForChargingInpatientCopayField;

        private ExcelCellVO beginPrimaryCareCostSharingAfterSetNumberVisitsField;

        private ExcelCellVO beginPrimaryCareDeductibleOrCoinsuranceAfterSetNumberCopaysField;

        /// <remarks/>
        public ExcelCellVO maximumCoinsuranceForSpecialtyDrugs
        {
            get
            {
                return this.maximumCoinsuranceForSpecialtyDrugsField;
            }
            set
            {
                this.maximumCoinsuranceForSpecialtyDrugsField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO maxNumDaysForChargingInpatientCopay
        {
            get
            {
                return this.maxNumDaysForChargingInpatientCopayField;
            }
            set
            {
                this.maxNumDaysForChargingInpatientCopayField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO beginPrimaryCareCostSharingAfterSetNumberVisits
        {
            get
            {
                return this.beginPrimaryCareCostSharingAfterSetNumberVisitsField;
            }
            set
            {
                this.beginPrimaryCareCostSharingAfterSetNumberVisitsField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO beginPrimaryCareDeductibleOrCoinsuranceAfterSetNumberCopays
        {
            get
            {
                return this.beginPrimaryCareDeductibleOrCoinsuranceAfterSetNumberCopaysField;
            }
            set
            {
                this.beginPrimaryCareDeductibleOrCoinsuranceAfterSetNumberCopaysField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("planDeductibleVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class PlanDeductibleVO
    {

        private ExcelCellVO deductibleTypeField;

        private ExcelCellVO inNetworkTier1IndividualField;

        private ExcelCellVO inNetworkTier1FamilyField;

        private ExcelCellVO coinsuranceInNetworkTier1Field;

        private ExcelCellVO inNetworkTierTwoIndividualField;

        private ExcelCellVO inNetworkTierTwoFamilyField;

        private ExcelCellVO coinsuranceInNetworkTier2Field;

        private ExcelCellVO outOfNetworkIndividualField;

        private ExcelCellVO outOfNetworkFamilyField;

        private ExcelCellVO coinsuranceOutofNetworkField;

        private ExcelCellVO combinedInOrOutNetworkIndividualField;

        private ExcelCellVO combinedInOrOutNetworkFamilyField;

        private ExcelCellVO combinedInOrOutTier2Field;

        /// <remarks/>
        public ExcelCellVO deductibleType
        {
            get
            {
                return this.deductibleTypeField;
            }
            set
            {
                this.deductibleTypeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTier1Individual
        {
            get
            {
                return this.inNetworkTier1IndividualField;
            }
            set
            {
                this.inNetworkTier1IndividualField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTier1Family
        {
            get
            {
                return this.inNetworkTier1FamilyField;
            }
            set
            {
                this.inNetworkTier1FamilyField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO coinsuranceInNetworkTier1
        {
            get
            {
                return this.coinsuranceInNetworkTier1Field;
            }
            set
            {
                this.coinsuranceInNetworkTier1Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTierTwoIndividual
        {
            get
            {
                return this.inNetworkTierTwoIndividualField;
            }
            set
            {
                this.inNetworkTierTwoIndividualField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTierTwoFamily
        {
            get
            {
                return this.inNetworkTierTwoFamilyField;
            }
            set
            {
                this.inNetworkTierTwoFamilyField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO coinsuranceInNetworkTier2
        {
            get
            {
                return this.coinsuranceInNetworkTier2Field;
            }
            set
            {
                this.coinsuranceInNetworkTier2Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfNetworkIndividual
        {
            get
            {
                return this.outOfNetworkIndividualField;
            }
            set
            {
                this.outOfNetworkIndividualField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfNetworkFamily
        {
            get
            {
                return this.outOfNetworkFamilyField;
            }
            set
            {
                this.outOfNetworkFamilyField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO coinsuranceOutofNetwork
        {
            get
            {
                return this.coinsuranceOutofNetworkField;
            }
            set
            {
                this.coinsuranceOutofNetworkField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO combinedInOrOutNetworkIndividual
        {
            get
            {
                return this.combinedInOrOutNetworkIndividualField;
            }
            set
            {
                this.combinedInOrOutNetworkIndividualField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO combinedInOrOutNetworkFamily
        {
            get
            {
                return this.combinedInOrOutNetworkFamilyField;
            }
            set
            {
                this.combinedInOrOutNetworkFamilyField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO combinedInOrOutTier2
        {
            get
            {
                return this.combinedInOrOutTier2Field;
            }
            set
            {
                this.combinedInOrOutTier2Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("serviceVisitVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class ServiceVisitVO
    {

        private ExcelCellVO visitTypeField;

        private ExcelCellVO copayInNetworkTier1Field;

        private ExcelCellVO copayInNetworkTier2Field;

        private ExcelCellVO copayOutOfNetworkField;

        private ExcelCellVO coInsuranceInNetworkTier1Field;

        private ExcelCellVO coInsuranceInNetworkTier2Field;

        private ExcelCellVO coInsuranceOutOfNetworkField;

        /// <remarks/>
        public ExcelCellVO visitType
        {
            get
            {
                return this.visitTypeField;
            }
            set
            {
                this.visitTypeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO copayInNetworkTier1
        {
            get
            {
                return this.copayInNetworkTier1Field;
            }
            set
            {
                this.copayInNetworkTier1Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO copayInNetworkTier2
        {
            get
            {
                return this.copayInNetworkTier2Field;
            }
            set
            {
                this.copayInNetworkTier2Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO copayOutOfNetwork
        {
            get
            {
                return this.copayOutOfNetworkField;
            }
            set
            {
                this.copayOutOfNetworkField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO coInsuranceInNetworkTier1
        {
            get
            {
                return this.coInsuranceInNetworkTier1Field;
            }
            set
            {
                this.coInsuranceInNetworkTier1Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO coInsuranceInNetworkTier2
        {
            get
            {
                return this.coInsuranceInNetworkTier2Field;
            }
            set
            {
                this.coInsuranceInNetworkTier2Field = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO coInsuranceOutOfNetwork
        {
            get
            {
                return this.coInsuranceOutOfNetworkField;
            }
            set
            {
                this.coInsuranceOutOfNetworkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("moopVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class MoopVO
    {

        private ExcelCellVO nameField;

        private ExcelCellVO inNetworkTier1IndividualAmountField;

        private ExcelCellVO inNetworkTier1FamilyAmountField;

        private ExcelCellVO inNetworkTier2IndividualAmountField;

        private ExcelCellVO inNetworkTier2FamilyAmountField;

        private ExcelCellVO outOfNetworkIndividualAmountField;

        private ExcelCellVO outOfNetworkFamilyAmountField;

        private ExcelCellVO combinedInOutNetworkIndividualAmountField;

        private ExcelCellVO combinedInOutNetworkFamilyAmountField;

        /// <remarks/>
        public ExcelCellVO name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTier1IndividualAmount
        {
            get
            {
                return this.inNetworkTier1IndividualAmountField;
            }
            set
            {
                this.inNetworkTier1IndividualAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTier1FamilyAmount
        {
            get
            {
                return this.inNetworkTier1FamilyAmountField;
            }
            set
            {
                this.inNetworkTier1FamilyAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTier2IndividualAmount
        {
            get
            {
                return this.inNetworkTier2IndividualAmountField;
            }
            set
            {
                this.inNetworkTier2IndividualAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO inNetworkTier2FamilyAmount
        {
            get
            {
                return this.inNetworkTier2FamilyAmountField;
            }
            set
            {
                this.inNetworkTier2FamilyAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfNetworkIndividualAmount
        {
            get
            {
                return this.outOfNetworkIndividualAmountField;
            }
            set
            {
                this.outOfNetworkIndividualAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO outOfNetworkFamilyAmount
        {
            get
            {
                return this.outOfNetworkFamilyAmountField;
            }
            set
            {
                this.outOfNetworkFamilyAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO combinedInOutNetworkIndividualAmount
        {
            get
            {
                return this.combinedInOutNetworkIndividualAmountField;
            }
            set
            {
                this.combinedInOutNetworkIndividualAmountField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO combinedInOutNetworkFamilyAmount
        {
            get
            {
                return this.combinedInOutNetworkFamilyAmountField;
            }
            set
            {
                this.combinedInOutNetworkFamilyAmountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("costShareVarianceVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class CostShareVarianceVO
    {

        private ExcelCellVO planIdField;

        private ExcelCellVO planMarketingNameField;

        private ExcelCellVO metalLevelField;

        private ExcelCellVO csrVariationTypeField;

        private ExcelCellVO issuerActuarialValueField;

        private ExcelCellVO avCalculatorOutputNumberField;

        private ExcelCellVO medicalAndDrugDeductiblesIntegratedField;

        private ExcelCellVO medicalAndDrugMaxOutOfPocketIntegratedField;

        private ExcelCellVO multipleProviderTiersField;

        private ExcelCellVO firstTierUtilizationField;

        private ExcelCellVO secondTierUtilizationField;

        private SBCVO sbcField;

        private AVCalVO avCalField;

        private MoopVO[] moopListField;

        private PlanDeductibleVO[] planDeductibleListField;

        private ServiceVisitVO[] serviceVisitListField;

        private ExcelCellVO defaultCopayInNetworkField;

        private ExcelCellVO defaultCopayOutOfNetworkField;

        private ExcelCellVO defaultCoInsuranceInNetworkField;

        private ExcelCellVO defaultCoInsuranceOutOfNetworkField;

        /// <remarks/>
        public ExcelCellVO planId
        {
            get
            {
                return this.planIdField;
            }
            set
            {
                this.planIdField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO planMarketingName
        {
            get
            {
                return this.planMarketingNameField;
            }
            set
            {
                this.planMarketingNameField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO metalLevel
        {
            get
            {
                return this.metalLevelField;
            }
            set
            {
                this.metalLevelField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO csrVariationType
        {
            get
            {
                return this.csrVariationTypeField;
            }
            set
            {
                this.csrVariationTypeField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO issuerActuarialValue
        {
            get
            {
                return this.issuerActuarialValueField;
            }
            set
            {
                this.issuerActuarialValueField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO avCalculatorOutputNumber
        {
            get
            {
                return this.avCalculatorOutputNumberField;
            }
            set
            {
                this.avCalculatorOutputNumberField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO medicalAndDrugDeductiblesIntegrated
        {
            get
            {
                return this.medicalAndDrugDeductiblesIntegratedField;
            }
            set
            {
                this.medicalAndDrugDeductiblesIntegratedField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO medicalAndDrugMaxOutOfPocketIntegrated
        {
            get
            {
                return this.medicalAndDrugMaxOutOfPocketIntegratedField;
            }
            set
            {
                this.medicalAndDrugMaxOutOfPocketIntegratedField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO multipleProviderTiers
        {
            get
            {
                return this.multipleProviderTiersField;
            }
            set
            {
                this.multipleProviderTiersField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO firstTierUtilization
        {
            get
            {
                return this.firstTierUtilizationField;
            }
            set
            {
                this.firstTierUtilizationField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO secondTierUtilization
        {
            get
            {
                return this.secondTierUtilizationField;
            }
            set
            {
                this.secondTierUtilizationField = value;
            }
        }

        /// <remarks/>
        public SBCVO sbc
        {
            get
            {
                return this.sbcField;
            }
            set
            {
                this.sbcField = value;
            }
        }

        public AVCalVO avCal
        {
            get
            {
                return this.avCalField;
            }
            set
            {
                this.avCalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("moop", IsNullable = false)]
        public MoopVO[] moopList
        {
            get
            {
                return this.moopListField;
            }
            set
            {
                this.moopListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("planDeductible", IsNullable = false)]
        public PlanDeductibleVO[] planDeductibleList
        {
            get
            {
                return this.planDeductibleListField;
            }
            set
            {
                this.planDeductibleListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceVisit", IsNullable = false)]
        public ServiceVisitVO[] serviceVisitList
        {
            get
            {
                return this.serviceVisitListField;
            }
            set
            {
                this.serviceVisitListField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO defaultCopayInNetwork
        {
            get
            {
                return this.defaultCopayInNetworkField;
            }
            set
            {
                this.defaultCopayInNetworkField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO defaultCopayOutOfNetwork
        {
            get
            {
                return this.defaultCopayOutOfNetworkField;
            }
            set
            {
                this.defaultCopayOutOfNetworkField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO defaultCoInsuranceInNetwork
        {
            get
            {
                return this.defaultCoInsuranceInNetworkField;
            }
            set
            {
                this.defaultCoInsuranceInNetworkField = value;
            }
        }

        /// <remarks/>
        public ExcelCellVO defaultCoInsuranceOutOfNetwork
        {
            get
            {
                return this.defaultCoInsuranceOutOfNetworkField;
            }
            set
            {
                this.defaultCoInsuranceOutOfNetworkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("planAndBenefitsVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class PlanAndBenefitsVO
    {

        private PlanAttributeVO planAttributesField;

        private BenefitAttributeVO[] benefitAttributesListField;

        private CostShareVarianceVO[] costShareVariancesListField;

        /// <remarks/>
        public PlanAttributeVO planAttributes
        {
            get
            {
                return this.planAttributesField;
            }
            set
            {
                this.planAttributesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("benefitAttributes", IsNullable = false)]
        public BenefitAttributeVO[] benefitAttributesList
        {
            get
            {
                return this.benefitAttributesListField;
            }
            set
            {
                this.benefitAttributesListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("costShareVariance", IsNullable = false)]
        public CostShareVarianceVO[] costShareVariancesList
        {
            get
            {
                return this.costShareVariancesListField;
            }
            set
            {
                this.costShareVariancesListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("planAndBenefitsPackageVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class PlanAndBenefitsPackageVO
    {

        private HeaderVO headerField;

        private BenefitAttributeVO[] benefitsListField;

        private PlanAndBenefitsVO[] plansListField;

        /// <remarks/>
        public HeaderVO header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("benefits", IsNullable = false)]
        public BenefitAttributeVO[] benefitsList
        {
            get
            {
                return this.benefitsListField;
            }
            set
            {
                this.benefitsListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("plans", IsNullable = false)]
        public PlanAndBenefitsVO[] plansList
        {
            get
            {
                return this.plansListField;
            }
            set
            {
                this.plansListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://vo.ffe.cms.hhs.gov")]
    [System.Xml.Serialization.XmlRootAttribute("planBenefitTemplateVO", Namespace = "http://vo.ffe.cms.hhs.gov", IsNullable = false)]
    public partial class PlanBenefitTemplateVO
    {

        private string applicationIdField;

        private string lastModifiedByField;

        private System.DateTime lastModifiedDateField;

        private bool lastModifiedDateFieldSpecified;

        private PlanAndBenefitsPackageVO[] packagesListField;

        /// <remarks/>
        public string applicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }

        /// <remarks/>
        public string lastModifiedBy
        {
            get
            {
                return this.lastModifiedByField;
            }
            set
            {
                this.lastModifiedByField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime lastModifiedDate
        {
            get
            {
                return this.lastModifiedDateField;
            }
            set
            {
                this.lastModifiedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedDateSpecified
        {
            get
            {
                return this.lastModifiedDateFieldSpecified;
            }
            set
            {
                this.lastModifiedDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("packages", IsNullable = false)]
        public PlanAndBenefitsPackageVO[] packagesList
        {
            get
            {
                return this.packagesListField;
            }
            set
            {
                this.packagesListField = value;
            }
        }
    }
}
